### ISSUE TITLE
Recalibrate level feelings

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3659]
**Reported by magnate on 26 Nov 2011 23:38 UTC**
Consensus is that level feelings are too low in 3.3.x - some ideas for improvement in this thread:

http://angband.oook.cz/forum/showthread.php?t=5097

**Comment by angband-import** [comment]
**Comment by magnate on 3 Dec 2011 22:06 UTC**
This isn't obviously broken. For object feelings, in 3.3 at dl90, the best two feelings are about twice as common as the worst feeling, and about the same likelihood as the second and third worst, i.e. 2, 2, 3, 5, 5, 3, 2, 2, 1 - that's actually quite a nice distribution for the late game. But it's not so good for the early game: at dl10 it's 1, 1, 1, 2, 8, 24, 24, 24, 13. So if my mental algebra is correct, the divisor needs to be sublinear with dlev such that it approaches linearity at deeper levels. Anyone got a good idea for that?

Monster feelings are much more skewed - they are currently based on total power / depth squared. At dl10: 1, 1, 1, 2, 3, 19, 132, 1062, 1279 - but at dl90: 58, 89, 145, 105, 110, 71, 39, 4, 1. Again the endgame distribution is much better than the early game, but making the depth less than quadratic will exacerbate the late game skew. Maybe the solution here is to use depth cubed? That should promote some of the lower levels without messing up the later levels.

**Comment by angband-import** [comment]
**Comment by magnate on 6 Dec 2011 01:15 UTC**
[194a5a2] in v4 changes object feelings to use the square of object value, making individual powerful objects much more important. We'll see how this works before porting to V.

**Comment by angband-import** [comment]
**Comment by magnate on 9 Dec 2011 10:57 UTC**
Weak artifacts are still not generating decent feelings, so they need a boost purely for being artifacts. But we have to be careful of overflows ... ah, I think I have it - we can test for c->good_item and just bump up the feeling ...

**Comment by angband-import** [comment]
**Comment by magnate on 12 Dec 2011 15:56 UTC**
IMO these are working quite well: http://angband.oook.cz/forum/showthread.php?p=64689#post64689

**Comment by angband-import** [comment]
**Comment by magnate on 4 Mar 2012 08:39 UTC**
Ok, the object changes have been ported to V in [1c96ef9], but using depth cubed didn't seem to work at all well for improving the distribution of monster feelings. Time for some more serious analysis.

**Comment by angband-import** [comment]
**Comment by fizzix on 4 May 2012 23:06 UTC**
Monster feeling recalibration punted to 3.5

**Comment by NickMcConnell** [comment]
Obsolete now.
