### ISSUE TITLE
Detect trap border interacting poorly with solid walls in GCU

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3681]
**Reported by non on 31 Dec 2011 07:17 UTC**
We handle the colors wrong on the trap detection border when reversing the colors.

**Comment by angband-import** [comment]
**Comment by takkaria on 27 Apr 2013 23:16 UTC**
Assigning open bugs to 3.5 for fixing.

**Comment by NickMcConnell** [comment]
Very obsolete.
