### ISSUE TITLE
Lurker display issues

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3691]
**Reported by cunninggabe on 2 Mar 2012 14:26 UTC**
Someone a while back suggested that a Lurker should stop looking like the floor once the player is aware of it. Making this change in ascii mode is easy, but there are some tile-mode issues:

1. Original tiles and Shockbolt's tiles currently show Lurkers even before the player is aware. I think this will not be too difficult to fix.
2. Other tilesets don't have any tile for Lurkers at all.

In general, how do we deal with tilesets when we want to add a new monster? That has always mystified me.

**Comment by angband-import** [comment]
**Modified by takkaria on 27 Apr 2013 22:56 UTC**

**Comment by backwardsEric** [comment]
(1) is fixed by https://github.com/angband/angband/pull/5447 .  Resolving this now requires assigning a new glyph for lurker in monster_base.txt and setting new tile assignments (or altering the tile images) for Lurker and Trapper in adam-bolt/graf-new.prf and nomad/graf-nmd.prf.
