### ISSUE TITLE
Unable to build GCU on OpenBSD

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3705]
**Reported by aerdan on 3 Apr 2012 13:26 UTC**
At the moment it is impossible to build the GCU interface on OpenBSD using autoconf; OpenBSD provides curses as part of its core library. Unlike ncurses on Linux, it does not provide ncurses5-config or ncursesw5-config, which the configure script presently uses to try and detect curses.

I think it would be useful to check for a function we require in curses in a manner similar to that of ZSNES's configure script.

**Comment by angband-import** [comment]
**Comment by takkaria on 27 Apr 2013 23:16 UTC**
Assigning open bugs to 3.5 for fixing.

**Comment by angband-import** [comment]
**Comment by vext01 on 13 Jul 2015 10:23 UTC**
For what it's worth this allows GCU to be detected:
https://github.com/jasperla/openbsd-wip/blob/master/games/angband/patches/patch-configure_ac

```
$OpenBSD$

Pick up ncursesw on OpenBSD. We do not deal with ncursesw via pkg-config
(as it is in openbsd base), which is what the build system appears to
expect.

--- configure.ac.orig	Sat Jan  3 23:45:00 2015
+++ configure.ac	Mon Apr  6 14:12:11 2015
\@\@ -224,17 +224,19 \@\@ AC_ARG_ENABLE(sdl_mixer,
 
 MAINFILES="\$(BASEMAINFILES)"
 
-dnl curses checking
-if test "$enable_curses" = "yes"; then
-	AM_PATH_NCURSESW(with_curses=yes, with_curses=no)
-	if test "$with_curses" = "yes"; then
-		AC_DEFINE(USE_NCURSES, 1, [Define to 1 if NCurses is found.])
-		AC_DEFINE(USE_GCU, 1, [Define to 1 if using the Curses frontend.])
-		CFLAGS="${CFLAGS} ${NCURSES_CFLAGS}"
-		LIBS="${LIBS} ${NCURSES_LIBS}"
-		MAINFILES="${MAINFILES} \$(GCUMAINFILES)"
-	fi 
-fi
+dnl curses checking - build system hosed for OpenBSD
+dnl yes, we have this stuff
+
+dnl if test "$enable_curses" = "yes"; then
+dnl 	AM_PATH_NCURSESW(with_curses=yes, with_curses=no)
+dnl 	if test "$with_curses" = "yes"; then
+ 		AC_DEFINE(USE_NCURSES, 1, [Define to 1 if NCurses is found.])
+ 		AC_DEFINE(USE_GCU, 1, [Define to 1 if using the Curses frontend.])
+dnl 		CFLAGS="${CFLAGS} ${NCURSES_CFLAGS}"
+ 		LIBS="${LIBS} -lncursesw"
+ 		MAINFILES="${MAINFILES} \$(GCUMAINFILES)"
+dnl 	fi 
+dnl fi
 
 AC_CHECK_FUNCS([mvwaddnwstr use_default_colors can_change_color])
 
```

Of course, a real fix is probably needed.

**Comment by angband-import** [comment]
**Comment by myshkin on 2 Feb 2016 18:53 UTC**
Another data point, from Mr_Bones_ on IRC: autoconf is broken on gentoo as well because the installed package there is ncurses6. See the [https://bugs.gentoo.org/show_bug.cgi?id=572794 gentoo ticket].

**Comment by angband-import** [comment]
**Comment by vext01 on 20 Sep 2016 09:17 UTC**
FWIW, on OpenBSD the issue is not autoconf, there is a custom macro which uses ncursesw5-config to get ncurses flags. OpenBSD does not use this program as ncursesw is in base.

related:
http://trac.rephial.org/ticket/1976

**Comment by NickMcConnell** [comment]
Punting to future on the off chance it's still relevant.

**Comment by backwardsEric** [comment]
ncurses and wide character support is detected by Angband post 4.2.2 on OpenBSD 6.8 and 6.9 and the gcu interface can be built and run on both.  On Angband's part, the last relevant changes to the ncurses detection were 2 years ago (require tinfo and tinfow) and 5 years ago (fallback if pkg-config checks failed).
