### ISSUE TITLE
Visual artifacts left on the screen with tiles

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3706]
**Reported by fizzix on 5 Apr 2012 01:53 UTC**
Very commonly occurs with the double height tiles and the look command.  Disembodied heads floating in the darkness is common.  Manually refreshing removes the artifacts.  A simple solution could be to add screen refreshes after the screen removes, or ro refresh the tile above the main target.

**Comment by angband-import** [comment]
**Comment by takkaria on 27 Apr 2013 23:16 UTC**
Assigning open bugs to 3.5 for fixing.

**Comment by NickMcConnell** [comment]
Obsolete - new problems have been made and fixed since this was opened.
