### ISSUE TITLE
Build without ncursesw5-config

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3746]
**Reported by nicm on 28 Sep 2012 13:04 UTC**
OpenBSD doesn't have ncursesw5-config and I expect won't for a while (if ever), so how about checking if -lncursesw works too before bailing. Something like this (also attached):

```
diff --git a/acinclude.m4 b/acinclude.m4
index b623a82..e66ce49 100644
--- a/acinclude.m4
+++ b/acinclude.m4
\@\@ -350,11 +350,16 \@\@ AC_ARG_ENABLE(ncursestest, [  --disable-ncursestest       Do not try to compile
   AC_MSG_CHECKING(for ncurses - wide char support)
   no_ncurses=""
   if test "$NCURSES_CONFIG" = "no" ; then
-    no_ncurses=yes
-  else
+    AC_MSG_RESULT(yes)
+    AC_SEARCH_LIBS(setupterm, ncursesw, [NCURSES_LIBS="-lncursesw"], no_ncurses=no)
+  else
+    AC_MSG_RESULT(no)
     NCURSES_CFLAGS=`$NCURSES_CONFIG $ncurses_args --cflags`
     NCURSES_LIBS=`$NCURSES_CONFIG $ncurses_args --libs`
+  fi

+  if test "x$no_ncurses" = x ; then
+    AC_MSG_CHECKING(if ncurses works)
     ac_save_CFLAGS="$CFLAGS"
     ac_save_LIBS="$LIBS"
     CFLAGS="$CFLAGS $NCURSES_CFLAGS"
```

**Comment by angband-import** [comment]
**Attachment from nicm on 28 Sep 2012 13:04 UTC**

REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_1682_GIT_3746/acinclude.m4.diff

**Comment by angband-import** [comment]
**Attachment from nicm on 28 Sep 2012 13:11 UTC**

REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_1682_GIT_3746/acinclude.m4.diff2

**Comment by angband-import** [comment]
**Modified by nicm on 28 Sep 2012 13:05 UTC**

**Comment by angband-import** [comment]
**Comment by nicm on 28 Sep 2012 13:11 UTC**
Erm, this time with yes and no the right way round:

```
diff --git a/acinclude.m4 b/acinclude.m4
index b623a82..5e9d0d4 100644
--- a/acinclude.m4
+++ b/acinclude.m4
\@\@ -350,11 +350,16 \@\@ AC_ARG_ENABLE(ncursestest, [  --disable-ncursestest       Do not try to compile
   AC_MSG_CHECKING(for ncurses - wide char support)
   no_ncurses=""
   if test "$NCURSES_CONFIG" = "no" ; then
-    no_ncurses=yes
-  else
+    AC_MSG_RESULT(no)
+    AC_SEARCH_LIBS(setupterm, ncursesw, [NCURSES_LIBS="-lncursesw"], no_ncurses=no)
+  else 
+    AC_MSG_RESULT(yes)
     NCURSES_CFLAGS=`$NCURSES_CONFIG $ncurses_args --cflags`
     NCURSES_LIBS=`$NCURSES_CONFIG $ncurses_args --libs`
+  fi
 
+  if test "x$no_ncurses" = x ; then
+    AC_MSG_CHECKING(if ncurses works)
     ac_save_CFLAGS="$CFLAGS"
     ac_save_LIBS="$LIBS"
     CFLAGS="$CFLAGS $NCURSES_CFLAGS"
```

**Comment by angband-import** [comment]
**Comment by takkaria on 14 Apr 2013 18:05 UTC**
See also #1638

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 18 Oct 2015 01:54 UTC**
Calling this ongoing

**Comment by backwardsEric** [comment]
https://github.com/angband/angband/commit/780d86b2b00baaac0b308783d1be1c2cae117dfe#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810 added falling back to direct checks for linking with ncurses.  That, with the subsequent changes to configure.ac, is sufficient to allow Angband to properly detect ncurses on OpenBSD 6.9.  Therefore, calling this done.

**Comment by NickMcConnell** [comment]
Great.
