### ISSUE TITLE
Windows does not remember tile size on restart

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3762]
**Reported by fizzix on 1 Nov 2012 19:23 UTC**
Tile size always reverts to default on restart.

**Comment by angband-import** [comment]
**Comment by takkaria on 27 Apr 2013 23:17 UTC**
Assigning open bugs to 3.5 for fixing.

**Comment by NickMcConnell** [comment]
this must have been fixed somewhere, because it's fine now.
