### ISSUE TITLE
Lurkers appearing when Reveal Monsters is cast, but not added to monster list

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3766]
**Reported by daniel-santos on 11 Nov 2012 05:23 UTC**
When casting Reveal Monsters, Lurkers will be visually shown, but selecting them (unexplored) just says "unknown grid" and they do not appear in the monster list.

So there are some questions to answer here I guess.

* Should Reveal Monsters & Rod of Detection show them? They aren't technically invisible, they are disguised.
* On a related note, should these spells also reveal mimics? (my thought is no, personally).

So if it should reveal them, they need to appear in the monster list.  If it shouldn't reveal them, then we shouldn't be showing their graphic (I'm using the David Gervais graphics in sdl mode).

I'm running from git origin/master (post 3.5-dev) with a number of experimental patches, but none that should affect that code

**Comment by angband-import** [comment]
**Comment by takkaria on 27 Apr 2013 23:17 UTC**
Assigning open bugs to 3.5 for fixing.

**Comment by NickMcConnell** [comment]
This seems to be fixed now.
