### ISSUE TITLE
Accidental Earthquakes aren't fun

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3776]
**Reported by daniel-santos on 6 Dec 2012 00:06 UTC**
I find it annoying when I'm just buzzing away on a priest or paladin and I accidentally hit the key sequence to cast Earthquake when I meant to cast something else.  This is bad because my Flyswatter of Companionship +2 just got destroyed.

This patch adds an option to prompt the user prior to a voluntary evocation of Earthquake or Destruction spells.  Prompt is not applicable for using an unidentified scroll or staff, because it's the surprises in life that keep it interesting.

**Comment by angband-import** [comment]
**Attachment from daniel-santos on 6 Dec 2012 00:06 UTC**

REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_1714_GIT_3776/0001-Add-prompt_destructive-option.txt

**Comment by angband-import** [comment]
**Comment by daniel-santos on 6 Dec 2012 00:13 UTC**
Oh, also, this doesn't affect weapons with an earthquake effect.  Specifically, it adds the prompt to casting either mage or priest spells of earthquake or destruction as well as identified staves and scrolls of these types.

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 18 Oct 2015 01:54 UTC**
Moving to future

**Comment by NickMcConnell** [comment]
I don't want to be micro-managing player miskeying.
