### ISSUE TITLE
Add passive LOS searching

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3805]
**Reported by takkaria on 27 Apr 2013 22:36 UTC**
a la ewert's patch, which detects a few squares in front of you

**Comment by angband-import** [comment]
**Comment by takkaria on 26 Jul 2013 17:14 UTC**
Punting to post 3.5.

**Comment by NickMcConnell** [comment]
I'm not seeing a need.

**Comment by NickMcConnell** [comment]
In fact, completely obsolete given the change to searching in 4.1.
