### ISSUE TITLE
Missing sounds

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3808]
**Reported by draconisPW on 30 Apr 2013 09:38 UTC**
After replacing the old sound set by Dubtrain's sound pack, it is probably time to implement the missing sounds:

* MSG_BOLD: already implemented, missing in sound.cfg (line was added to the old 3.4 sound.cfg but forgotten in the new one)

* MSG_STORE_ENTER/MSG_STORE_LEAVE/MSG_STORE_HOME (not in the code)

* MSG_WALK (but wouldn't that be extremely annoying?)

* MSG_DESTROY: the sample limit is 8, but 10 samples are referenced (which means that the last two are never played); perhaps increase the limit?

* MSG_KILL_KING: you kill Morgoth and all you get is a stupid guitar chord?

* MSG_MON_BITE: mco_bite_crunch.mp3 referenced from the sound pack doesn't exist; also 13 samples are referenced, five of which are never played; increase the limit?

* MSG_SUM_AINU: still referenced as "summon_angel" in sound.cfg when it should be "summon_ainu"

**Comment by angband-import** [comment]
**Modified by takkaria on 25 Nov 2013 22:50 UTC**

**Comment by backwardsEric** [comment]
The issues with MSG_BOLD, MSG_DESTROY, MSG_MON_BITE, and MSG_SUM_AINU appear to have all been resolved prior to 4.2.3.

#5154 tries to resolve the issue with MSG_STORE_ENTER/MSG_STORE_LEAVE/MSG_STORE_HOME.

That leaves MSG_WALK and MSG_KILL_KING as still unaddressed.

**Comment by NickMcConnell** [comment]
I agree with the original comment that MSG_WALK would be really annoying, and am not fussed about MSG_KILL_KING, so I'm going to call this done.
