### ISSUE TITLE
Changing font size on Windows doesn't refresh terms properly

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3820]
**Reported by takkaria on 26 Jul 2013 17:11 UTC**
Had some issues with changing the font/tile sizes not updating properly on Windows 7 64-bit. Probably best illustrated by example:

* If I'm in ASCII mode and, say, change the font size from 8x12 to 16x24, the font size increases, but the space that it's displayed in does not - i.e., I get chopped off 16x24 characters crammed into 8x12 tiles. (Conversely, if I make the font size smaller, the letters end up swimming in black space.)

* If I switch the display mode over to one of the tile sets, the tiles appear at 8x12 size and the letters are still truncated. If I then switch back to ASCII, the tile size will update properly and I'll get the font at the correct 16x24.

(from http://angband.oook.cz/forum/showthread.php?t=6220)

**Comment by angband-import** [comment]
**Modified by takkaria on 7 Dec 2013 17:06 UTC**

**Comment by angband-import** [comment]
**Modified by takkaria on 21 Dec 2013 19:02 UTC**

**Comment by NickMcConnell** [comment]
Resolved in 11c5077e4
