### ISSUE TITLE
New item tag display (1/2/3 instead of a/b/c) fails with duplicate tags

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3837]
**Reported by takkaria on 17 Sep 2013 11:17 UTC**
e.g. If you've got a melee weapon and a digger inscribed with '\@w1', but you wield an un-ID'd weapon to find out what it is, when you want to go back to your main weapon, or digger, you can't choose between them because they're both labelled '1'.  Display should revert to letters when duplicated.

**Comment by angband-import** [comment]
**Comment by takkaria on 1 Oct 2013 11:53 UTC**
New item tag display reverted for 3.5.0 (original commit was ae5f2cb5), so punting this to 3.5.1.

**Comment by angband-import** [comment]
**Modified by takkaria on 24 Dec 2013 16:28 UTC**

**Comment by NickMcConnell** [comment]
Obsolete, I think
