### ISSUE TITLE
New item tag display (1/2/3 instead of a/b/c) not sorted

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3838]
**Reported by takkaria on 17 Sep 2013 11:18 UTC**
It would make sense to sort it with 0-9 at the top and the normal letters afterward.  This would be less confusing.

**Comment by angband-import** [comment]
**Comment by takkaria on 1 Oct 2013 11:53 UTC**
New item tag display reverted for 3.5.0 (original commit was ae5f2cb5), so punting this to 3.5.1.

**Comment by angband-import** [comment]
**Modified by takkaria on 24 Dec 2013 16:28 UTC**

**Comment by NickMcConnell** [comment]
Obsolete
