### ISSUE TITLE
Inven/equip context menus fail to allow dropping

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3853]
**Reported by takkaria on 10 Oct 2013 17:37 UTC**
"Finally, dropping items from inventory/equipment menus still has persistent, albeit intermittent, bugs. For example, you id an item and go to drop it, but the option isn't available. You have to leave the menus, select "d"rop and then drop the item. Still haven't figured out why this is intermittent. Possibly in connection with having inscriptions on the items, and/or items being ego or artifact items, and/or items in the quiver?"

from http://angband.oook.cz/forum/showthread.php?t=6357

**Comment by angband-import** [comment]
**Comment by bensemmler on 21 Nov 2013 00:21 UTC**
I can't reproduce this as of dd17148e2860. I have tried dropping the following by context menu, both from the inventory list and the equipment list, and all drop correctly:
- artifacts
- ego armor and weapons
- ego arrows and regular arrows (dropping one and dropping all)
- inscribed weapons and arrows
- unidentified weapons and freshly identified weapons

**Comment by angband-import** [comment]
**Comment by bensemmler on 21 Nov 2013 04:44 UTC**
Replying to [comment:1 molybdenum]:
> I can't reproduce this as of dd17148e2860. I have tried dropping the following by context menu, both from the inventory list and the equipment list, and all drop correctly:
> - artifacts
> - ego armor and weapons
> - ego arrows and regular arrows (dropping one and dropping all)
> - inscribed weapons and arrows
> - unidentified weapons and freshly identified weapons

Somehow, I did manage to get this to happen, but it fixed itself on relaunch so I couldn't trace it. I had generated a bunch of items, picked them up, dropped/thrown a bunch and then some arrows and a few mushrooms weren't droppable at all.

**Comment by NickMcConnell** [comment]
I'm calling this fixed.
