### ISSUE TITLE
Resizing object list and monster list subwindows to very small sizes causes crashes.

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3869]
**Reported by bensemmler on 23 Dec 2013 00:25 UTC**
See #1611. Doesn't seem to happen on OS X.

"As of dev-668-g13dc1db, when you reduce the horizontal size of the subwindow to minimal, the game crashes. Also the subwindow is not refreshed when you change levels until you move (monster list).
Edit: the game also crashes when resizing the object list subwindow vertically with 3 objects on the screen.

Not fixed. Since I'm under Windows, I can't get any extra log/info about the crash, but it should be easy to track down since it always happens when you resize the subwindow horizontally until you have only 2 columns left."

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 18 Oct 2015 03:44 UTC**
Kicking to future - seems marginal and/or fixed

**Comment by NickMcConnell** [comment]
Not reported for ages, and I can't repeat it.  Closing.
