### ISSUE TITLE
Keymap bug under Linux, unknown port

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3872]
**Reported by takkaria on 6 Jan 2014 15:36 UTC**
http://angband.oook.cz/forum/showthread.php?p=88642#post88642

**Comment by angband-import** [comment]
**Comment by pnd10 on 27 Oct 2014 23:13 UTC**
In targeting mode, the "special" keymaps (q, ,*,+,-,p,o,m,t,5,0,.,g,?) are handled before the keypress is handed off to have its keymap translated.

So an 'o', even with Alt pressed, is caught first before the keymap remaps it.

Keymap translation should really happen at a consistent point when keypresses are first gathered, but there are several code paths.

**Comment by angband-import** [comment]
**Comment by magnate on 29 Dec 2014 22:28 UTC**
Punting to 4.0 release as agreed with Herr Nick on IRC. Presumably this bug will disappear in the restructure ...

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 30 Dec 2014 06:15 UTC**
...along with poverty, suffering and ever having to pay for wifi :)

**Comment by NickMcConnell** [comment]
I assume overtaken by events
