### ISSUE TITLE
Windows port font changing is dodgy

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3876]
**Reported by takkaria on 12 Jan 2014 11:41 UTC**
see http://angband.oook.cz/forum/showpost.php?p=88684&postcount=42

**Comment by angband-import** [comment]
**Comment by magnate on 26 Oct 2014 22:36 UTC**
Not for 3.5.1 unless someone else fixes it - reassigning to Future.

**Comment by NickMcConnell** [comment]
Surely obsolete.
