### ISSUE TITLE
Update SDL frontend to SDL 2.x

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3890]
**Reported by magnate on 3 Nov 2014 20:44 UTC**
Necessary to ship the SDL port in Debian. And a good thing anyway.

Aiming initially for 3.5.1 but if this is the last ticket I will release 3.5.1 and reschedule this for the next release.

**Comment by angband-import** [comment]
**Comment by pnd10 on 3 Nov 2014 23:54 UTC**
Not actually necessary for debian. Debian now prefers SDL2.0, but you can still install dev packages for 1.2, specifically libsdl1.2-dev, libsdl-image1.2-dev, libsdl-sound1.2-dev and libsdl-ttf2.0-dev

**Comment by angband-import** [comment]
**Modified by pnd10 on 7 Nov 2014 23:52 UTC**

**Comment by NickMcConnell** [comment]
Separate SDL2 port included in 4.2
