### ISSUE TITLE
Object list delay

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3941]
**Reported by NickMcConnell on 28 Mar 2015 01:13 UTC**
1. Object sub-window delayed 1 turn. E.g., pick up a potion and it still appears in the sub-window until the next move by either player or monster. The monster sub-window works correctly, kill a monster and it immediately is removed from the sub-window. So should the object sub-window be immediate.
2. Inventory sub-window not showing flavor. E.g., \@ picked up a purple potion. It shows as a Purple Potion on the inventory menu screen, but only as Potion on the sub-window. This is okay with me and may be better, but it is different than 3.5.1 so wanted to be sure it was intended.

Reported by Ingwe Ingweron

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 4 May 2015 11:17 UTC**
2. Is actually as in 3.5.1, but 1 still needs attention

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 13 Jun 2015 06:30 UTC**
This is fixed now

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 25 Jun 2015 13:05 UTC**
Not actually fixed

**Comment by NickMcConnell** [comment]
Seems genuinely fixed now, and I have never been known to be wrong...
