### ISSUE TITLE
Messages running together

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3974]
**Reported by NickMcConnell on 18 Apr 2015 01:20 UTC**
"I'm occasionally getting two pseudo-ID messages merging together instead of being on separate lines when they both occur in the same turn, so you end up seeing something like:

magical... You feel the Iron Shots in (b) in your pack are average...

I think it's because the format of messages about equipped items has changed since 3.5, and some of them are now longer than 80 characters and overflow onto a second line. Before, the message used to be "You feel the Set of Leather Gloves (k) you are using is magical..." (66 characters) and now it's "You feel the Set of Leather Gloves (k) you are wearing on your hands is magical..." (82 characters, too long for a single line)" - Nomad

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 23 May 2015 07:45 UTC**
This is actually unchanged from 3.5.1 - I'm going to regard it as an improvement to be made some time.

**Comment by NickMcConnell** [comment]
Pseudo-ID no longer exists.
