### ISSUE TITLE
Assertion fail in square_istrap()

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4014]
**Reported by NickMcConnell on 26 Sep 2015 00:13 UTC**
"In fight against Ibun I got assertion fail

version: 4.0.2
file: cave-square.c
line: 374
Expression: square_in_bounds(x,y,z)

in a long corridor shooting arrows on Ibun. He spelled a lot and a cold vortex behind him kept breathing on both of us. Somewhat south of map center." - Thraalbeast

This is in square_istrap() - looks likely that this is called sometimes on grids that need not be in bounds.

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 18 Oct 2015 05:22 UTC**
Kicking this one to future - I need more clues

**Comment by NickMcConnell** [comment]
I'm assuming this is obsolete now.
