### ISSUE TITLE
New item property grid

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4035]
**Reported by NickMcConnell on 11 Jul 2016 21:01 UTC**
Implement this:
http://angband.oook.cz/forum/showpost.php?p=111745&postcount=16

**Comment by backwardsEric** [comment]
In the new forums, that post is at the top of the page, https://angband.live/forums/forum/angband/vanilla/7578-regarding-temporary-resist-indicators/page2 , though the forum isn't displaying the screenshot appropriately.  The version archived by the Wayback Machine is post 16 on this page, https://web.archive.org/web/20230609203311/http://angband.oook.cz/forum/showthread.php?s=3efdf6f1f693556726a9f88c07edd3f1&p=111745#post111745 .  The form that this idea was implemented in game is the equippable comparison in the knowledge menus.
