### ISSUE TITLE
Incorrect ncursesw detection on OpenBSD

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4036]
**Reported by vext01 on 11 Sep 2016 20:02 UTC**
The angband build uses ncursesw5-config to detect ncursesw. On OpenBSD (and other BSDs?) there is noncursesw5-config. ncursesw is part of the base system and can be assumed to be always installed.

(Note however that it is probably best to add define _OPEN_SOURCE_EXTENDED as older versions on OpenBSD inherited a broken implementation of some ncurses functions which got stuck in an infinite loop -- I believe this is fixed now. This causes a blank screen upon starting angband).

Thanks

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 21 May 2017 03:46 UTC**
Marking all OpenBSD bugs as such and setting them to Future

**Comment by angband-import** [comment]
**Comment by vext01 on 7 Apr 2019 11:14 UTC**
In Angband 4.1.3, curses is correctly detected, but wide character support is erroneously not detected.

**Comment by backwardsEric** [comment]
With Angband post 4.2.2 and OpenBSD 6.9, curses detection (including wide character support) worked.

**Comment by NickMcConnell** [comment]
OK, can we close this, do you think?

**Comment by backwardsEric** [comment]
I'd say yes if I better knew which OpenBSD versions are in common use.  I only tried 6.9 (apparently the latest release) and didn't try older ones to see if those also work.

**Comment by backwardsEric** [comment]
According to https://en.wikipedia.org/wiki/OpenBSD_version_history , there's a release every 6 months with only the last 2 receiving patches.  Based on that, I'll check to see if 6.8 works as well.  If it does, I'd close all the old ncurses-related OpenBSD issues.

**Comment by backwardsEric** [comment]
ncurses and wide character support is detected by Angband post 4.2.2 on OpenBSD 6.8 and 6.9 and the gcu interface can be built and run on both. On Angband's part, the last relevant changes to the ncurses detection were 2 years ago (require tinfo and tinfow) and 5 years ago (fallback if pkg-config checks failed).
