### ISSUE TITLE
Amulet of & Amulet~

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4098]
**Reported by NickMcConnell on 23 Aug 2017 21:23 UTC**
" Ran into the old "Amulet of & Amulet~" bug; as in that report, the problem amulet was Carlammas." - Sideways

See http://angband.oook.cz/forum/showthread.php?t=7849

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 8 Oct 2017 04:05 UTC**
Can't reproduce, marking as Ongoing

**Comment by NickMcConnell** [comment]
Dammit, I'm closing this.  Hasn't been seen for a while, it can be reopened (or a new issue made) if it reappears.
