### ISSUE TITLE
Interaction between selling prices and curses

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4109]
**Reported by NickMcConnell on 25 Aug 2017 23:36 UTC**
See http://angband.oook.cz/forum/showthread.php?t=8462

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 9 Sep 2017 00:12 UTC**
Also this: http://angband.oook.cz/forum/showpost.php?p=123734&postcount=190

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 28 Oct 2017 06:49 UTC**
Fixed sufficiently for now in 39f74279, kicked to ongoing for better power evaluations on not fully known objects

**Comment by NickMcConnell** [comment]
This is definitely obsolete as of 4.1.
