### ISSUE TITLE
macOS fullscreen issues

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4114]
**Reported by NickMcConnell on 9 Sep 2017 00:14 UTC**
"Mac OS X, I started a game and enabled full screen with Window > Enter Full Screen, then quit with ^X.

When I restarted the game it started in the default-size window but the title screen was incorrectly centred (offset to the bottom right, as if it were being centred for the full screen). Similarly, the main map area appeared blank immediately after loading because \@ was off screen to the bottom right (this fixed itself as soon as I resized the window)." - passer_by

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 28 Oct 2017 06:51 UTC**
Not a big disaster and requires more knowledge of Cocoa than I have, so booting to Ongoing

**Comment by backwardsEric** [comment]
[This pull request](https://github.com/angband/angband/pull/4258) resolves this issue on my system (OS X 10.14; laptop with single screen).  I don't have ready access to a system with multiple displays to check if it works properly there.

**Comment by NickMcConnell** [comment]
I'm calling it done.
