### ISSUE TITLE
Corridor connection issues

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4177]
**Reported by NickMcConnell on 9 Apr 2019 11:13 UTC**
A few things:
- weirdness around circular rooms
- dead end corridors
- corridors which run into interesting rooms with no doors (eg http://angband.oook.cz/forum/showpost.php?p=137525&postcount=301)

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 8 Jul 2019 11:32 UTC**
Last problem was an error in vault.txt, fixed in 0832a2509

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 8 Aug 2019 12:03 UTC**
Punting to future

**Comment by NickMcConnell** [comment]
More of an enhancement than a bug, IMHO

**Comment by igroglaz** [comment]
_A feature_ (tm) :bear:

**Comment by NickMcConnell** [comment]
I'm thinking with #4761 this may actually be complete.  I can't recall what the dead-end corridors were, but there haven't been recent complaints.

**Comment by backwardsEric** [comment]
Dead-end corridors are still possible.  One cause is the random termination condition configured by the third parameter to tunnel: in dungeon-profile.txt; that can fire if the tunnel is more than 10 grids in x or y from where the tunnel started.  Another is if a particular tunnel took too many steps without completing.

After the FEW_ENTRANCES change, I've seen tunnels somewhat like those that used to come with circular rooms near some of the interesting rooms or template rooms with a lot of walls that aren't purely horizontal or vertical but didn't bother to note which particular rooms caused that behavior.

Maybe it's best to close this issue if you feel the original points have been addressed, and let any new complaints about problems with the tunneling get there own issue(s).

**Comment by NickMcConnell** [comment]
Yes indeed.
