### ISSUE TITLE
Improve throwing

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4197]
**Reported by NickMcConnell on 4 Oct 2019 22:05 UTC**
See http://angband.oook.cz/forum/showpost.php?p=140008&postcount=122

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 17 Nov 2019 20:22 UTC**
Mostly done alongside the introduction of O-combat, will leave this open for now

**Comment by NickMcConnell** [comment]
Calling this done for now.
