### ISSUE TITLE
Fail to pick up when running

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4200]
**Reported by NickMcConnell on 4 Oct 2019 22:10 UTC**
See http://angband.oook.cz/forum/showpost.php?p=139903&postcount=98 and posts before it

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by NickMcConnell** [comment]
Can't reproduce this test as of f9fd44493, leaving open for now.

**Comment by NickMcConnell** [comment]
No further reports of this, and no reports back from my [forum post](http://angband.oook.cz/forum/showpost.php?p=145296&postcount=301) on it, I'm closing this.
