### ISSUE TITLE
Monster memory not updating fully

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4202]
**Reported by NickMcConnell on 4 Oct 2019 22:13 UTC**
"I've already seen people mention the wand of darkness not doing damage, so I won't go into that, but I have noticed that both that wand and "raise earth" haven't been updating the relevant elements in monster memory (I assume raise earth is shards damage)." - Oraticus

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 4 Oct 2019 22:45 UTC**
Also see http://angband.oook.cz/forum/showthread.php?t=9552

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by NickMcConnell** [comment]
Not a bug.  The darkness thing doesn't get mentioned in lore because nothing is hurt by weak darkness, and shards doesn't because there is no separate IM_SHARDS flag - the only monsters that resist shards are shards breathers.
