### ISSUE TITLE
Sound not working in new game

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4204]
**Reported by NickMcConnell on 4 Oct 2019 22:17 UTC**
"Tired of my current character, decided to try a blackguard. Killed old character, then tried the new "new game" option. Generated the new character and noticed while moving around the town that the game wasn't making sounds. The option was still set in user interface options for sound on. Quit the game, restart and sounds are back working.

This is on MacOS X." - mrfy

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by NickMcConnell** [comment]
I believe this is fixed (possibly for the second time) in 787c5139b.
