### ISSUE TITLE
Detected traps show as floor until you see them

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4205]
**Reported by NickMcConnell on 4 Oct 2019 22:18 UTC**
This is disconcerting

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 13 Oct 2019 20:25 UTC**
Also:
"Seeing a strange display bug with traps, not sure if this has been reported before. Playing in ascii mode, find a hidden trap, get the messages:

You fall into a spiked pit!
You float gently to the bottom of the pit, neatly avoiding the spikes.

I continue down the corridor a few spaces since I don't see the trap. Back up, still no trap displayed get:

You have disarmed the pit." - mrfy

**Comment by NickMcConnell** [comment]
See also posts 205-208 in [this thread](http://angband.oook.cz/forum/showthread.php?t=9607).

**Comment by NickMcConnell** [comment]
And also [this video](https://www.youtube.com/watch?v=fgOcJ-2FPiQ#t=67m20s).
