### ISSUE TITLE
Improvement to town layout

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4215]
**Reported by NickMcConnell on 4 Oct 2019 22:42 UTC**
See http://angband.oook.cz/forum/showthread.php?t=9573

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 4 Oct 2019 22:42 UTC**

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 13 Oct 2019 11:05 UTC**

**Comment by NickMcConnell** [comment]
Fixed by sanedragon in pull request #536
