### ISSUE TITLE
Unnecessary lines in object_property.txt

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4216]
**Reported by NickMcConnell on 4 Oct 2019 22:44 UTC**
See http://angband.oook.cz/forum/showthread.php?t=9572

**Comment by angband-import** [comment]
**Modified by NickMcConnell on 12 Oct 2019 23:21 UTC**

**Comment by NickMcConnell** [comment]
Lines were necessary, comment only needed (as per Derakon).
