### ISSUE TITLE
Monsters breathe at squares they can't hit

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4219]
**Reported by NickMcConnell on 13 Oct 2019 05:15 UTC**
Reported by wobbly; monster will breathe at the player when the player is at knight's move position behind a wall

**Comment by NickMcConnell** [comment]
Can't confirm this, closing.

**Comment by NickMcConnell** [comment]
Confirmed that the dragon in [this shot](http://angband.oook.cz/screen-show.php?id=4819) (or equivalent) breathes at the player and misses.
This seems to be a mismatch between the call to projectable() in monster_can_cast() (which returns true) and the actual project() function - likely to do with the PROJECT_ARC flag, is my guess.

**Comment by NickMcConnell** [comment]
OK, it seems that the problem is that the projection path is calculated with project_path(), but then los() is used to decide whether a grid can be hit, and they can give different answers.

**Comment by NickMcConnell** [comment]
Which suggests the resolution of allowing grids if they pass los() *or* are on the projection path.
