### ISSUE TITLE
Resistance grid for home

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4234]
**Reported by NickMcConnell on 17 Dec 2019 01:24 UTC**
See http://angband.oook.cz/forum/showthread.php?t=9712

**Comment by backwardsEric** [comment]
On the new forum, that thread is here, https://angband.live/forums/forum/angband/vanilla/9285-weapon-armor-resistances-capabilities-grid-for-home .  The equippable comparison in the knowledge menus is how the idea was implemented in the game.
