### ISSUE TITLE
Quiver problems

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4238]
**Reported by NickMcConnell on 24 Dec 2019 22:25 UTC**
See http://angband.oook.cz/forum/showpost.php?p=141377&postcount=50

**Comment by rdmacko** [comment]
Noob at this. I would like to pull your fixes to the quiver problems and add it to my Angband. I play Ranger and think the changes will improve my play.
Thank you, sir.

**Comment by NickMcConnell** [comment]
What version are you currently playing?

**Comment by rdmacko** [comment]
4.2

Was trying to get to the most current.

**Comment by NickMcConnell** [comment]
Your best bet is to go to the [nightlies page](http://rephial.org/nightlies) and download the latest build from there - that is the current development version.

**Comment by rdmacko** [comment]
Thank you, Nick.

 

What should be the greatest difference with the quiver fixes in place?

Rick

**Comment by rdmacko** [comment]
Hi sir,

Has Windows support gone away from the nightles?
Last 5 or so have not offered it.

Thank  you,

Rick

**Comment by NickMcConnell** [comment]
Currently, yes - we have an issue with the autobuilder we have been using.  I've posted a build of the latest nightly for Windows [here](http://angband.oook.cz/faangband//angband-win-421-g81dfed316.zip).

**Comment by rdmacko** [comment]
Thank you.

It gets to loading to basic pref file then shuts down.
Any clues where I should look?

Thanks,

Rick

**Comment by rdmacko** [comment]
Hi Nick,

When you get a chance, can you send me the August 15th build for Windows
Thank you,

Rick

**Comment by NickMcConnell** [comment]
You should be able to download it from [this post](http://angband.oook.cz/forum/showpost.php?p=147844&postcount=54); in general, I'll post links to any new Windows build in this thread.

**Comment by rdmacko** [comment]
Nick,

Should I be able to extract all the files into a folder and run it?
When I click on the .exe it fires up and looks like it is starting then shuts down.

 

Rick

**Comment by NickMcConnell** [comment]
There may be a problem here - I have to look into it.

**Comment by rdmacko** [comment]
Thank you, sir!
I have tried it with and without the INI and PRF files.

 

And now my current copy of the game is doing the same thing… haha
So, I am guessing it is just a simple setting that that is being tweaked.

Is there a log file I can peruse or send to you?

 

Rick
