### ISSUE TITLE
Patches from backwardsEric

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4239]
**Reported by NickMcConnell on 24 Dec 2019 22:27 UTC**
Several submitted; I will link them here:
http://angband.oook.cz/forum/showpost.php?p=141467&postcount=55

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 24 Dec 2019 22:31 UTC**
http://angband.oook.cz/forum/showpost.php?p=141629&postcount=70

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 26 Dec 2019 21:54 UTC**
http://angband.oook.cz/forum/showpost.php?p=141466&postcount=118

**Comment by backwardsEric** [comment]
The patch for more compact rendering with Cocoa, [http://angband.oook.cz/forum/showpost.php?p=141467&postcount=55](http://angband.oook.cz/forum/showpost.php?p=141467&postcount=55) , is also available as [a pull request for Angband on github](https://github.com/angband/angband/pull/543) .   The patch for the crash when restarting without exiting, [http://angband.oook.cz/forum/showpost.php?p=141629&postcount=70](http://angband.oook.cz/forum/showpost.php?p=141629&postcount=70) is also available as [this pull request for Angband](https://github.com/angband/angband/pull/2805)
