### ISSUE TITLE
Code errors from PowerWyrm (4.2.0 edition)

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4240]
**Reported by NickMcConnell on 24 Dec 2019 22:31 UTC**
Several, as usual :)

First one: http://angband.oook.cz/forum/showpost.php?p=141538&postcount=57

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 26 Dec 2019 22:07 UTC**
Problems with innate frequency: http://angband.oook.cz/forum/showpost.php?p=141862&postcount=127 and http://angband.oook.cz/forum/showpost.php?p=141863&postcount=128

**Comment by angband-import** [comment]
**Comment by NickMcConnell on 26 Dec 2019 22:14 UTC**
Just dumb: http://angband.oook.cz/forum/showpost.php?p=141888&postcount=135

**Comment by NickMcConnell** [comment]
Copy/paste: http://angband.oook.cz/forum/showpost.php?p=143697&postcount=146
