### ISSUE TITLE
Labyrinth with no down staircase

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4243]
**Reported by NickMcConnell on 26 Dec 2019 21:59 UTC**
"I found myself in a maze on dLvl 13 without a staircase leading down. There was only one staircase, and it led up. I've never seen this before (outside of 99)."- fruviad

Screenshot: http://angband.oook.cz/screen-show.php?id=4665

**Comment by Eastwind921** [comment]
I looked at this out of curiosity.

labrynth has this:

`    /* Generate a single set of stairs down if necessary. */
    if (!cave_find(c, &grid, square_isdownstairs))
		alloc_stairs(c, FEAT_MORE, 1);
`

I didn't see any code in the actual wall generation that will generate any stairs, so the implication is alloc_stairs failed. The only way I could see that that might happen is if there are no empty squares, though I can't understand how that could be.

alloc_stairs isn't checking the true/false result from find_empty. Find_empty if it fails will set grid to something that's not empty. If that has enough adjacent walls the code will try to place a stair there, which might have been what happened.

`

			/* Try several times, then decrease "walls" */
			for (j = 0; !done && j <= 100; j++) {
				find_empty(c, &grid);

				if (square_num_walls_adjacent(c, grid) < walls) continue;

				place_stairs(c, grid, feat);
				done = true;
			}

			/* Require fewer walls */
			if (walls) walls--;
`

One possible thing to try is to put in a failure check for find_empty and have the code assert if that happens and see whether the assert ever gets hit.

**Comment by NickMcConnell** [comment]
Am going with an assert that the grid is now a stair after place_stairs().

**Comment by NickMcConnell** [comment]
Looks like this is back: http://angband.oook.cz/forum/showpost.php?p=157154&postcount=168

**Comment by backwardsEric** [comment]
In that recent report, there's one grid in the lower left that hasn't been seen.  #5287 modifies alloc_stairs() so it will place the requested number of stairs if there are empty grids available.  With #5287 applied, the 'D' debugging command didn't turn up a case of a missing downstairs in the 140000 labyrinth levels generated.

**Comment by backwardsEric** [comment]
With the current nightly and a hacked dungeon_profile.txt that sets the allocation for labyrinth levels to be 100 and the allocation for all other level types to be 0, generated 10 million labyrinth levels at a depth of 13 using the debugging command for disconnected statistics.  There were no levels that were reported as having the starting location disconnected from a down staircase.  The terrain counts supplied by the disconnected statistics had an average of one down staircase per level with no variation.

Based on that, I'd mark this as resolved.

**Comment by NickMcConnell** [comment]
Agreed.
