### ISSUE TITLE
Stealing from mimics

### ISSUE THREAD

**Issue by angband-import** [angband/angband#4244]
**Reported by NickMcConnell on 26 Dec 2019 22:00 UTC**
"Playing 4.2.0-29-g200c7be7b. By old habit I pressed 's' next to a chest (steal). That revealed to me that it was a chest mimick without waking it up. "failed to steal from the chest mimick"" - NightLizard

**Comment by NickMcConnell** [comment]
I'm going to say this is working as designed.
