### ISSUE TITLE
15 artifacts have AGGRAVATE flag - this should be a curse

### ISSUE THREAD

**Issue by Eastwind921** [angband/angband#4247]
Shouldn't there be some chance of removing AGGRAVATE from artifacts?

NB: this is for 4.2.0 - seems to me I should have to fill in some field somewhere with the version I'm reporting a bug against, but I don't see it....

**Comment by NickMcConnell** [comment]
As Pete Mack says (http://angband.oook.cz/forum/showpost.php?p=142474&postcount=295) no, this is working as designed.
