### ISSUE TITLE
Huan and Cantoras need ATTR_FLICKER

### ISSUE THREAD

**Issue by pete-mack** [angband/angband#4248]
Both are easily confused with harmless low-level monsters. (Dragluin is too, but he can't instakill.)

**Comment by pete-mack** [comment]
Whoops. Huan already appears to have it. But not cantoras.

**Comment by NickMcConnell** [comment]
Yes, good idea for Cantoras.

**Comment by NickMcConnell** [comment]
Fixed in 30fd1ba8c
