### ISSUE TITLE
OS X crash on font change/window resize in 4.2.0-44-g40f659b

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4250]
The correction for solid/hybrid walls in the OS X front-end causes access to uninitialized memory when updating the screen in response to a wipe.  One result is an assertion failure in get_background_color_index().

**Comment by backwardsEric** [comment]
This [pull request](https://github.com/angband/angband/pull/4251) has a fix for the uninitialized memory.

**Comment by NickMcConnell** [comment]
Fix applied in c60786748
