### ISSUE TITLE
struct element_info  should never exist in an array

### ISSUE THREAD

**Issue by pete-mack** [angband/angband#4260]
The contents of this structure are an array of resistance levels and a bitarray of flags. So you only need one element_info per object. But in the code, it is written as an array of size ELEM_MAX (both in struct object and struct player.)  Please fix this, so I can understand how to use it.

**Comment by pete-mack** [comment]
I started solving this enhancement:
https://github.com/angband/angband/issues/4035
but I am horribly stuck because of this problem.

**Comment by pete-mack** [comment]
Also: I am unable to add labels or milestones. The links are greyed out and inactive.

**Comment by pete-mack** [comment]
Whoops, misread how the structure works. I understand how elements work. But I am even more baffled by how the flag values work.

**Comment by NickMcConnell** [comment]
The important flags are EL_INFO_HATES and EL_INFO_IGNORES, which show when an item can or can't be destroyed by an element.

I'm not sure why you can't add labels or milestones, I'll look into it.  Closing this now.

**Comment by NickMcConnell** [comment]
OK, looks like it's only maintainer that can add labels and milestones.  I'll have to amend my instructions.

**Comment by pete-mack** [comment]
thanks Nick!
