### ISSUE TITLE
Items with random resist should ignore that element

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#4263]
Whenever `EL_INFO_RANDOM` is set `EL_INFO_IGNORE` should be set as well.

**Comment by pete-mack** [comment]
EL_INFO_RANDOM is actually just set and never used anywhere in the code

**Comment by pete-mack** [comment]
On further thought it should probably be used in lore--if the flag is set in a dummy ego don't show it in lore

**Comment by NickMcConnell** [comment]
Yes, I've noticed this too, and couldn't remember if it ever did anything.  I think the lore thing is covered by the fact that ego lore compares against the ego description, but I feel like the flag's not hurting anyone, so it can stay there.
