### ISSUE TITLE
[4.2.0] found some redundant flags in monster.txt

### ISSUE THREAD

**Issue by Eastwind921** [angband/angband#4265]
Output from a perl script I was working on that processes monster.txt and monster_base.txt.
Dunno if anyone cares, but it was easy to grab while I was debugging my script.

Beorn, the Shape-Changer: both monster and base are defining the SPIRIT flag
aether vortex: both monster and base are defining the IM_POIS flag
nightcrawler: both monster and base are defining the BASH_DOOR flag
Oss├½, Herald of Ulmo: both monster and base are defining the IM_FIRE flag
Oss├½, Herald of Ulmo: both monster and base are defining the IM_COLD flag
Oss├½, Herald of Ulmo: both monster and base are defining the SMART flag
Makar, the Warrior: both monster and base are defining the FORCE_SLEEP flag
Wiruin, the Maelstrom: both monster and base are defining the IM_POIS flag
Me├íss├½, the Bloody: both monster and base are defining the FORCE_SLEEP flag
Me├íss├½, the Bloody: both monster and base are defining the TAKE_ITEM flag
Vampire-Sauron: both monster and base are defining the FORCE_SLEEP flag
Vampire-Sauron: both monster and base are defining the EVIL flag
Vampire-Sauron: both monster and base are defining the NO_CONF flag

**Comment by Eastwind921** [comment]
Also, monster.txt: gelatinous cube has flags-off:HURT_COLD but monster_base.txt:jelly doesn't have flags:HURT_COLD.

**Comment by NickMcConnell** [comment]
Yeah, it's not super important but might as well be fixed.  What does your script do, btw?  You may be interested in Thraalbee's monster display page: https://thraalbee.azurewebsites.net/monview/

**Comment by Eastwind921** [comment]
Right now all it's doing is parsing these two files and building up data structures, doing some testing along the way. I'm writing something that will help choose between weapons to find which is the most effective for a given dungeon level given average monster generation for that level and their resistances.

**Comment by NickMcConnell** [comment]
Nice.
