### ISSUE TITLE
wrong variable used in town_gen_layout(), no discernible impact.

### ISSUE THREAD

**Issue by Eastwind921** [angband/angband#4281]
Town_gen_layout() contains the following code to place the stairs in the town. The last line references town_wid when it probably should be using town_hgt instead, because it's looking
for the y-limit. But it's dividing by 4 so it probably never matters. I'm not really sure why it's dividing by 4, I guess to make it fail if it gets too far from the north wall.

`
		/* Stairs along north wall */
		pgrid.x = rand_spread(z_info->town_wid / 2,
							  z_info->town_wid / 6);
		pgrid.y = 2;
		while (!square_isfloor(c, pgrid) && (pgrid.y < z_info->town_wid / 4)) pgrid.y++;
		if (pgrid.y >= z_info->town_wid / 4) continue;

`

**Comment by NickMcConnell** [comment]
I assume this is from after the changes to town generation?
