### ISSUE TITLE
performance: time/date calls unnecessarily inside loop

### ISSUE THREAD

**Issue by Eastwind921** [angband/angband#4283]
In mon-make.c, lines 230 & 231 could/should be moved outside and above the for loop. The time isn't going to change by enough between monster generations to be worth re-checking to see if you've ticked into our out of a seasonal monster's range, just check the time once and keep using it for all monsters on the level. The localtime call ain't cheap.

	/* Process probabilities */
	for (i = 0; i < alloc_race_size; i++) {
		time_t cur_time = time(NULL);
		struct tm *date = localtime(&cur_time);

**Comment by takkaria** [comment]
Sure, that makes sense.
