### ISSUE TITLE
melee_damage() uses any slay over any brand

### ISSUE THREAD

**Issue by Eastwind921** [angband/angband#4284]
player-attack.c:

`
static int melee_damage(struct object *obj, int b, int s)
{
	int dmg = damroll(obj->dd, obj->ds);

	if (s) {
		dmg *= slays[s].multiplier;
	} else if (b) {
		dmg *= brands[b].multiplier;
	}
`
This will cause any weapon that has, e.g. 
slay:EVIL_2
slay:ACID_3
to use the slay and do less damage than the brand.

Angrist is an example, vs anything that's EVIL, not IM_ACID, not TROLL and not ORC.
Angrist vs squint-eyed rogue should show this bug.

Function should collect both multipliers and use max().

**Comment by NickMcConnell** [comment]
This is not actually a problem, as melee_damage() is always called by py_attack_real() with a brand or a slay or neither, but never both.   The function improve_attack_modifier() goes through all the possible brands and slays a weapon could use and decides which to use, and that is what is passed to melee_damage().
