### ISSUE TITLE
With scaled up tiles, HTML screenshot has characters spaced by the tile scaling

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4289]
Using ')' to take an HTML screenshot while the game is displayed with tiles scaled up by h x v causes the characters in the screen shot to be separated by h-1 spaces horizontally and v-1 spaces vertically.  Happens with the SDL front end on Linux compiled from post 4.2.0 source as of February 16th, 2020.  Also happens with the Mac OS X front end compiled from the post 4.2.0 source as of February 16th, 2020 and the patches to enable tile set scaling.

Of course, there's an easy enough workaround:  switch to text display prior to dumping the screen.

**Comment by NickMcConnell** [comment]
Yes, this would be an improvement.

**Comment by NickMcConnell** [comment]
Fixed in a5729228e2625c823309be2ac5b5463a386aff12
