### ISSUE TITLE
HOF does not put winners first, just sorts on raw XP

### ISSUE THREAD

**Issue by pete-mack** [angband/angband#4290]
Up til now, the HOF didn't matter, but with angband.live, it is actually meaningful. Also, I can't see the whole HOF in knowledge menu. This is the time I really do want to know how other people are doing!

**Comment by NickMcConnell** [comment]
This may need to wait for 4.3 because of maintaining savefile compatibility; leaving as Triage for now.

**Comment by NickMcConnell** [comment]
Nope, looks like this is doable (although probably without re-ordering existing score files).
