### ISSUE TITLE
alchemist is oversubscribed; bring back temple or move basics to general store.

### ISSUE THREAD

**Issue by pete-mack** [angband/angband#4306]
There are so many items potentially for sale in the alchemist --and so many fixed items--that certain useful goods appear far less frequently than before. Move some of the fixed goods to the general store to allow more variety.

**Comment by NickMcConnell** [comment]
The number of fixed items makes no difference; the only relevant parameters are the minimum and maximum normal stock levels and the list of normal items (and the turnover, but that's barely significant).  For the Alchemist, the min is 6, the max is 10, so on average 8 of the 15 types of item possible will be stocked.  That doesn't feel way out to me - what would you suggest?

**Comment by NickMcConnell** [comment]
OK, I'm going to take that as eloquent silence 😉
