### ISSUE TITLE
Cry of the Damned not adjusting for radius

### ISSUE THREAD

**Issue by damedley** [angband/angband#4314]
I tested this quite a bit in 4.2 and I'm certain radius plays no part. I couldn't see anything wrong in the code but seems like it should be somewhere around here:

project-mon.c
static void project_monster_handler_TURN_LIVING(project_monster_handler_context_t *context) {
...
context->mon_timed[MON_TMD_FEAR] = adjust_radius(context, context->dam);
...
}

All the other context seems to work, but somehow context->r isn't set?

**Comment by NickMcConnell** [comment]
Not a bug, but a consequence of the type of projection used.  The spell definition in class.txt has PROJECT_LOS, which means direct application to all monsters in line of sight, so radius is irrelevant.
The projection code has quite a few subtleties in it, this is one...

**Comment by damedley** [comment]
OK. I was thinking that this spell should *obviously* decrease in effectiveness with range, but now I see that it is, at a minimum, not obvious.
