### ISSUE TITLE
player_attack_random_monster moves instead of attacking

### ISSUE THREAD

**Issue by damedley** [angband/angband#4320]
In player-util.c
I believe the idea is a raging blackguard will attack a nearby foe kinda like being confused, but it shouldn't move the player into an empty space. However, I have been moved into an empty place by this function a few times.

Maybe loc_sum(player->grid, ddgrid_ddd[dir % 8]) and move_player(dir % 8, false) don't refer to the same target square?

**Comment by damedley** [comment]
Oh, I just noticed: it will trigger from looking at menus and doing other no-game-time actions. Maybe this should be moved to the same place as confusion?

**Comment by NickMcConnell** [comment]
Nice find.  You are right about the direction, it should be ddd[dir % 8] going into move_player().

This function has never been in the right place (PowerWyrm has pointed this out before), and its implementation needs rethinking.  In fact, it may be that the whole command system needs to be expanded to allow this to happen.

**Comment by damedley** [comment]
Do you use the assign function? I'd be happy to take this one on while I'm tinkering with BG class.

**Comment by NickMcConnell** [comment]
I think I need to think about the command system a bit more.

**Comment by NickMcConnell** [comment]
Fixed in 669225de3
