### ISSUE TITLE
Mouse with main-gcu.c

### ISSUE THREAD

**Issue by nicm** [angband/angband#4329]
Hi

Here is a patch against master to add mouse support to main-gcu.c when using ncurses.

[angband-main-gcu-mouse.diff.txt](https://github.com/angband/angband/files/4373742/angband-main-gcu-mouse.diff.txt)

ncurses can support five rather than four mouse buttons but it must have been built with `--enable-ext-mouse` so in the interests of simplicity I have only used the four buttons supported by default.

Thanks

**Comment by NickMcConnell** [comment]
This patch doesn't seem complete; in particular, MOUSE_KEY and ALL_MOUSE EVENTS aren't defined.

**Comment by nicm** [comment]
They are defined by ncurses. I can take a look. What ncurses version do you have on what platform?

**Comment by NickMcConnell** [comment]
Oh, right, duh.  I'll add it in and we'll see how we go.

**Comment by nicm** [comment]
Great, thanks!
