### ISSUE TITLE
Spells Check For Fail Before Checking For Viability

### ISSUE THREAD

**Issue by damedley** [angband/angband#4330]
Can we check effect_valid first? I didn't look too deep into a solution.
	if (randint0(100) < chance) {
		event_signal(EVENT_INPUT_FLUSH);
		msg("You failed to concentrate hard enough!");
	} else {
		/* Cast the spell */
		if (!effect_do(spell->effect, source_player(), NULL, ident, true, dir,
					   beam, 0)) {
			mem_free(ident);
			return false;
		}
... other spell effects
	}

Related: 
https://github.com/angband/angband/issues/2661
(closed)

**Comment by NickMcConnell** [comment]
I don't think this is a problem; effect_valid() should only fail if it is calling an effect which hasn't been added to list-effects.h, so it's a coding error.  So the only advantage I can see is that the error may only be discovered after the spell has failed some number of times, which I would regard as just punishment for failing to add the effect to list-effects.h...
I'm going to close this, open it again if you think you have a better argument than mine 😃

**Comment by damedley** [comment]
The instances where this occurs are very specific. I should have documented it better, because I don't remember now, or maybe I was wrong from the beginning. If I can find it again I'll document it better.

**Comment by damedley** [comment]
OK, I do have one trivial example but I SWEAR there was at least one non-trivial example! Roll up a Paladin, discard all weapons and/or equipment, and then cast Enchant Weapon or Armor. It will check for spell fail before checking if you have something to cast it on.

There must be a Druid, Ranger, or Necromancer spell that can only target certain types of creatures, and this failure is less trivial. Or maybe casting Leap into Combat as a Blackguard with no enemies in sight.
