### ISSUE TITLE
Memory leaks in post 4.2.0 as of late March 2020

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4335]
These are call stacks for allocations which were later leaked as reported by Xcode's Leaks Instrument.  I've only included the ones that are from the Angband code and the parts of the call stack above the uppermost play_game() have been omitted.  Unless otherwise noted, the code was the post 4.2.0 code as of late March 2020.  With a handful of exceptions (menu allocation for ignoring items (see leak B2 below) and some object structures leaked while exploring the dungeon (see leaks D1 and D2 below)), these leaks are once per restart so would have minimal impact unless repeatedly using the restart without exiting option.

run A; from startup, player creation, play till character death, restart as new character (do not reuse the previous), exit with ctrl-x

leak A1;  2 allocations of 16 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
string_make
visuals_parse_cycle
parser_parse
parser_file
parser_file_quit_not_found
visuals_file_parser_run
run_parser
ui_visuals_module_init
init_angband
play_game

leak A2; 1 allocation of 48 bytes
malloc_zone_alloc
malloc
mem_alloc
mem_zalloc
player_spells_init
rd_player_spells
load_block
try_load
savefile_load
start_game
play_game
play_game

leak A3; 26 allocations of 320 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
object_new
write_curse_kinds
finish_parse_artifact
run_parser
init_arrays
init_angband
play_game

leak A4; 77 allocations of 64 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
finish_parse_player_prop
run_parser
init_arrays
init_angband
play_game

leak A5; 2 allocations of 16 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
string_make
visuals_parse_cycle
parser_parse
parse_file
parse_file_quit_not_found
visuals_file_parser_run
run_parser
ui_visuals_module_init
init_angband
play_game

leak A6; 41 allocations of 64 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
finish_parse_player_prop
run_parser
init_arrays
init_angband
play_game

leak A7;  27 allocations of 320 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
object_new
write_curse_kinds
finish_parse_artifact
init_parser
init_arrays
init_angband
play_game

leak A8; 1 allocation of 64 bytes
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
finish_parse_player_prop
run_parser
init_arrays
init_angband
play_game

leak A9; 1 allocation of 400 bytes
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
rd_player
load_block
try_load
savefile_load
start_game
play_game
play_game

leak A10; 1 allocation of 2 kilobytes
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
history_init
history_add_full
rd_history
load_block
try_load
safefile_load
start_game
play_game
play_game

leak A11; 12 allocations of varying sizes, 240 bytes in total
malloc_zone_malloc
malloc
mem_alloc
string_make
rd_player
load_block
try_load
safefile_load
start_game
play_game
play_game

leak A12; 1 allocation of 48 bytes
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
player_spells_init
rd_player_spells
load_block
try_load
savefile_load
start_game
play_game
play_game

leak A13; 1 allocation of 32 bytes
malloc_zone_malloc
malloc
mem_alloc
string_make
rd_player
load_block
try_load
savefile_load
start_game
play_game
play_game

run B; from startup, load a living character, and play until exiting with ctrl-x

leak B1; one allocation of 176 bytes
malloc_zone_malloc
malloc
mem_alloc
menu_new
sval_menu
handle_options_item
menu_handle_action
menu_select
do_cmd_options_item
menu_action_handle
menu_handle_action
menu_select
do_cmd_xxx_options
textui_process_command
textui_get_cmd
play_game

leak B2; 2 allocations of 16 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
string_make
visuals_parse_cycle
parser_parse
parse_file
parse_file_quit_not_found
visuals_file_parser_run
run_parser
ui_visuals_module_init
init_angband

run C; from startup, through character generation, playing until character death, restart as a new character (reusing the previous one), and playing until exiting with ctrl-x; do not show leaks that appear to be the same as in run A

leak C1; 15 allocations of 320 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
object_new
rd_item
rd_gear_aux
rd_gear
load_block
try_load
savefile_load
start_game
play_game
play_game

leak C2; 1 allocation of 240 bytes
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
rd_item
rd_gear_aux
rd_gear
load_block
try_load
savefile_load
start_game
play_game
play_game

leak C3; 15 allocations of 320 bytes apiece
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
object_new
rd_item
rd_gear_aux
load_block
try_load
savefile_load
start_game
play_game
play_game

leak C4; 1 allocation of 240 bytes
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
rd_item
rd_gear_aux
rd_gear
load_block
try_load
savefile_load
start_game
play_game
play_game

leak C5; 1 allocation of 96 bytes
malloc_zone_malloc
malloc
project
proejct_aimed
effect_handler_BOLT
effect_do
do_mon_spell
make_ranged_attack
monster_turn
process_monsters
run_game_loop
play_game

run d; from startup, generate new character, play until character died, restart as new character (not reusing the previous one), and exiting with ctrl-x; used modified code with changes to
plug the leaks seen above

leak D1; 1 allocation of 320 bytes
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
object_new
object_see
square_know_pile
square_note_spot
floor_carry
drop_near
monster_death
player_kill_monster
mon_take_hit
project_m_player_attack
project_m
project
project_aimed
effect_handler_BOLT
effect_handler_BOLT_OR_BEAM
effect_do
spell_cast
do_cmd_cast
process_command
cmdq_pop
process_player
run_game_loop
play_game

leak D2; one allocation of 320 bytes
malloc_zone_malloc
malloc
mem_alloc
mem_zalloc
object_new
object_see
square_know_pile
ssquare_note_spot
update_one
update_view
move_player
run_step
do_cmd_run
process_command
cmdq_pop
process_player
run_game_loop
play_game

**Comment by NickMcConnell** [comment]
All but D1 and D2 fixed in 67595731001a5c2881626516a7f9af1a3c435c6b

**Comment by NickMcConnell** [comment]
There is probably still the odd leak, but I'm struggling to find them now (and I can't see what's causing the D leaks, which seem to result from a call to object_new() in object_see()).  So I'm closing this.
