### ISSUE TITLE
No digging with mutliple same best diggers in your pack

### ISSUE THREAD

**Issue by AvdN** [angband/angband#4338]
Currently, if you have an average shovel in your pack and rely on digging, have auto-pick-up on and happen not to notice that you walked over a second average digger in a pile of loot, you inexplicable cannot dig quart vein anymore. This is not immediately obvious (and another 100 turns wasted), 

I think it would be better if this is changed to test > 0, and if necessary the code that auto swaps the digger in and out while actually digging can take care of keeping track of the number of diggers that needs to be 'restored' after digging.

https://github.com/angband/angband/blob/9d49b598e88ed2721c4bd3342ff3fcebf53c764d/src/player-util.c#L504

**Comment by NickMcConnell** [comment]
Fixed in 561b181
