### ISSUE TITLE
SET_TO/INC_BY to hitpoints

### ISSUE THREAD

**Issue by igroglaz** [angband/angband#4339]
It would be wonderful to be able to assign effects based at current character HPs, like it made for nourish, eg:

> effect:NOURISH:SET_TO
> effect:NOURISH:INC_BY

So certain effects from traps, potions, spells, etc - will be independent from dungeon depth. Eg. right now there are cool formulas:
```
dice:$Dd5
expr:D:DUNGEON_LEVEL:/ 10 + 1
```
...it's awesome, but its quite hard to customize to something like - leave 15% of HP after certain deadly trap (at _any_ dungeon depth). With SET_TO it could be:

> effect:HITPOINTS:SET_TO
> dice:15
> #make HPs 15%

The same thing could be added to mana and even some other parameters.

**Comment by igroglaz** [comment]
Another way to solve it - add expr:B:PLAYER_HITPOINTS; the same way as it's not for expr:B:PLAYER_LEVEL:

eg:

effect:DAMAGE
dice:$B
expr:B:PLAYER_HITPOINTS:- 5

**Comment by NickMcConnell** [comment]
The second solution actually already exists - PLAYER_HP.  It's used in shape.txt for vampire form.

**Comment by igroglaz** [comment]
Thanks! I've added it to FAQ https://tangaria.com/gamedesign/

**Comment by igroglaz** [comment]
hm.. I've got:

`name:Death
graphics:!:d
type:potion
level:0
weight:4
cost:0
alloc:1:2 to 40
pile:70:1d3
attack:3d6:0:0
armor:0:0
flags:EXPLODE
effect:DAMAGE
dice:$B
expr:B:PLAYER_HP:- 7
effect:DRAIN_MANA
dice:$Dd1
expr:D:DUNGEON_LEVEL:* 4
desc:The last enemy that shall be destroyed is death...
desc: Long time ago this potion was one of the most deadlies of all.
desc: But it seems time took most of it's harm, it's not so strong anymore...
msg_self:Once again you've cheated death!
msg_other: beats in spasms!`

but it doesn't work. HP doesn't change from this:
`effect:DAMAGE
dice:$B
expr:B:PLAYER_HP:- 7`
