### ISSUE TITLE
Known version of object in dungeon issues - analysis

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4348]
These are from my understanding of the current code and haven't all been verified with actual play:

1.  If @ fires or throws an object and it lands out of the line of sight, there's a known version of the object (since the player has touched it), but that's not added to the object list in the player's version of the cave.  Some side effects of that:
a) If @ leaves the level, there's a memory leak of the known version.
b) If @ senses objects at that point, the known version is lost (obj->known overwritten without checking in object_sense()).  Besides the memory leak, if the object was an artifact, it is now longer flagged as having been seen by @ and could be regenerated if @ leaves the level before seeing it again.

2.  @ drops an object.  It's destroyed out of the line of sight of @ leaving the original version of the object orphaned.  @ leaves the level without seeing the drop location again.  The known version of the object is still in a floor pile and is removed, but the original is not and is leaked.

3. @ drops an object and it's picked up by a monster out of the line of sight of @.  If the object is merged into another one in the monster's inventory, the post-4.2.0 change to object_absorb() (my fault) will remove the known version of object from the floor if it's still there.  That reveals information which @ isn't in a position to gather.

4. @ senses objects.  One is picked up out of the line of sight by a monster.  @ kills the monster without having seen the sensed location of the object.  On seeing the drop, the known version of the object at the sensed location is moved to the location of the drop revealing information @ wasn't in a position to gather.  If the object had been dropped by the player or detected with *Enlightenment* before being picked up by the monster, the current behavior seems okay.

5. @ senses objects.  One is picked up out of the line of sight by a monster.  The monster dies out of the line of sight due to something @ did and the object is dropped out of the line of sight.  @ senses objects again.  Because the object has a previous sensed location and is in the object list for @'s version of the cave.  The new position will not necessarily be marked as having an object while @ will still get the message that objects were detected.

6. @ senses objects.  One is picked up out of the line of sight by a monster.  @ attempts to steal from the monster and sees the picked up object but doesn't steal it.  Since the object has a known version in the object list for @'s version of the cave, object_see() moves the known version from where it was to the pile at (0,0). That reveals information that @ wasn't in position to gather.  Attaching it the pile at (0,0) could also be problematic since most places will only remove something from a floor pile if the location is not (0,0).

**Comment by NickMcConnell** [comment]
I missed this - have the pull requests that were referenced fixed all the issues, or is there still stuff that's problematic?

**Comment by backwardsEric** [comment]
The pull requests resolved those issues.  They introduce a regression of sorts:

1) @ drops something that wouldn't likely be mistaken for something else in the dungeon.
2) A monster picks up the object out of the line of sight.
3) @ kills the monster and sees the drop.  @ would reasonably know that the object is no longer where it was originally dropped, but with the changes it'll still be marked as there until @ sees the location again.

**Comment by NickMcConnell** [comment]
Yeah, I think that's fair enough - it's technically possible that the monster just happened to be carrying another indistinguishable object.

I'll close this issue, then.
