### ISSUE TITLE
Rune of Protection crash in angband.live

### ISSUE THREAD

**Issue by Sphara77** [angband/angband#4360]
17.4.2020
I did read an unidentified scroll in a late-midgame dungeon level and the game immediately crashed and threw me at angband.live opening room.
I reloaded and fortunately nothing had changed. Except that I was standing on a Glyph of Warding and still had that unidentified scroll in my inventory. Moving to a next square and reading it did the same thing. As I reloaded again, there were now two Glyphs and I still had the scroll. And so on.
I dropped the scroll and went on with my game.

**Comment by NickMcConnell** [comment]
Same reported [here](http://angband.oook.cz/forum/showpost.php?p=144809&postcount=266).

**Comment by NickMcConnell** [comment]
Can't repeat this now, I'm calling it fixed.
