### ISSUE TITLE
Race Flags Don't Clear on Birth Screen

### ISSUE THREAD

**Issue by damedley** [angband/angband#4362]
When you go up and down choosing races, the special abilities listed below Search don't clear unless they are overwritten. E.g., press down to get to Half-Elf, then up to get to Human, and the half-elf abilities remain on screen. When you press the letter, e.g. a for human, sometimes it clears and sometimes it doesn't, for reasons that escape me.

**Comment by NickMcConnell** [comment]
Can't repeat - it always clears fine for me.

**Comment by damedley** [comment]
![Humans-resist-poison-and-light](https://user-images.githubusercontent.com/5931886/80895352-f07c4f00-8cb1-11ea-9483-e4fc97d1f4e0.png)

**Comment by damedley** [comment]
Maybe this one needs to be handed over to Gwarl. I can't recreate it in my PC version.
