### ISSUE TITLE
property which forbids to move diagonally

### ISSUE THREAD

**Issue by igroglaz** [angband/angband#4364]
inspired by http://angband.oook.cz/forum/showthread.php?t=9990

1) there could be monsters which can not move diagonally (which is interesting property if added with eating walls).
2) an item property which forbids player to move diagonally. Could be a curse or just a property for a VERY heavy armour... as it could be hellish hard to move in heavy armour with a precise angle :)

**Comment by NickMcConnell** [comment]
I think this sounds like a great plan for you to implement for your variant :grin:
