### ISSUE TITLE
Mining and No-Sell

### ISSUE THREAD

**Issue by damedley** [angband/angband#4365]
Not critical, obviously, but the no-sell option should not affect how much gold is found in walls. You never find items to sell in town inside walls, so gold veins do not need to be multiplied to compensate.

**Comment by NickMcConnell** [comment]
Actually, I think gold veins are no worse than anything else.  Increasing gold finds is a fairly crude way of compensating for inability to sell items - I don't see much difference in whether those are from the walls, on the floor or dropped by monsters.  For example, hydras drop only gold.
