### ISSUE TITLE
DEC_BY effect

### ISSUE THREAD

**Issue by igroglaz** [angband/angband#4366]
I'm gorged pretty often, so wanna add a potion to cure stomach in my variant (cause salt water is too hardcore), eg

```
name:Stomach Water
graphics:!:d
type:potion
level:3
weight:4
cost:1
effect:NOURISH:INC_BY
dice:-15
msg_self:The potion calms your stomach.
msg_other: hiccups.
```

But negative value doesn't work.. maybe it's possible to make it work or add something like DEC_BY ?

**Comment by NickMcConnell** [comment]
Looks like this is solved.

**Comment by igroglaz** [comment]
Still DEC_BY suffix could be fun to have one day :D Certain food could be bad for your stomach, but not fatal as salt water or purging

**Comment by igroglaz** [comment]
DEC_BY for the living!
