### ISSUE TITLE
Shift-U

### ISSUE THREAD

**Issue by damedley** [angband/angband#4372]
Not sure if the Shift-U command is supposed to let you activate wearable items that you aren't wearing. If so then Shift-A should let you also. When I Shift-U-sed a stack of rings of open wounds they all became "charging" but a stack of rods of treasure detection used only 1.

**Comment by damedley** [comment]
Probably Shift-U should be on the menu when you inspect an item as well.

**Comment by NickMcConnell** [comment]
No, activation shouldn't work.  Not sure about the context menu - having two entries that do the same thing might be confusing, but it would show the command existed.

**Comment by damedley** [comment]
Agreed.

**Comment by damedley** [comment]
I would say, in a perfect world where I don't have to do any of the programming work, it'd be great to list U underneath the specific command (which seems to always be beneath Inspect). So
I) Inspect
E) Eat
U) Eat
v) Throw
... etc

One man's opinion.

**Comment by NickMcConnell** [comment]
OK, having looked at the context menus, I'm not going to make any changes.  The 'U'se command is used when the player right-clicks on the character to enable use of an object, and I don't want to muddy the waters by having it appear in a different context.

**Comment by NickMcConnell** [comment]
Fixed in c3aa12548

**Comment by damedley** [comment]
It's in help->commands and Menu->Items list as well, at the bottom. So that's pretty good. My idea to add it below the specific command is not good, in retrospect.
