### ISSUE TITLE
Losing Monster Info?

### ISSUE THREAD

**Issue by damedley** [angband/angband#4374]
It looks like I'm losing monster info when I exit and come back. It seems to only happen with monsters with special characters in their names like Mim, Smeagol, etc.

**Comment by NickMcConnell** [comment]
What, so they're not int your monster memory any more?

**Comment by damedley** [comment]
They are, but details I've learned about them disappear.

**Comment by damedley** [comment]
IDK if there was a change, but I am remembering Smeagol now. Maybe I always was. Now sure if I'm remembering guys with a ^ over i - my monster memory definitely is missing info I should have on them, but I haven't encountered one lately.

**Comment by damedley** [comment]
Encountered Ibun, son of Mi^m. I remembered his details after exiting and coming back.
