### ISSUE TITLE
Farmer Maggot drops Sling of Buckland at town level? (Angband.Live - Nightly)

### ISSUE THREAD

**Issue by HolyRage** [angband/angband#4384]
Recalling to town from DL 18, I killed Farmer Maggot with my Blackguard and he dropped a Sling of Buckland (x4) (+11,+4) <+3, +6, +2>. Is that a bug or was I simply extremely extremely lucky?

Thank you for your continued work!

**Comment by NickMcConnell** [comment]
That is not a bug, that's cause for boasting 😄
