### ISSUE TITLE
Dump Should Default to Y

### ISSUE THREAD

**Issue by damedley** [angband/angband#4386]
This sounds small, but I've been doing an HTML dump on Angband.live when I detect monsters and the fact that the dump overwrite confirmation defaults to Y is actually pretty annoying. There's already one challenge (H/F) that has no default, and a bunch of stuff to spacebar through. Pretty sure we won't have too many people accidentally overwriting a crucial dump.

**Comment by NickMcConnell** [comment]
I assume you mean defaults to N, and the annoyance is you have to hit 'y' rather than enter?

**Comment by damedley** [comment]
Yep, that's what I meant.

**Comment by NickMcConnell** [comment]
Having looked into this, I don't think it's a good idea - it would require either a new checking function which copies a lot of the functionality of the old one, or confuses the logic of the old one.  You'll just have to get used to that keystroke, I'm afraid.
