### ISSUE TITLE
The Teleport Curse is Silent

### ISSUE THREAD

**Issue by damedley** [angband/angband#4387]
Probably should be a message whenever teleport curse activates. Right now it only gives a message when you learn the rune.

**Comment by NickMcConnell** [comment]
Yeah, I'll buy that.

**Comment by Cuboideb** [comment]
The anti-teleport curse is also silent.

**Comment by NickMcConnell** [comment]
Until you try to teleport...

**Comment by damedley** [comment]
From my most recent experience with tele curse, it doesn't interrupt digging (and maybe other stuff).
You dig in the rubbble. <2x>
You have learned the rune of teleportation curse.
You tunnel into the granite wall <3x>

I didn't order that granite wall dig.

**Comment by NickMcConnell** [comment]
OK, fixed in development - curses now disturb on activation (always should have, really).
