### ISSUE TITLE
Can't Donate With Selling On

### ISSUE THREAD

**Issue by damedley** [angband/angband#4395]
Donating for ID is often not available with no_sell off. Some things you can donate like scrolls and potions. But some things you can't like rings. I suspect when it's calculating values of potentially salable items it ignores items with a calculated cost <=0, but when it just goes off the "cost" coded into object.txt then it will let you donate.

**Comment by NickMcConnell** [comment]
I think this is a feature, not a bug 😉 
More precisely, donation for ID is something you get access to by playing no-selling; if you're asking shopkeepers for money, they're not going to accept your junk for nothing and do you the service of IDing it.

**Comment by damedley** [comment]
That's fair. That's how I looked at it already anyway. One oddity, though: you can have something that's not junk and they won't take it. I don't understand how it determines prices for stuff that you haven't fully ID'ed, but I often have stuff that I know they would pay for if only I knew what it was.
