### ISSUE TITLE
Why Are Up Stairs Generated on Forced Descent?

### ISSUE THREAD

**Issue by damedley** [angband/angband#4397]
Someone must have done this on purpose at some time because there's a message "Nothing happens!" when you try to go up. But I can't see any reason to generate them. And you don't get a connected up-stair when you come down a staircase. Harmless, but a bit odd.

**Comment by NickMcConnell** [comment]
I think it was more a decision not to go through and insert an (if option) statement every time an up staircase was to be generated.  There is also the issue that before 4.2 mages had a Create Stairs
 spell which would have had to be taken into account.
I guess this could probably be changed by aborting alloc_stairs() where necessary - there may be an argument that having the up stairs but being unable to use them is more immersive, too.

**Comment by damedley** [comment]
Another way to go, and easier to program, would be to generate the return stair when you go down, but that return stair also does nothing. Maybe make the message a bit more flavorful. "The way is shut" or "You may not return that way!"

**Comment by NickMcConnell** [comment]
I'm going to leave this as is - forced descent is a non-mainstream choice, and I think the current behaviour is OK.
