### ISSUE TITLE
bell() sound generation and message display

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4400]
When writing up the unit tests for message.c, it looked like bell() doesn't perform as advertised:

- There's no immediate generation of an audible warning, either through TERM_XTRA_NOISE or sound().  Unless it's intended that a downstream handler for MSG_BELL generate the sound.
- The message text is added to the message log but the current handler for MSG_BELL, bell_message() in ui-input.c passes it to display_message() in the same file which does not display it.

**Comment by NickMcConnell** [comment]
Hm, I have literally never thought about this.  I do recall that the bell did work, but not how long it is since I last experienced it (which I wouldn't now because I have headphones permanently plugged in, and don't wear them when playing Angband).

**Comment by backwardsEric** [comment]
On a Mac with the nightly code, using an invalid command during targeting or looking didn't trigger a sound (sounds were on).  In the changes to message.c, bell() appeared in its current form in January 2015.

**Comment by NickMcConnell** [comment]
Setting this to 4.2 for now, we'll see how we go.

**Comment by NickMcConnell** [comment]
Call me lazy if you like, but I'm thinking something that's been broken for a few years with no-one noticing is not a high priority to fix, and certainly shouldn't be blocking a release.
Kicking to future.

**Comment by backwardsEric** [comment]
That sounds reasonable to me.

**Comment by takkaria** [comment]
Historically (say, in the 3.0 era) the bell did work but the message has never been displayed - it's only ever been in the message logs.  I always thought this was weird.  Maybe a good argument for restoring the noise and nuking the message?  (The messages are super uninformative anyway...)
