### ISSUE TITLE
Skill No Effect on Crits?

### ISSUE THREAD

**Issue by damedley** [angband/angband#4413]
I was surprised to see that melee skill (from racial, class, and my pet berserk strength mod) has no effect on critical chance or quality:

int power = weight + randint1(650);
int chance = weight + (p->state.to_h + plus + debuff_to_hit) * 5
		+ p->lev * 3;

How to introduce that term, if it is even wanted, is pretty tricky. The nine classes have an average melee skill of about 50 at L1 and 200 at L50 (just from class contributions). And of course skill +3 is about equal to +1 to hit.

Also a bit weird that only weight can change the average power or degree of crit.

Not really sure if posting this in "Issues" is even the right place to start.

**Comment by NickMcConnell** [comment]
Hm.  It does for O-combat 😃

**Comment by NickMcConnell** [comment]
I think I'm going to say this is just how V combat works - I don't feel strongly enough about it either way to change it.  If there's wider discussion of it, maybe.

**Comment by damedley** [comment]
Yeah. Lots of surprising stuff in here, really. Like: monsters have no ability to defend against crits, other than avoiding being hit in the first place, and avoiding status effects. But no adjustment for things like AC or native depth.

I have a more firm recommendation: replace p->lev*3 with melee_skill - 60. This keeps crits damn near the same rate on average across classes and races, somewhat preserves the to-hit to skill ratio (1 to 5 instead of 1 to 3), and rewards the melee skill granted by classes, races, and whatever else.

**Comment by NickMcConnell** [comment]
All right, actually did this in fb7284e52
