### ISSUE TITLE
Broken savefile after entering a dungeon. Problem with piles?

### ISSUE THREAD

**Issue by Cuboideb** [angband/angband#4421]
Hi, 

I got a broken savefile when entering a dungeon. Load the savefile, take a step and an assertion fails at cave.c, line 505. I think its something related to piles. A user of the android port reported something similar.

The savefile can be fixed? I would appreciate it very much!

[NecroBroken.zip](https://github.com/angband/angband/files/4674759/NecroBroken.zip)

**Comment by NickMcConnell** [comment]
OK, it turns out you are playtesting one of the new level types and have found a bug.  The savefile should be fixed, it's just a matter of fixing the bug now...
[NecroUnbroken.zip](https://github.com/angband/angband/files/4674858/NecroUnbroken.zip)

**Comment by Cuboideb** [comment]
Thanks!

**Comment by NickMcConnell** [comment]
Fixed in c2770f51f
