### ISSUE TITLE
Detected But Unseen Monsters Defy Time Stop?

### ISSUE THREAD

**Issue by damedley** [angband/angband#4423]
With a 1-turn detect spell cast (Seek Battle), I ignored an item. The detected monsters moved! I ignored a second time and they moved again. I didn't check if my turn count changed, but my detect stayed active and the monsters moved when no time should have passed. I'm almost certain that monsters I'm looking at directly don't move when I ignore something.

**Comment by NickMcConnell** [comment]
OK, reproduced, and probably not a bug.  The thing is, when you ignore something in your inventory, you then automatically drop it, which takes some energy (1/2 a usual turn's worth).  If you ignore a floor object, that will take no energy and monsters will not move.

Technically maybe the monsters should not stay detected, but maybe they should too and it would take a lot of delicate work with the game loop...

So I'm leaving it as is 😃
