### ISSUE TITLE
Lightning strike can't be shot at tile where the digital line gets fine, but which is not in FOV

### ISSUE THREAD

**Issue by Mikolaj** [angband/angband#4425]
When I cast the spell as a druid, it does nothing. Tiles not seen due to being dark are no problem, only tiles not see due to no FOV are a problem. However, the digital line marked by stars reaches that tile without any issue. I can attach savefile if it helps, but it's pretty consistent.

**Comment by NickMcConnell** [comment]
This is a deliberate limitation of the STRIKE effect.  Because this effect doesn't project from the player, some limitation is needed, or you could hit things in the next room; field of view seems like the obvious one.  Note that you don't use a turn and mana when you attempt to hit a grid out of FOV.
I'll add some words to the spell description.

**Comment by Mikolaj** [comment]
Thank you for responding so quickly, but description is not enough, IMHO. I should see that the spell won't work already when I start targeting for the spell. I am getting feedback that everything is fine, none of the stars on the line is blue or grey and then nothing happens. When I detect monsters or I have ESP, I can't even see that the monster I target at is not in FOV, so there is absolutely no feedback that would help me, not just conflicting feedback (targeting line OK, out of FOV bad). At worst I should get a message that the spell failed for this and that reason. 

But ideally the line that appears when targeting should agree with FOV. I know this is not easy. I know how to do it for Digital and probably permissive FOV, but not any other. Or perhaps base the STRIKE restriction on the line not on FOV and then you can keep having them out of sync, which is the Angband tradition. Perhaps that's the best solution for Angband: let all spell restrictions be based on the targeting line only?

**Comment by NickMcConnell** [comment]
OK, agreed.  I'll play with using the targeting line, and if that fails print a failure message.

**Comment by Mikolaj** [comment]
You are the best maintainer ever. :)

**Comment by NickMcConnell** [comment]
Aiming to release in the next week or so, so I'm fairly focused 😁

**Comment by NickMcConnell** [comment]
OK, target grid now has to be projectable (which *should* correspond to the line) and also known (so the grey grids on the line will not work, even if they are projectable).  And I've added a bit to the spell description.

**Comment by Mikolaj** [comment]
That's a bit harsh, because when I see a monster via infravision 1 tile further than my light source reaches, I won't be able to hit the monster. But fair enough, visible and projectable are clear and understandable restrictions the player can learn and understand. However, I still have no visual feedback, because when targeting, the infravision-visible monster grid is always bright red, whether the tile itself is known or not.

**Comment by Mikolaj** [comment]
It works, in general, but uh, oh, the new spell happily hops over an unknown area. The target space is known, but it's marked by a grey star, because the line goes over unknown tiles. So visual feedback is negative, but I can still cast the spell. I guess the visual line is using client-side projecting (what the player sees), but the condition uses server-side projecting (what the game arbiter knows).

**Comment by NickMcConnell** [comment]
Yes, I think that's correct.  I'm starting to think there is fundamentally no correct answer to this one.

**Comment by Mikolaj** [comment]
I don't believe you. It may not be worth the effort, at least at a short notice, but e.g., if the star is grey on the screen, there must be a way to specify that as a condition for a spell. Perhaps the game would need to seriously start keeping track of what the player knows, e.g., as a second copy of the game state, smaller than the full one. Or perhaps there is a much simpler way, given that the appearance of the targeting line seems correct, whatever heuristics it uses to achieve that.

Then again, it's somewhat unnatural that I deduce the target location is free and I guess there is no glass wall on the line from me to the target but I'm not allowed to attempt that spell and bear the consequences if the glass wall is, in fact, there (or if I have FOV, but no target line due to them not being in sync). As with a stinking cloud that goes off at the glass wall or a FOV bend. For the Lightning strike it could go off at the player location instead, but that gives even less feedback on why the failure ocurred.

The only visual feedback that I can come up that feels natural to me is to permit the spell if anything is visible at the target location: previously seen or magic-mapped tile (not sure what to do if it changed to wall, but the player is not aware) or a monster visible via infravision, ESP or detection; perhaps even a detected trap or door (but not item, since it's only vaguely determined and shows a red star). The visible/detected think is the mental anchor, the coordinate at which the spell fires. If that makes the spell too powerful, perhaps restrict range.

**Comment by NickMcConnell** [comment]
OK, I'll put it another way - I'm unwilling to put in the time to find a correct answer.  This is partly because I'm unconvinced that there is one - or at least one that doesn't involve a rethink of field of view and projectability and the relationship between them.  And I am very reluctant to start such a rethink because of its potential for side-effects on other parts of the game.
Lightning Strike is a single spell.  If it doesn't behave intuitively, that's largely because it is not a projection from the player like everything else, so it doesn't behave the same.  So my solution is it behaves as it does, and the player becomes accustomed to that behaviour 😃

**Comment by Mikolaj** [comment]
Fair enough, you are the maintainer and I'm just providing feedback. Thank you again!
