### ISSUE TITLE
e and i reduced function with shapechange

### ISSUE THREAD

**Issue by damedley** [angband/angband#4430]
Latest nightly: when shapechanged, doesn't allow you access to equipment via "e" command or inventory via "i" (gives list but no more). Can look at equipment through "I" command, though. This prevents some hackery and isn't too bad if you know the commands, but seems like e and i could give you the I readout without too much programming effort. 4.2.2?

**Comment by damedley** [comment]
This may just be me, but I'm very accustomed to pressing ea to look up my melee damage.

**Comment by NickMcConnell** [comment]
Yes, that's a point

**Comment by NickMcConnell** [comment]
I'll leave this open, but I'm not sure if it's worth it - and the current situation acts as a small reminder that things are different when you're shapechanged.
Amusingly, ea does bring the weapon description up in the object recall subwindow if you have that open.

**Comment by NickMcConnell** [comment]
I think this is below the noise floor
