### ISSUE TITLE
Support to CMake (Linux x86 X11)

### ISSUE THREAD

**Issue by Andres6936** [angband/angband#4436]
I have succeeded to compile Angband with CMake on Linux with X11, however the support is not complete. After a while of starting the program I receive the following error:

> /home/andres6936/CLionProjects/Angband/cmake-build-debug/Angband: software bug

Obviously the error is not very specific and I'm not related to the code.

**Comment by NickMcConnell** [comment]
This means handle_signal_abort() has been called.  There are a number of signals that could do this -- see ui-signals.c for details.

**Comment by Andres6936** [comment]
Yes, according to CLion there are 11 places where the function is called:

![Screenshot from 2020-06-05 22-00-23](https://user-images.githubusercontent.com/18540634/83934656-26f92e00-a778-11ea-89c6-409ac678ec0e.png)

But, I have a little more information now: It happens every time the character dies.

**Comment by Andres6936** [comment]
What files are required for Angband to compile on Windows?

**Comment by Andres6936** [comment]
I have managed to compile Angband on Linux with NCurses, SDL and X11 support

**Comment by Andres6936** [comment]
Support to X11 - Work!

![image](https://user-images.githubusercontent.com/18540634/83976831-2371be00-a8c2-11ea-9a6d-21e041a69547.png)

Support to SDL - Work!

![image](https://user-images.githubusercontent.com/18540634/83977488-72b9ed80-a8c6-11ea-9515-059e327cfd45.png)

Support to NCurses - Not fine, but work!

![image](https://user-images.githubusercontent.com/18540634/83977544-dfcd8300-a8c6-11ea-8335-b05152edb391.png)

**Comment by NickMcConnell** [comment]
Done in 5efff72a36a11021b8d5bf29ebd3d3a638cc51b4
