### ISSUE TITLE
Calris not (LOST) when destroyed by removing curse

### ISSUE THREAD

**Issue by AvdN** [angband/angband#4442]
I tried to remove the curse on Calris in 4.2.0, which first turned it fragile and then was destroyed/removed from my inventory.
I had never experienced an artifact to disappear like that, and I have succesfully uncursed Calris and maybe the code for that has changed. But strangely enough Calris was not marked (LOST) in the character history.
I tried going down a level, if something like that would trigger it to be (LOST) forever, but it didn't.

(Not really high priority, but I thought I mention it anyway).

**Comment by NickMcConnell** [comment]
Yes, artifacts can now be destroyed this way.  It's generally a good idea to check the power of the curse against the power of your removal method (scroll or spell); the strength needs to exceed the power for the uncursing to work.  A failed uncursing will make the object fragile, and subsequent failures have a chance to destroy it.
I'l think about the LOST question.
