### ISSUE TITLE
Rogue-like key problems

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#4452]
"With rogue like keys, some of the 'alter/tunnel' commands are over-ridden by other things: ^H brings up the "use ? for help" message instead of tunnelling to the left, and ^J brings up the onscreen menu (I would have thought SDL has a different key code for RET to ^J?)."  - drquicksilver

**Comment by backwardsEric** [comment]
From drquicksilver's follow-up post, http://angband.oook.cz/forum/showpost.php?p=146792&postcount=6 , that was with the Mac front-end and should be fixed by https://github.com/angband/angband/commit/719d8b22cd771bdf18daade5654a1f1a85693fc1#diff-62ab822859fb914ed59fffe2f5c3ccce .

**Comment by NickMcConnell** [comment]
Aha thanks, I vaguely remember that now.   I'll close this.
