### ISSUE TITLE
Teleport other on creeping coins can lead to weirdness

### ISSUE THREAD

**Issue by fizzix** [angband/angband#4455]
If you "teleport other" a creeping coins that you have not discovered are coins yet, you'll get the message that the coins have disappeared, the monster will be gone, but coins will still be there and you can go pick up the money.  I didn't track down the monster to see if its drop vanished.

**Comment by backwardsEric** [comment]
https://github.com/angband/angband/commit/5bcb26b59d7231ed4ab78912e6ecc0108a19888d should resolve this by adding unrevealed mimic handling in monster_swap().

https://github.com/angband/angband/pull/4509 covers the other place that comes to mind for situations where object or monsters are moved but there wasn't handling of unrevealed mimics.

**Comment by NickMcConnell** [comment]
OK, excellent, I'll pull that in later.  There have been persistent but rare crashes involving mimics - this is a possible explanation.

**Comment by NickMcConnell** [comment]
Should be done now
