### ISSUE TITLE
Compiling with --enable-sdl2-mixer does not enable sdl2-mixer for sound (Linux)

### ISSUE THREAD

**Issue by hewholikethlisp** [angband/angband#4458]
Configuring the installer with --enable-sdl2-mixer does not allow the installed game to use SDL2 for audio.

Following the [compilation guide](https://angband.readthedocs.io/en/latest/hacking/compiling.html.):

```
./autogen.sh
./configure --enable-sdl2 --enable-sdl2-mixer --prefix /some/path
make
make install
```

From the output of `./configure ...`:

```
checking for sdl2-config... /usr/bin/sdl2-config
checking for SDL2 - version >= 2.0.0... yes
checking for IMG_LoadPNG_RW in -lSDL2_image... yes
checking for TTF_Init in -lSDL2_ttf... yes
checking for Mix_OpenAudio in -lSDL2_mixer... yes
```

which indicates that SDL2 support should be OK.

When running `angband --help` no sound modules are listed under the `-s<mod> ...` row.
When running the game with `angband -msdl2` there is no sound at all.

If we repeat the same process with `./configure --enable-sdl2 --enable-sdl2-mixer --enable-sdl-mixer --prefix /some/path` or remove the `--enable-sdl2-mixer` flag and only include the `--enable-sdl2-mixer` flag audio works, but only using the SDL1 version. If the game is launched with `angband -msdl2` after such a compilation there is sound.

**Comment by steils** [comment]
Is it closed in https://github.com/angband/angband/commit/bbfe78654e2f67da264d81d25fe1e6332302e51a?

**Comment by NickMcConnell** [comment]
Yes I think so, nice catch
