### ISSUE TITLE
Secret door detection on level change

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4469]
In the 4.2.1 nightly, @ went down a set of stairs and ended up at the end of what appeared to be the end of a corridor.  Only upon moving away from the stair and then coming back to it (from the code holding would have also sufficed) did @ notice the secret door immediately adjacent to the stairs in the wall opposite from the direction of the corridor.  Shouldn't @ have noticed the secret door upon first descending the stairs?

**Comment by NickMcConnell** [comment]
Yes, this is a thing I've noticed for a while, but never done anything about.

**Comment by NickMcConnell** [comment]
Fixed in 0b0798133f98653c6b30ea7cdaf1dde40bcffac3
