### ISSUE TITLE
Access shops in "display current knowledge" by their number

### ISSUE THREAD

**Issue by AvdN** [angband/angband#4519]
With 4.2.1 You can display the content of the black market using ~ followed by n (rogue mode). With the nightly built on angband.live this has changed to ~ + o because another entry was added before the shops. It would nice if the  "display current knowledge" for shops could be activated by the shop number and muscle memory, for this, only once (or less often) re-trained.

**Comment by NickMcConnell** [comment]
I'll look into this.
