### ISSUE TITLE
Wrong keyboard input with non-US keyboard layout in SDL2 version for GNU/Linux in Xorg (v4.2.1)

### ISSUE THREAD

**Issue by hewholikethlisp** [angband/angband#4522]
The keyboard input in the SDL2 version is wrong when using a non-US keyboard layout. In my case, using a Scandinavian layout, inputs such as `*` and `?` do not work on the keys they are mapped to.

Some examples:

- During character creation you can press `*` to generate a random name. With the Scandinavian layout the input for the `*` key (`Shift` + the button next to Enter) does not work. Pressing `Shift` + `8` (the combination for `*` on US keyboards and the combination for `(` in the Scandinavian layout) generates both the character `(` and a random name.
- With the Scandinavian layout `?` is bound to Shift + `+` (where `+` is to the right of `0`). Pressing this combination does not open the help menu. However, pressing `Shift` + `-` (which is in the same position as `/` would be on a US keyboard) does not open the help menu either.

Keyboard layouts for reference:

- [US keyboard layout](https://upload.wikimedia.org/wikipedia/commons/1/17/LinuxUSKeyboard.png)
- [Scandinavian keyboard layout](https://forums.crackberry.com/attachments/blackberry-keyone-f445/419377d1489488747t-keyone-swedish-keyboard-layout-2000px-kb_sweden.svg.jpg)

**Comment by NickMcConnell** [comment]
This will be got to at some stage, but I can't promise when.  If the necessary changes had been made and I just had to pull them in, of course...
