### ISSUE TITLE
Angband cannot be opened because the developer cannot be verified - Mac

### ISSUE THREAD

**Issue by Longoval** [angband/angband#4525]
Error message states "macOS cannot verify that this app is free from malware". Issue is new since upgrading from 4.1.3 to 4.2.1

**Comment by NickMcConnell** [comment]
If you Control-click, or possibly click a second time, you should get an option to open.  This is a consequence of Apple tightening their requirements for apps.

**Comment by NickMcConnell** [comment]
I believe this is resolvable by the player - let me know here if not, otherwise I'll close this in a few days.

**Comment by Longoval** [comment]
Yes, thank you - I resolved it. Very kind of you to help :)

**Comment by NickMcConnell** [comment]
Cool 😃
