### ISSUE TITLE
Cannot enchant worn items if carrying same type of item in backpack

### ISSUE THREAD

**Issue by hyvokar** [angband/angband#4536]
Hi, 

noticed that I cannot magically enchant worn weapons or armor with scrolls if I'm carrying same type of item (weapon, armor) in my backpack. Reading the scroll allow you only to enchant item in backpack. If you drop the item from backpack, you can enchant items worn. 

angband 4.2.1. on windows

**Comment by NickMcConnell** [comment]
This seems to work fine for me.  Can you explain exactly what's happening?

**Comment by hyvokar** [comment]
Ah never mind. It's working, I just missed the  "/ for equip" part when reading a enchant scroll

**Comment by NickMcConnell** [comment]
Cool
