### ISSUE TITLE
Two tunnel directions (h and j) broken when using rogue_like_commands on 4.2.1

### ISSUE THREAD

**Issue by pscheyen** [angband/angband#4538]
New in version 4.2.1 with rogue_like_commands set to yes, ^h and ^j fail to tunnel in the expected directions.  ^h appears to be undefined.  ^j brings up a help menu.

**Comment by BPaden** [comment]
I have similar but slightly different symptoms with rogue_like_commands and -mgcu. ^j works as expected for me, but ^h just gives me the message `Type '?' for help.`

**Comment by NickMcConnell** [comment]
I haven't been able to reproduce this - ^h and ^j work as expected both with -msdl and -mgcu.  I wonder of this is something terminal-specific.

**Comment by BPaden** [comment]
Hmm, well I am using gnome-terminal. both ^h and ^j work for me with -msdl and -mx11.

**Comment by RMPeteScheyen** [comment]
This appears to be MacOS specific.  I cannot reproduce the same error on Windows.  I'm using MacOS 10.15.7 (Catalina)

**Comment by dealpete-work** [comment]
It does seem to be terminal specific. I'm on mac OS, and it works fine with my normal terminal (Kitty), but behaves like BPaden described above on the built in Terminal app (i.e. ^j works but not ^h).

**Comment by NickMcConnell** [comment]
OK, I'm going to say this is an issue with macOS terminal, not Angband.
