### ISSUE TITLE
Instance of failure to place player

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4549]
Happened with custom-compiled code which matches the current 4.2.1 nightly for cave generation at level 16 with the Moria profile and a 138 x 46 chunk.  The part of the chunk that is both empty and not a vault fits in a 52 x 25 box.  The attached file, [player-placement-failure-example.txt](https://github.com/angband/angband/files/5287806/player-placement-failure-example.txt), renders that with ' ' for the parts that are empty and not a vault and '#' for the rest:  it is one big irregular room.

The failure occurred in the process of running the disconnection statistics debugging command.  As for an estimate of the probability of this happening, I had simulated about a quarter to half a million levels at shallow depths (1 - 16) before running into this failure.

**Comment by NickMcConnell** [comment]
This is not ideal, but rare enough not to be a real priority; I'm going to mark it as ongoing so we don't forget completely.

**Comment by backwardsEric** [comment]
Encountered another instance of it with the current 4.2.2 nightly with some modifications to the gauntlet generation to try to resolve the disconnection issue.  It was at level 37 with the Moria profile and a 190 x 60 chunk.  Attached is the map (after compression by gzip) generated by dump_level_simple() in new_player_spot():

[dumpedlevel.html.gz](https://github.com/angband/angband/files/6328374/dumpedlevel.html.gz)

According to it, there was one room - The Plains of Air vault.

**Comment by backwardsEric** [comment]
#4730 should have addressed the two instances reported (Moria levels with single rooms).  #4978 makes the error unlikely to be fatal for the player's game, at least in Vanilla, since generation will be restarted and that would have to fail multiple times before the game bails out.  As such closing this.  Any new reports could reopen this or, likely better, open a new issue with a description more specific to the circumstances of the new failures.
