### ISSUE TITLE
Segfault on launch on OSX 10.12.6

### ISSUE THREAD

**Issue by GndGeek** [angband/angband#4554]
Upon updating from 4.2.0 to 4.2.1, I found that Angband crashes with a segmentation fault when I open it. I verified that master has the same issue, and that the problem was introduced in the rendering path rework (7397d6f4); reverting that commit removes the crash. I haven't had time to try to figure out what's causing it, but I've attached a crash report in case anyone else wants to.
[angband_crash_log.txt](https://github.com/angband/angband/files/5301019/angband_crash_log.txt)

**Comment by backwardsEric** [comment]
GndGeek, would you have the opportunity to compile and try a modified version on 10.12.6?  The change would be to replace the lines:
`old = Term;
Term_activate(self->terminal);`

at line 3298 of main-cocoa.m (in drawRect) with

`if (Term != self->terminal) {
    old = Term;
    Term_activate(self->terminal);
}`

That may be enough to prevent the recursion that seems to be the cause of the crash.

**Comment by backwardsEric** [comment]
What I suggested above won't work (since Term_activate() is already returning early for that case).  The thing to try would be to delete the two lines,

`old = Term;
Term_activate(self->terminal);`

at line 3298 in the current version of main-cocoa.m.

**Comment by GndGeek** [comment]
Ah, that does it! Thanks.
