### ISSUE TITLE
Targeting ('*') should be enhanced to include stairs and items as "interesting places"

### ISSUE THREAD

**Issue by 3m4r** [angband/angband#4574]
Currently, targeting only includes @ and monsters as interesting places. This limits the use of *g to moving to a monster. 

If interesting places included items, collecting ammo, moving to items in a large room, etc. would be easier to do with a single keymap.

If interesting places included stairs, exiting a dlevel would also be possible to do with a single keymap.

Best of all scenarios would be changing interesting places to include items, stairs, and monsters, but also to add separate options for going to the nearest item, nearest monster, or nearest character given a character.

With this and some work on the pathing logic, a lot of DCSS-style quality of life improvements could be made simply using keymaps.

Pseudo-autoexplore, moving to the nearest down-stair, and auto-bumping monsters being the primary ones.
 
Note on pseudo-autoexplore: This could be achieved by targeting the nearest accessible unexplored grid. Something of this sort is what left-clicking on an unknown grid already attempts but the current pathing logic for it seems like it has a pretty short reach.

**Comment by 3m4r** [comment]
Okay, starting to delve into the code and I think I understand a bit more now. Target only applies to monsters, whereas look applies to everything. So look _does_ include objects and terrain as well as monsters.
 
So "interesting places" is probably working as intended already. Still, being able to distinguish in look/target mode between next item, next terrain feature, next monster, and by char would be nice enhancements.

**Comment by NickMcConnell** [comment]
I think this one and its fellows can be closed now 😄
