### ISSUE TITLE
angband: Couldn't load the requested font. (10x20)

### ISSUE THREAD

**Issue by andmars** [angband/angband#4575]
When installing angband 4.2.1 in Linux (Arch Linux) I get: "angband: Couldn't load the requested font. (10x20)" when playing in X11. Other modes like ncurses work.
There was a fix by installing "xorg-fonts-misc" package, but this no longer works.
https://bugs.archlinux.org/task/57751
Maybe you can look into the requested fonts that angband is using and make it work with X11 again?
Thanks

**Comment by NickMcConnell** [comment]
I think this is a problem with the fonts you have installed on your system - Angband is simply assuming you have the 10x20 font there.

**Comment by andmars** [comment]
Thanks for the reply. Interestingly if you google this bug, you receive similar bug reports in other distros including Debian and Ubuntu. I would say that if an issue persists across so many distros then it's on my part as a developer to try to do something about it. Hope you guys can fix this because I'd love to play a round of angband again.

**Comment by andmars** [comment]
I don't know if it helps, but "10x20x.fon" does exist in  /usr/share/angband/fonts/. Still it won't start.

**Comment by andmars** [comment]
looking into the xorg-fonts-misc package in Arch, it has:

`[andreas@andreas-pc ~]$ cd /usr/share/fonts/misc/ 
10x20-ISO8859-10.pcf.gz  10x20-ISO8859-15.pcf.gz  10x20-ISO8859-3.pcf.gz   10x20-ISO8859-8.pcf.gz
10x20-ISO8859-11.pcf.gz  10x20-ISO8859-16.pcf.gz  10x20-ISO8859-4.pcf.gz   10x20-ISO8859-9.pcf.gz
10x20-ISO8859-13.pcf.gz  10x20-ISO8859-1.pcf.gz   10x20-ISO8859-5.pcf.gz   10x20-KOI8-R.pcf.gz
10x20-ISO8859-14.pcf.gz  10x20-ISO8859-2.pcf.gz   10x20-ISO8859-7.pcf.gz   10x20.pcf.gz`

xlsfonts gives me:

`[andreas@andreas-pc ~]$ xlsfonts -fn "10*"
xlsfonts: pattern "10*" unmatched`

Not sure where to place this? Is it a bug in the arch-package of angband? Is it with xorg-fonts-misc? Or on your part? Dunno...

**Comment by backwardsEric** [comment]
My suspicion is that something went amiss with what the xorg-fonts-misc package would do to get the X server to recognize the newly installed fonts.  Part 2.2 of [Xorg's font installation instructions](https://www.x.org/archive/X11R6.8.0/doc/fonts2.htmll) describes the steps for manually installing fonts.  You could check over that (sections 2.2.2 and 2.2.4 should be the most relevant) to see if the package's scripts performed those steps on your system.  It's also possible that those steps were done but the X server wasn't told to reread its configuration file (as I recall there's a signal you can send to it to get it to do that; otherwise restarting the X server should work).

**Comment by maboleth** [comment]
I too get this error. Also Arch.

I can only start angband with -msdl option.

Is there a possible solution to include some other font or replacement, since it 's affecting major distributions?

**Comment by maboleth** [comment]
Ok, so I forgot to restart my PC after the installation. :O

It now works out of the box on Arch!

**Comment by andmars** [comment]
@maboleth So now I'm curious since we're on the same distro and presumably use the same packages what might be the difference between your config and mine?
I have this in my .xinitrc
`xset +fp /usr/share/fonts/misc/ # Inform the X server of new directories
xset fp rehash                # Forces a new rescan`
and the /usr/share/fonts/misc/ folder contains the fonts requested by angband, why do I get:
`[andreas@andreas-pc ~]$ xlsfonts -fn "10*"
xlsfonts: pattern "10*" unmatched`
What am I missing here?
(and, yes, I have rebooted my system)

**Comment by maboleth** [comment]
> @maboleth So now I'm curious since we're on the same distro and presumably use the same packages what might be the difference between your config and mine?
> I have this in my .xinitrc
> `xset +fp /usr/share/fonts/misc/ # Inform the X server of new directories xset fp rehash # Forces a new rescan`
> and the /usr/share/fonts/misc/ folder contains the fonts requested by angband, why do I get:
> `[andreas@andreas-pc ~]$ xlsfonts -fn "10*" xlsfonts: pattern "10*" unmatched`
> What am I missing here?
> (and, yes, I have rebooted my system)

Well, I don't have a .xinitrc file. I do have those fonts in /usr/share/fonts/misc, I also don't have xorg-xlsfonts installed.

I installed regular angband package with all listed dependencies from pacman. Nothing else. Hope this helped.

**Comment by andmars** [comment]
@maboleth And what desktop environment are you using? I'm on a tiling window manager (dwm) only. Maybe DEs like gnome, kde, xfce, etc. install additional fonts or configure the X-Server differently?

**Comment by maboleth** [comment]
> @maboleth And what desktop environment are you using? I'm on a tiling window manager (dwm) only. Maybe DEs like gnome, kde, xfce, etc. install additional fonts or configure the X-Server differently?

That's another possibility. I use KDE. Though considering angband is ascii by default, it should work on a bare arch.

I'm not sure what video card you use, mine is Nvidia, official, proprietary drivers.

Can you create a symlink somewhere to just connect the font to the folder where anband seeks?

**Comment by backwardsEric** [comment]
@andmars 
> I have this in my .xinitrc
> `xset +fp /usr/share/fonts/misc/ # Inform the X server of new directories xset fp rehash # Forces a new rescan`
> and the /usr/share/fonts/misc/ folder contains the fonts requested by angband, why do I get:
> `[andreas@andreas-pc ~]$ xlsfonts -fn "10*" xlsfonts: pattern "10*" unmatched`
> What am I missing here?
> (and, yes, I have rebooted my system)

Is /usr/share/fonts/misc/fonts.dir present on your system and does it have a line for the 10x20 font (on Debian Buster, the line looks like "10x20.pcf.gz -misc-fixed-medium-r-normal--20-200-75-75-c-100-iso10646-1")?  That would be necessary for xlsfonts or angband to be able to access the font (neither use fontconfig).  If it isn't present, you'd need to generate it by running mkfontdir and then you probably have to run "xset fp rehash" to get pick up the change.

**Comment by andmars** [comment]
It's fixed now. I installed xorg-mkfontscale and it looks like this created "fonts.dir" in /usr/share/fonts/misc. And I also have a `.cache/fontconfig` folder now with cache content. So now I get:
`[andreas@andreas-pc ~]$ xlsfonts -fn "10*"
10x20`
Angband is starting and I can happily play this game now. Thanks for your efforts.

**Comment by fosskers** [comment]
Installing `xorg-mkfontscale` and restarting my machine makes `angband` playable from a terminal (I use `i3`).
