### ISSUE TITLE
v4.2.1 crash on startup in OS X 10.11: dyld symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by pmer** [angband/angband#4579]
Hello,

Running the pre-compiled release binary for v4.2.1 on OS X 10.11 gives the following error on start:

```
Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Angband 4.2.1.app/Contents/MacOS/angband
  Expected in: /usr/lib/libSystem.B.dylib
```

I have gone through the previous releases, too, and this is the only release with this issue. v4.2.0 and earlier are unaffected.

Attached is a full crash report from OS X, which includes a more complete description of the environment: [Crash report.txt](https://github.com/angband/angband/files/5505533/Crash.report.txt)

**Comment by NickMcConnell** [comment]
It looks like this is a backwards compatibility issue, as the 4.2.1 release was built on 10.15.  I think the solution for older OS versions is probably to build yourself via the instructions at the bottom of [this page](https://trac.rephial.org/wiki/Compiling).

**Comment by backwardsEric** [comment]
That problem should be fixed by [this change in the master branch](https://github.com/angband/angband/commit/83781a67dc7405dde8a13d3ef4921efcca62b936) so [the nightly builds for OS X](http://rephial.org/nightlies) should run on 10.11.

**Comment by pmer** [comment]
@backwardsEric Thank you, using a nightly build fixed the issue successfully.

**Comment by pmer** [comment]
@NickMcConnell I understand your point, thanks for the reference. Fortunately, the nightly seems to be working so I'll try using that for now. Thanks!

**Comment by NickMcConnell** [comment]
Oh yes, that thing 😊
