### ISSUE TITLE
Artifact generation

### ISSUE THREAD

**Issue by AvdN** [angband/angband#4584]
I am playing nightly on angband.live and out of the 5 characters that made it to CL30 and DL30, four only found Galadriel and one Galadriel and Elendil. My current character only has Galadriel although he has slain 34 uniques.
It might just be chance, but I think something has changed to make getting an artifact much less likely, or has broken getting non-light artifacts.
Appearance of other items seems normal, wrt depth ( Spell books, one potion of Exp so far, rod of recall)

**Comment by AvdN** [comment]
As an update: On DL 51 Gorlim dropped Carlammas and Barahir was laying around. On DL 68 I found Narya. Haven't seen any other artefacts besides those four, and normally several weapons or armour would have shown up by now (CL 42)

**Comment by AvdN** [comment]
Update 2: DL75, CL 48: Found Galadriel, Train, Elendil. Narya, Barahir, Carlammas, Elessar. 
70 Uniques slain. The two things I haven't seen so far that I noticed is dwarven shields (could use the +Constitution) and shields of Preservation. I did get a shield of Elvenkind.

The big advantages is that I have not yet ran out of space in my home, normally I hoard artefacts until they don't fit anymore.

**Comment by NickMcConnell** [comment]
I really think this is just randomness.

**Comment by AvdN** [comment]
Could be, but it is more likely that Gwarl is pulling a prank on me. Just found The Necklace of the Dwarves and Nenya and still no artefact weapons/armour. CL 50, DL 86, Uniques slain: 86

**Comment by AvdN** [comment]
I just killled Morgoth, and he dropped Grond, but he didn't drop his massive crown. I have never seen that happen, are you sure that is just randomness?

**Comment by NickMcConnell** [comment]
Hm, maybe.  I'll reopen this and have a check.

**Comment by AvdN** [comment]
I am not sure when angband.live was updated (didn't see anything in the cut-off chat window), but I just found Forasgil, so this looks fixed.
Does that mean that setting "birth_no_artifacts" doesn't affect all artifacts, but just weapons/armour/diggers?

**Comment by NickMcConnell** [comment]
The problem was that I had the test back to front, so people playing with birth_no_artifacts *would* have been finding weapons/armour/diggers, but now it's behaving as expected.
