### ISSUE TITLE
Add ANGBAND_DIR_ARCHIVE to change_path_values

### ISSUE THREAD

**Issue by grcancelliere** [angband/angband#4616]
Reason:
At the moment ANGBAND_DIR_ARCHIVE is the only folder whose path can't be overridden by a "-d" switch (function [change_path](https://github.com/angband/angband/blob/master/src/main.c#L179)), so if I wanted to move all the user-related Angband folders to a different parent folder the "~/.angband/Angband/archive" folder would still be created.

**Comment by NickMcConnell** [comment]
OK, I think I know what to do here
