### ISSUE TITLE
Throwing Menu Always Starts At "a"

### ISSUE THREAD

**Issue by damedley** [angband/angband#4620]
Eg, If I have a dagger in my (s) slot in inventory, it's my only item with the thrown flag, and I try to throw it, it'll be listed in the (a) slot on the throwing menu. It's a pretty minor inconvenience, but I think it would be better to keep it consistent with the other menus. I guess if the dagger is in my quiver I'd have to press a number key instead of a letter.

**Comment by NickMcConnell** [comment]
Thinking about this one.

**Comment by NickMcConnell** [comment]
If you have a dagger you want to use for throwing, you can inscribe it @v0 (or similar), which will put it in the quiver; it still gets a letter in the throwing menu, but you can use either that or 0 to select it.  I think this is adequate.
