### ISSUE TITLE
No save restore etc options birth options windows port

### ISSUE THREAD

**Issue by timmy02l** [angband/angband#4622]
Hi, in the windows port of angband there isn't options in birth options to save or restore options, although this is in the mac port.

Thanks.

**Comment by backwardsEric** [comment]
That's a fairly recent change (10 November 2020) and is only available so far in the nightly builds or if you build an executable yourself from sufficiently new versions of the source code.  [This is the most recent Windows build](http://angband.oook.cz/forum/showpost.php?p=148589&postcount=85) I found, but it predates that change.

**Comment by NickMcConnell** [comment]
OK, this is sorted then (and there is a new windows build [here](https://github.com/angband/angband/releases/tag/4.2.1-190-g5c16b9e7)).
