### ISSUE TITLE
linux build errors for angband 4.2.1 when both --enable-sdl and --enable-sdl2 used 

### ISSUE THREAD

**Issue by pscheyen** [angband/angband#4623]
configure angband 4.2.1 on Ubuntu-based distro with --enable-sdl and --enable-sdl2 succeeds.  The build then fails with a variety of errors in main-sdl.c.  main-sdl2.c builds successfully.

configuring sdl or sdl2 alone builds fine.

**Comment by NickMcConnell** [comment]
I guess correct behaviour would be for configure with --enable-sdl and --enable-sdl2 to either fail, or fall back to picking just one (probably sdl2).
