### ISSUE TITLE
Document conversion in GitHub release workflow

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4630]
Should the documents copied to the zip and dmg files in the GitHub release workflow be in a converted form or forms rather than the raw restructured text?

If converted, what should the output format or formats be?  And are there preferences for the style used?  Should it try to mimic the documents displayed on rephial.org?

From what I remember, there were incompatibilities between the style configured in the docs folder and the set of tools available in Debian Buster's packages:  requiring some changes before the conversion process would run to completion.

**Comment by NickMcConnell** [comment]
I'm not sure, I've never taken much notice of that.  I've noticed the unix2dos stuff in pkg_win, and that the Mac port seems straightforward.  Magnate used to package for Debian, but hasn't since 3.5, and I'm not sure what was required.

**Comment by backwardsEric** [comment]
The part about Debian wasn't intended to get at packaging for different Linux distributions.  It was more to say, from my one attempt at it, that running the Makefile in docs didn't seem fully compatible with a current distribution's version of sphinx-build.  Probably, that was solely due to me not setting up the 3rd party theme, https://github.com/irskep/sphinx-better-theme, it expected.

As I see it, the docs written to the zip and dmg files should, ideally, be in some format (HTML, maybe PDF, ...) that's easy to access.  Now that I know where to get the theme, I'll see if I can update the release workflow to have a step to run the document conversion and then put the converted documents and their dependencies in the zip and dmg files rather than the document source.
