### ISSUE TITLE
Big Windows executable from release workflow

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4634]
The angband.exe generated by the release workflow is roughly 5.7 MiB.  angband.exe in the 4.2.1 zip file is 1.6 MiB.  I don't have any leads for why it's so much larger than in 4.2.1.

**Comment by Zireael07** [comment]
Maybe the workflow is defaulting to keeping debug information?

**Comment by NickMcConnell** [comment]
It would be good to answer this, but I don't think it's urgent

**Comment by backwardsEric** [comment]
I get a similar, albeit somewhat larger, executable size using the mingw cross-compiler in Debian Buster's packages - so the issue doesn't seem to be specific to the Ubuntu 18.04 environment used for the Github workflow.  Both that build and the Github workflow are following the instructions at https://angband.readthedocs.io/en/latest/hacking/compiling.html#cross-building-for-windows-with-mingw .  Did the procedure that generated the 4.2.1 executable do something beyond that - for instance, setting compiler options when invoking configure or stripping the executable after it was built?

**Comment by NickMcConnell** [comment]
IIRC I built the 4.2.1 executable by hand using MinGW on Windows 10.  Previous ones have been done through the buildbot instance on rephial - I can look at those and see whether I can pick any obvious differences.

**Comment by NickMcConnell** [comment]
Leaving open for now, reluctantly.
