### ISSUE TITLE
Not able to dig in magma with shovel in backpack

### ISSUE THREAD

**Issue by AvdN** [angband/angband#4641]
(While playing nightly on angband.live)

My STR 15 mage was gathering money for his third spellbook by digging in magma & quartz veins using a shovel (0, 0). At some point he couldn't dig anymore and I thought the shovel was dropped from the backpack (happens sometimes when you auto-pick up), but it was there.

The culprit was a lance (also (0, 0)) that the character had auto-picked up, and that was preferred as digger although the character could not wield the lance (not strong enough to wield, and inspecting the lance indicated it could not be used to dig into magma).
Dropping the lance, restored the ability to dig into magma.

If re-prioritizing lances below shovels if STR is not high enough is too difficult, it would be useful to extend the message "You futilly chip away at ..." with "with your Lance (0, 0)", then it is at least clear what "digger" the game has selected to swap in.

(my main weapon was a maul of extra attacks, which can also dig into magma, but not as fast as the shovel. 24 vs 17 turns)

**Comment by NickMcConnell** [comment]
I think the best thing would probably to rule out weapons that are too heavy.

**Comment by NickMcConnell** [comment]
Fixed in 14c105f21

**Comment by AvdN** [comment]
Thanks, I can confirm this is fixed
