### ISSUE TITLE
shouldn't pick up when backpack full, causing unexpected drop

### ISSUE THREAD

**Issue by AvdN** [angband/angband#4642]
(Angband nightly on angband.live)
With a full backpack, and "always pick up items: yes",  I walked over a Flask of Oil, which caused that to be picked up and the last item in my backpack (not in my quiver) to be dropped. Even when I inscribed that item with !d, dropped the oil, picked up the item and walked over the oil, this happened again.
This is both counter-intuitive and did not use to be like that.
![angband_overflow](https://user-images.githubusercontent.com/1210650/108028788-ab50c000-702c-11eb-8ac6-f99b1bd7ada4.png)

Later on, with still a full backpack, this did not happen while walking over an unidentified potion of Poison, nor an unidentified potion of True Seeing, nor an identified Robe (giving "You have no room..."). So this might be oil specific.

**Comment by NickMcConnell** [comment]
It may be related to the fact that oil is used in the throwing menu.  I'll check.

**Comment by NickMcConnell** [comment]
Yes, problem is the flask could be put in the quiver (which I think is actually wrong itself...), and is failing to be.  Working on it.
