### ISSUE TITLE
option to suppress prompts altogether

### ISSUE THREAD

**Issue by AvdN** [angband/angband#4646]
If you are playing with auto_more on angband.live, and show messages in a window above the play area (Term-3), it would make sense to be able to suppress the prompt altogether, as you already see all the messages in Term-3.

Currently if you do set things up this way, it looks like the last line is repeated in the message window, whereas in fact the last line of the message window equals the (superfluous) prompt.

**Comment by NickMcConnell** [comment]
So there are two types of thing that appear on the top line of the main screen - messages (as appear in the message window) and prompts for action (which direction, quaff which potion, etc., which **don't** appear in the message window).  I think what you're asking is not to print messages on the top line at all - is that correct?

**Comment by AvdN** [comment]
I realise that the  the prompts should stay, as they don't end up in the message window. It is the messages that end up in the message window that should be suppressed.

![image](https://user-images.githubusercontent.com/1210650/108617278-4246bf00-7415-11eb-90ad-98edaa735ec4.png)

So you don't get the double lines. IMO it would be better if it is empty.

The logic would have to be something like: if option is set and written to message stack (or what ever it is called that is shown in the message window and for which you can scroll back using Ctrl+P in rogue mode), then do nothing, else show message in top row of main window.

**Comment by NickMcConnell** [comment]
After consideration, I'm reverting this, as people not using angband.live didn't like it.
