### ISSUE TITLE
inven_carry_num():  behavior for some corner cases

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4655]
For inven_carry_num() what should the behavior be when stack is true, there's similar objects in the pack, and there's at least one pack slot available.  Should it have the current behavior, return obj->number?  Or should it only return the number that could be accepted without requiring an additional pack slot?    Nothing in the current code base calls inven_carry_num() with stack set to true, so the question is an academic one at this point.  However, I was starting to write some test cases and wondered what behavior should be expected.

Another case where inven_carry_num()'s current behavior may be suspect is:

1. There's one pack slot available.
2. There's at least one quiver slot available.
3. The object has the THROWING flag, is not ammunition, and is inscribed so it would go into one of the empty quiver slots.
4. Adding the object to the quiver would cause the quiver to expand and use up the remaining pack slot.
5. obj->number is bigger than z_info->quiver_slot_size / 5.
6. stack is false.

In that case, inven_carry_num() returns obj->number as the amount that would be accepted, but since calc_inventory() would put the object in the quiver (filling up the remaining pack slot so none could be absorbed there), the maximum that could be added is z_info->quiver_slot_size / 5.

**Comment by NickMcConnell** [comment]
OK, I need to think about this.  I assume inven_carry_num() used to be called with stack true for the case where pickup_inven is true, and am not 100% sure why it isn't still.

**Comment by backwardsEric** [comment]
Yes, the pickup_inven case is when stack was set to true.  It was lost in this commit from me, https://github.com/angband/angband/commit/a5647cb5b5d84730bfe860d7e2ecf5b7f2b85d77#diff-56cbac94136bd3253c8b79ab9c2676b01771a6b8d87b541de389dd17c671c78d .  Since the gear had to be checked for the "!g" or "=g#" inscriptions anyways, it combined what was done in the stack equal true case into it's own loop over the gear.  Given what it was used for (only checking if a compatible stack is present), the current behavior is correct:  returning obj->number when stack is true, there's a compatible stack, and at least one pack slot is available.

**Comment by NickMcConnell** [comment]
OK. So for your two cases of suspect behaviour, I think the responses should be:

1. Remove the stack argument from inven_carry_num() altogether;
2. This is subtle.  I think the current behaviour is correct; if the player insists on putting the objects stack in the quiver, they only get to hold as many as the quiver slot they have specified will hold.  But it's not very intuitive, and will probably confuse people.  Still, can't please everyone 😃

**Comment by backwardsEric** [comment]
For the number 2 case (tested with picking up 14 daggers; had one dagger and 60 arrows in the quiver and one free pack slot), the in-game behavior on pickup triggers a pack overflow.  All 15 daggers end up displayed in the same quiver slot when displaying the quiver; the quiver itself takes 4 pack slots as expected (60 + 15 * 5 = 135 = 3 * 40 + 15).  I'd argue that inven_carry_num() should be modified to prevent the overflow on pickup, but I wouldn't stall the release for that.

**Comment by backwardsEric** [comment]
With #4671 in place, the cases mentioned have either been removed (no stack parameter) or resolved.
