### ISSUE TITLE
Daggers Less Damage than Reported?

### ISSUE THREAD

**Issue by damedley** [angband/angband#4656]
Been playing a game on Live for a while and throwing a dagger that says it does 200 damage to undead. And for the longest time it was. But now it isn't doing nearly that.

Also, saying I don't have room for a dagger when I clearly do. Maybe I am playing an old version. Version ends in 8655a.

**Comment by NickMcConnell** [comment]
So you're saying the same dagger was doing about 200 damage, and now isn't?  When did you notice the change?  And when you say you obviously do have room for a dagger, can you give more detail?

**Comment by backwardsEric** [comment]
The current expected behavior (presuming I've read the code correctly) for whether there's room for the dagger is that at least one of the following is true:

1. There's a free pack slot.
2. It can stack with a dagger already in the pack or quiver.
3. It has an inscription containing '@vx' or '@fx' where x is the number of an empty slot in the quiver.

**Comment by damedley** [comment]
Yeah, at the time I had around 60 arrows. It wouldn't let me pick up the dagger directly to my quiver. I dropped about 20 arrows, picked up the dagger, then picked up the arrows again no problem.

I can't remember how long ago the dagger was doing 200 damage. Maybe a month or two? I took some time off with this character (trying to get my card game published).

**Comment by backwardsEric** [comment]
With a full pack and 60 arrows in the quiver, manually picking up a dagger inscribed with '@v2' works for me with the latest code.  Without the inscription, picking it up isn't possible unless there's a free pack slot (after dropping twenty arrows, can pick up the dagger but then can't pick up the dropped arrows).  Auto-pickup (pickup_equip with one such dagger already in the quiver; dagger on the floor either not inscribed or inscribed with '@v2') also works in my tests when the pack is full.

Is auto-inscription at play here?  My tests were done without it.  One of the times auto-inscription triggers is when the object is picked up, but the tests before pickup only look at what's currently inscribed on the object and don't factor in what auto-inscription would add.

**Comment by NickMcConnell** [comment]
Hm, the only commit which changed player-attack.c (and so which could have varied the damage) since May last year was 43529f659 ...  I wonder who did that one...

**Comment by NickMcConnell** [comment]
Not that that commit actually caused any problems, I just found it funny 😃

**Comment by damedley** [comment]
Oh, sure, blame it on the dumbest guy on the team. Easy target.

**Comment by damedley** [comment]
I withdraw my suspicion that daggers are doing less damage than reported. It happened to me twice, or so I thought, but now I see that the second time I wrongly assumed a Greater Rotting Q was undead. Can't recall what the first event was, but I was probably mistaken there, too.

**Comment by NickMcConnell** [comment]
All right, I'm calling this one done then, as the rest is covered in #4655
