### ISSUE TITLE
Lightning Balls Underpowered

### ISSUE THREAD

**Issue by damedley** [angband/angband#4657]
This should probably be pushed off to 4.2.3, but I wanted to get it on the record before I forgot.

Lightning *balls* seem woefully underpowered. I can only guess that when lightning bolts became beaming, lightning damage got reduced. This makes sense for bolts/beams, but not for balls. This applies to rods and wands, maybe other stuff.

**Comment by NickMcConnell** [comment]
They appear earlier than other balls, and are also arguably the most useful (not resisted by many monsters and don't destroy many objects).  So they're working as intended.
