### ISSUE TITLE
Automated release script for full release

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4658]
If you're intending to use the current automated release script for the 4.2.2 release, these are the potential problems that come to mind:

1. The script only triggers on pushes to the master branch and, if the tag on that branch's head looks like one for a full release, it'll generate a release that's not tagged as a prerelease.  The readme for the release will be automatically generated by GitHub in the same way as it is for the current prereleases.  It may be better to always have the full releases generated as drafts so you can manually review them from the releases tab, set up the readme, and then turn off the draft flag when they look read to go.  To help with debugging the release process without leaving a mess in the master branch, the script could also trigger on pushes to another branch (release-test perhaps) and generate the zip and dmg files but, in that case, leave them as action artifacts without pushing them to the release page.
2. The source code archives automatically added by GitHub don't include the configure script and its dependencies and don't include the file, 'version', at the top level containing the version string.  For a full release (and, perhaps, for the prereleases as well), I'd guess that it would be nice to have source code archives that would be usable without having autoconf (for building with ./configure ...) or git (to get the version string properly) installed.  The automated script could have a stage to run "make dist" to get the archive and put it in the release.

**Comment by NickMcConnell** [comment]
So for 1, I normally do any write up for github (or formerly for rephial) myself; all I really care about is the version number being internally correct (not certain, as I sometimes forget to push tags...).  For 2 - I didn't realise that, I assumed the configure script was included.  Ideally it would be, but I don't think I'll delay release for it.  Release is currently delayed because I was trying to work out if there was anything to this dagger pickup bug - I think there probably isn't, and will try and release sometime this week.

**Comment by backwardsEric** [comment]
I added a pull request that includes a source archive generated with "make dist" in the automatically generated release assets.

For the first point, adding the logic to the release script so releases that aren't prereleases will be marked as drafts is easy.  That way you can do the write up before it's officially published and then remove the draft flag.  Handling the case where one forgets to push the tag may be harder - just pushing tags doesn't seem to automatically trigger the script.  The option in GitHub's UI to manually re-run the script may work in that case or push some sort of commit to trigger the script to rerun.

**Comment by NickMcConnell** [comment]
OK, cool - and I wasn't suggesting there was some coding solution to my forgetfulness 😄

**Comment by backwardsEric** [comment]
I added a pull request to change the release script so any release that isn't a prerelease will be marked as a draft.  Unless you have other concerns about using the release script for a full release, that should resolve this issue.

**Comment by NickMcConnell** [comment]
Excellent, thanks

**Comment by NickMcConnell** [comment]
Resolved in a7736ddcb
