### ISSUE TITLE
auto-ignoring settings

### ISSUE THREAD

**Issue by igroglaz** [angband/angband#4661]
Usability improvement: as players die often - every time player need to spend several minutes in item ignore setup to restore settings used for previous character.

It will be fun to have one day possibility to assign auto-ignoring settings in .prf file, so eg if you play chars who can't read the books - you could just add it to config initially without need to add stuff with every RIP

**Comment by NickMcConnell** [comment]
It used to be like this back about 3.3, but the problem is people will use their old savefile to play a different character which needs different ignore settings.  So the whole idea was ditched.

**Comment by igroglaz** [comment]
Maybe add possibility to save this ignore setting to a separate .prf file? so if needed it will be possible to load it from game options window

**Comment by igroglaz** [comment]
Still pretty actual issue..
