### ISSUE TITLE
Suggestion: allow 'running' in Arcade Control -> Dimension Door

### ISSUE THREAD

**Issue by AvdN** [angband/angband#4681]
I use Dimension Door (30 level Magic User spell from Arane Controll book) a lot after receiving the spell, on angband.live ( 4.2.2, nightly). It helps getting to a particular place without the lag of redrawing shadows in rooms, so I use it sometimes just jump 20-30 gridpoints.

However since long east-west movements can easily involve 100+ keystrokes I invariable tend to press and hold a key ('h', 'l') to long and the input buffer fills up quicker than the lagged update can show. Pressing those keys individually that many times is a pain as well.

Could it be changed that while selecting the target for Dimension Door that "running" ('H', 'L' for east and west, but also for the other directions) would jump 10 grids at a time? That would allow to move the cursor in a more controlled way, at least in rogue mode.

**Comment by NickMcConnell** [comment]
OK, this is a good idea, but I'm reluctant to mess further with the horrible target-setting code without completely overhauling it (see #3399).  So I'm going to set this to Future.
Do note that you can click the mouse on where you want to go directly, which is much more efficient.
