### ISSUE TITLE
Tile issues

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#4717]
See [this post](http://angband.oook.cz/forum/showpost.php?p=152554&postcount=17).

**Comment by backwardsEric** [comment]
For the first issue in that post, is the solution similar to the resolution for https://github.com/angband/angband/issues/4577 : change the entries for the general store, armory, and weapon smith so they don't use the tiles from the double height row, 0x9B ?  The other stores on that row currently have completely transparent top halves.

**Comment by NickMcConnell** [comment]
So is this one all done now?

**Comment by backwardsEric** [comment]
There's still a clearing problem with the overhead view in the Mac front end:  with big tiles, part of the last row of tiles isn't cleared.  I believe I know the cause - the clipping done in Term_big_queue_char() to avoid overwriting the status line in the main window - but haven't finished testing my solution (passing in how to clip as an argument).

**Comment by backwardsEric** [comment]
With #4784 applied (to fix clearing of overhead views using big tiles on the Mac), the problems in this issue have been resolved.
