### ISSUE TITLE
Altering a permanent wall gives wrong message

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4729]
If I try to tunnel with control-direction, it says "You spin around", as if I tried to alter an empty grid. 

The actual tunnel command says it's permanent rock.

**Comment by NickMcConnell** [comment]
This is because the test for digging in the alter command is now for whether the grid is diggable.  So you get the "You spin around" message because all the attempts at alteration have failed.  For all the game knows, you may have been trying to unlock the wall 😃
