### ISSUE TITLE
I think something's off with the randomness of teleport

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4734]
So, I was working on a vault in sector 1,0, and teleported away an ancient dragon and two Maia. 

Then I failed to disarm a teleport trap, and it teleported me into a room at 2,7 (essentially as far southeast as I could get in the dungeon), right next to the ancient dragon and both Maia.

I know randomness is random, and weird things can happen, but this is suspicious.

Edit: There are also two other special rooms along the right side of the map, which are probably constraining landing spots there.

**Comment by jl8e** [comment]
(I have the save file for the original post if it's useful.)

I just encountered it again, with a level with a greater vault in the bottom left, and a nexus Q on right center that kept teleporting me away to the top left.

I recall this sort of problem showing up way back when, due to teleport ranges being too long, leading to too few target locations being available.

**Comment by NickMcConnell** [comment]
This is basically working as designed.  The teleport algorithm tries to match the intended teleport distance; if there are only a few choices, you will get one of those.
