### ISSUE TITLE
main-sdl2.c issues with MSVC

### ISSUE THREAD

**Issue by user673679** [angband/angband#4737]
Just to point out a couple of changes I had to make to get angband to compile and run using MSVC with `WINDOWS` and `USE_SDL2` defined:

 * In `main-sdl2.c` in `handle_menu_tile_sets()`, a variable length array is used. This isn't supported by MSVC (and probably never will be).  Changing the `elems` array to use `mem_alloc` and `mem_free` at the end of the function seems to work fine.

		size_t num_elems = 0;

		graphics_mode *mode = graphics_modes;
		while (mode != NULL) {
			num_elems++;
			mode = mode->pNext;
		}

		struct menu_elem elems[num_elems]; // VLA :(
		...

 * I get a crash in `z-file.c` in `my_dread()`, that seems to be caused by a double free. Specifically, this bit:

		/* Try the first file */
		if (dir->first_file) {
			/* Copy the string across, then free it */
			my_strcpy(fname, dir->first_file, len);
			mem_free(dir->first_file); // CRASH :(

			/* Wild success */
			return true;
		}
		...

   Since `dir->first_file` isn't set to NULL after being freed, when `my_dread()` is called in a loop (in my case from `init_font_info` in `main-sdl2.c`), we re-enter that same `if` statement, and call `mem_free` on `dir->first_file` a second time. Putting `dir->first_file = NULL;` fixes the issue for me.

**Comment by NickMcConnell** [comment]
Thanks, I love problems that come with a solution attached 😄
