### ISSUE TITLE
Traps you set off don't necessarily appear on the map

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4739]
I'm running half-troll warriors ATM, so have truly abysmal searching, and at low levels, I'm frequently setting off traps, then trying to disarm a space that hasn't gained the ^ symbol.

**Comment by NickMcConnell** [comment]
Sometimes setting a trap off destroys it.  Could this be what is happening?

**Comment by jl8e** [comment]
No, the traps were still there

**Comment by jl8e** [comment]
I have an example save. In this case, I'm trap immune from my weapon, and there's a dart trap one step south. If I step on it, it tells me there's a dart trap, but it's still a floor space.

If I take off the weapon and step south, I set off the trap, and it still doesn't appear.
[trap.zip](https://github.com/angband/angband/files/6378340/trap.zip)

**Comment by NickMcConnell** [comment]
OK, I'll need randart_00515268.txt this time...

**Comment by jl8e** [comment]
Sorry. Maybe I should stop playing with randarts. :)
[randart.zip](https://github.com/angband/angband/files/6380596/randart.zip)
