### ISSUE TITLE
Digging info is inaccurate

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4742]
According to the Inspect info for my weapon (a dagger of slay orc), it doesn't affect granite. (My strength is 18/60)

I'm digging through granite with it.

**Comment by backwardsEric** [comment]
In Angband 4.2 and later, the game will automatically swap the wielded weapon for a weapon in the pack when digging if there's something in the pack that'll work better.  If your pack has something capable of dealing with granite, that's likely what is happening (digging without the swap weapon or weapons in the pack would verify that).  If there's not something in the pack that can deal with granite, then there's definitely a bug.

**Comment by jl8e** [comment]
I have a shovel of digging.

That behavior is ever so slightly unmentioned by the game

**Comment by jl8e** [comment]
I just confirmed this.

A message in the history about "digging with a shovel of digging..." would go a long way to letting people know about this

(Does your regular weapon unequip?)

**Comment by backwardsEric** [comment]
The regular weapon is swapped out while digging and then swapped back at the end.  The intent is that, except for the effect on the digging, the player won't see a change in the character's state (so swapping out a +INT +WIS +CON weapon with ESP for a plain shovel shouldn't trigger a drop in the hit points or mana that would have to be regenerated or lose the player's sense of nearby monsters).

**Comment by jl8e** [comment]
And if something breathes on you mid-dig?

**Comment by backwardsEric** [comment]
The resistances from the original weapon are in place (if I'm understanding the code correctly).  Internally a separate bit of player state is computed with the digger and used for digging; everything else sees the normal player state with the original weapon.

**Comment by jl8e** [comment]
Is there any reason not to just have a dedicated digging slot? Diggers are already so disadvantaged by weight in the early game and lack of need in the later game, and inventory slots are so precious.

It'd make the ability to use diggers without swapping more obvious, and simplify the code.

**Comment by NickMcConnell** [comment]
I am happy with the current state.  The way it works is mentioned in the help, and it's a setup that was asked for and that several people have approved of.
