### ISSUE TITLE
Autoswap for digging and sticky curses

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4746]
Currently it doesn't consider them at all and allows the exchange if the current weapon or the one in the pack have a sticky curse.  May not matter for Vanilla if the only things with sticky curses are the two non-weapons in the standard artifacts.

Should it enforce the "realistic" behavior:  don't allow the current weapon to be swapped out if it has a sticky curse and don't allow something in the pack to be swapped in if it has a sticky curse?

**Comment by NickMcConnell** [comment]
I think probably it should.
