### ISSUE TITLE
Unstable wall lighting 

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4748]
I have a wall segment that doesn't have stable lighting. It keeps toggling between lit and unlit while I stay still.
It's a single-panel maze level.

I have a save with it, attached here.
[light-jarin.zip](https://github.com/angband/angband/files/6371118/light-jarin.zip)

**Comment by NickMcConnell** [comment]
I'll need your randart file  - it should be called randart_07e2b546.txt and be in your archive directory

**Comment by jl8e** [comment]
Sorry; didn't realize the save file wasn't self-contained.
[randart.zip](https://github.com/angband/angband/files/6372153/randart.zip)

**Comment by NickMcConnell** [comment]
It is for standard artifact games; for randart games it writes a standalone file so people can re-use a set of randarts if they want to.

**Comment by NickMcConnell** [comment]
OK, not a bug.  There is a dark hound moving around out of your view; when it walks next to that grid, it casts shadow on it.
