### ISSUE TITLE
Round rooms usually have weird, blobby halls around them

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4761]
I suppose this could be deliberate, but it's weird if so.

Round rooms usually have large open spaces and double-width corridors around them, like it's confusing the dungeon generation algorithms. A couple of screenshots attached:

[round.zip](https://github.com/angband/angband/files/6377694/round.zip)

**Comment by NickMcConnell** [comment]
This has been a longstanding problem (see #4177), which has finally probably been solved by @backwardsEric in 3dc1cb1 three days ago.  So nice timing on asking 😄
