### ISSUE TITLE
Visible doors don't update as soon as they're visible

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4767]
No save for this one, but I had a situation like this:

###########+##
@
##############

Where the door had been broken open, but it didn't update until I moved closer

(In case it matters, I was actually to the right of the door, but that's harder to draw in a proportional font)

**Comment by NickMcConnell** [comment]
This is intentional, the player now doesn't see terrain changes until they're in LoS.

**Comment by jl8e** [comment]
But, I saw the door in the first place

**Comment by NickMcConnell** [comment]
In that configuration, though, it wouldn't be currently in your line of sight.
