### ISSUE TITLE
Ignore can make Mimics vanish

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4785]
I just fought a ring mimic that wasn't visible. What I'm pretty sure happened is that I ignored the ring type chosen for it after it was generated.

**Comment by NickMcConnell** [comment]
I'll need to try and reproduce this.

**Comment by NickMcConnell** [comment]
Did it become visible once you attacked it?

**Comment by jl8e** [comment]
Yes, iirc, though it may have died immediately. It was an empty square, and became a mimic when I tried to enter it.

**Comment by NickMcConnell** [comment]
OK, I think this is actually working as designed, then.  The entire ignore system involves a little weirdness like this (for example sensing an object, and then having it disappear when you see what it is), but I think overall this is consistent.
