### ISSUE TITLE
macOS 10.11 issues

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#4824]
4.2.1 crashes with the error:
Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Volumes/VOLUME/Angband.app/Contents/MacOS/angband
  Expected in: /usr/lib/libSystem.B.dylib

With the latest build, the app starts without opening a window, and selecting window 0 from the menu gives a crash:
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x8:
-->
    __TEXT                 0000000105d6e000-0000000105ea6000 [ 1248K] r-x/r-x SM=COW  /Volumes/VOLUME/Angband.app/Contents/MacOS/angband

Application Specific Information:
Performing @selector(selectWindow:) from sender NSMenuItem 0x7f89aa443b00

Is 10.11 still supported?  Makefile.osx says 10.9 is the minimum.

**Comment by backwardsEric** [comment]
The first of those was fixed between 4.2.1 and 4.2.2 by https://github.com/angband/angband/commit/83781a67dc7405dde8a13d3ef4921efcca62b936#diff-94e456c479a88c3211ed26c85098a78a98349989249c34253f7031522e7abdd8 .

For diagnosing the latter, what happened when the main window should have been displayed at startup will be more useful than the later crash from trying to get it to display.  Looking at the logs with Applications->Utilities->Console might be able to pull up something but it's probably easier to run the application from a Terminal and report the messages generated there.  Open a Terminal (Applications->Utilities->Terminal) then enter the following in that (for the first line, replace AngbandDir with the directory where Angband is installed, i.e. /Applications if it's in the standard Applications directory; if it's in the Desktop for the current user use ~/Desktop for AngbandDir):

```
cd AngbandDir/Angband.app/Contents/MacOS
./angband
```

I don't have access to anything earlier than 10.15.7 so this isn't something I can verify myself.

**Comment by jl8e** [comment]
`open Angband.app`

would also work.

(I have access to 10.11; it's the last supported OS on my ancient Mac.)

**Comment by backwardsEric** [comment]
If this is a system where Angband was run previously, it's possible that the stored application settings are causing the failure of the main window to appear.  What could be done to test that is this (all from a Terminal; with Angband not running):

```
defaults read ~/Library/Preferences/org.rephial.angband.plist > ~/Desktop/angband-settings.txt
defaults delete ~/Library/Preferences/org.rephial.angband.plist
```

Then try to restart Angband.  The first line there is to make a human readable copy of the previous settings; the second line deletes the prior settings.  If Angband does start and show the main window after doing that, could you send the generated ~/Desktop/angband-settings.txt (it'll be on the Desktop)?  That would help identify what was triggering the problem (there shouldn't be anything sensitive in those settings, but all that matters is the selected fonts, GraphicsID, and window geometries so the rest could be excised before sending).  If you want to restore the old settings (i.e. to run the old version of Angband that works in the configuration that you had it), this would work (again run from the terminal):

```
defaults write ~/Library/Preferences/org.rephial.angband.plist "`cat ~/Desktop/angband-settings.txt`"
```

**Comment by NickMcConnell** [comment]
OK thanks, I've emailed the original bug reporter.

**Comment by NickMcConnell** [comment]
And here it is:
{
    "FontName-0" = "Menlo-Regular";
    "FontSize-0" = 18;
    FramesPerSecond = 60;
    NSFontPanelAttributes = "1, 0";
    NSNavLastRootDirectory = "~/Documents/Angband/save";
    NSNavPanelExpandedSizeForOpenMode = "{712, 448}";
    "NSWindow Frame AngbandTerm-0" = "1 337 1101 538 0 0 1440 877 ";
    "NSWindow Frame AngbandTerm-1" = "3 78 592 259 0 0 1440 877 ";
    "NSWindow Frame AngbandTerm-2" = "1100 565 340 310 0 0 1440 877 ";
    "NSWindow Frame AngbandTerm-3" = "1102 73 338 267 0 0 1440 877 ";
    "NSWindow Frame AngbandTerm-4" = "1101 343 338 223 0 0 1440 877 ";
    "NSWindow Frame AngbandTerm-5" = "593 76 510 259 0 0 1440 877 ";
    "NSWindow Frame NSFontPanel" = "929 110 445 237 0 0 1440 877 ";
    SaveFile = PLAYER;
    Terminals =     (
                {
            Columns = 102;
            Rows = 24;
            Visible = 1;
        },
                {
            Columns = 98;
            Rows = 20;
            Visible = 1;
        },
                {
            Columns = 56;
            Rows = 24;
            Visible = 1;
        },
                {
            Columns = 56;
            Rows = 20;
            Visible = 1;
        },
                {
            Columns = 56;
            Rows = 16;
            Visible = 1;
        },
                {
            Columns = 84;
            Rows = 20;
            Visible = 1;
        },
                {
            Columns = 80;
            Rows = 24;
            Visible = 0;
        },
                {
            Columns = 80;
            Rows = 24;
            Visible = 0;
        }
    );
}

No GraphicsID?  Would that cause it?

**Comment by backwardsEric** [comment]
Not from what I see.  There's a set of default preferences, and the user's ones override those if set.  Without GraphicsID, it picks up the default for ASCII, at least on 10.15.5.

Using that preferences file and starting up on MacOS 10.15.5 either with 4.2.2 or with post 4.2.2 works.  I also tried with the columns and rows for the main window set to be bigger than the screen size and that also worked, but I suspect that I also have to change the frame sizes as well which I didn't do in that test.

You didn't directly mention it, but since the reporter sent back the old preferences file, did clearing out the old preferences let it start up successfully on the 10.11 system?

**Comment by NickMcConnell** [comment]
No, it didn't.

**Comment by backwardsEric** [comment]
Besides the earlier suggestion to run the executable from the terminal and get what messages it produces, there's a release here, https://github.com/backwardsEric/angband/releases/download/4.2.2-145-ga1544b13/Angband-4.2.2-145-ga1544b13-osx.dmg , with tracing statements added to the Mac front end (other than those tracing statements, it's the current master branch; the source code is here, https://github.com/backwardsEric/angband/tree/macos-trace-startup ).  The output from the tracing statements will end up in ~/Documents/Angband/mac.log .  One could run that on the 10.11 system and report what's in mac.log  The very top with the initialization of the main window is likely what's of interes.  Running on MacOS 10.15.5 gives this as the first part of the log:

```
Entering load_prefs...
Leaving load_prefs
Entering init_windows...
Entering Term_init_cocoa...
this is the main window
Entering context's init...
Finished super class's init
Leaving context's init
window font Menlo-Regular 18
Entering setSelectionFont...
Entering updateGlyphInfo...
font metrics: 16.708008 ascender -4.245117 descender 10.836914 median advance 11.000000 x 21.000000 tile dimensions 0 npre 1 npost
Leaving updateGlyphInfo
Leaving setSelectionFont
window initial size 102 x 24
Creating primary window in makePrimaryWindow...
Finished creating primary window; window = 0x10052b880 view = 0x10054ecb0
calling main window's makeKeyAndOrderFront window = 0x10052b880
Leaving Term_init_cocoa
Leaving init_windows...
```

**Comment by NickMcConnell** [comment]
OK, the answer is:
i tried to run the binary from https://github.com/backwardsEric/angband/releases/download/4.2.2-145-ga1544b13/Angband-4.2.2-145-ga1544b13-osx.dmg
but the Angband folder in ~/Documents doesn't get created... i checked first with the previous Angband folder there (from previous install i suppose) but mac.log was not in it.
after the first try i deleted that folder and now it doesn't get created anymore. i can click on New at the top, nothing happens. if i click Window - Angband 0 it just crashes
(indeed must be something with initialization of main window)

I'm kind of inclined to give up at this point.

**Comment by backwardsEric** [comment]
From that description, applicationDidFinishLaunching() is not called.  That's what calls beginGame() where the directory setup and window creation happens.  Given that the Windows menu is there (is the Command menu also there?), it sounds like awakeFromNib(), an earlier step in the initialization process, was called.

My (very limited understanding) is that the usual cause for this is that the "application delegate" isn't properly hooked up through the .nib/.xib/storyboard file.   In this case, that seems okay (and it works with other versions of MacOS:  as I recall, there was someone who ran one of the post 4.2.1 builds on MacOS 10.12).

If the reporter is interested in more debugging, there's another release.  It's built with the pre-4.2.1 Mac front end (and thus the old .nib file which could affect whether applicationDidFinishLaunching() is called) but with the rest of the code for post-4.2.2.  That release is here, https://github.com/backwardsEric/angband/releases/download/4.2.2-158-gee9012a7/Angband-4.2.2-158-gee9012a7-osx.dmg , (source code is at https://github.com/backwardsEric/angband/tree/macos-pre-4-2-1 ).  If that works to display the main window, then the problem should be in how the .nib file in 4.2.1 and later was generated.  If that release does not work, I am not sure what's the next step for diagnosing the cause.

**Comment by NickMcConnell** [comment]
I think there is enough that's dubious about the whole business that we can just disregard this now; also the original complainant now has a new macbook running version 11.  jl8e, if you wanted to test any of Eric's stuff on your copy of 10.11, feel free, but I'm going to close this.
