### ISSUE TITLE
the use of the list-xxx headers is deeply unreadable

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4828]
I was trying to read my way up the code chain to see how earthquakes work, and there's a massive discontinuity when you try to find the name of an effect handler. 

In order to get the effect handler name, you have to find the definition of the effects table down at the bottom of effects.c, understand two levels of macros with string pasting, and then check list-effects again. (Or just search effects.c for 'quake', I admit, but I was also trying to see how to get from a to b.)

I have to assume that this breaks any IDE's ability to understand the code.

What is really gained by doing things this way?

**Comment by backwardsEric** [comment]
I wasn't in on the original design and hadn't seen it used before, but it does let one use the same set of data to create an enum or arrays (of structures, strings ...)  as needed, and for most of where it's used in Angband, both an enum and one or more arrays are desired.  An alternative, creating a separate enum and separate array(s) has the risk of the two getting out of sync with each other.

The use of string pasting to generate function names does make it hard to figure out where that function is called (what calls build_circular()?; it's declared in generate.h and defined in generate.c, but searching for build_circular doesn't find a call or an assignment to a function pointer).  Depending on the situation, that could be mitigated a bit, while keeping the same idiom, by supplying the full name of the function as one of the macro parameters in the list*.h header and not generate it via string pasting.

**Comment by jl8e** [comment]
It's an incredibly clever way of working around C's lack of either hash tables or dynamic programming capabilities, and, like many incredibly clever programming techniques, is very hard to understand. (I consider my self to be fairly clever, and I have a solid, if rusty, grasp of C, and it still took me several tries to figure out WTF was up with the list headers.

Had I my druthers and a lot more free time, I'd replace it with either a two-step build process that runs a program to generate headers from the text files, or, more likely, find a usably-licensed hash table library to avoid the need for enums.

**Comment by NickMcConnell** [comment]
The main use of the list-xxx files is to allow more stuff to be in the text data files, and so be player-editable.  In particular, list-effects.h is read by the effect handlers and other things in the effect code, but is also used in initialisation (see grab_effect_data()) to allow the use of effect names in data files.  This (along with similar stuff done in list-projections.h and the project-xxx.c files) means that we can define spells in class.txt.

All this has moved the codebase away from the clear, well-commented code of late 2.x.y and early 3.x.y - so it's probably harder for people to make variants with major changes, but easier to adjust the game in small ways.

**Comment by NickMcConnell** [comment]
I'm going to close this because it's a path chosen some time ago for reasons I agree with.  If we had a label for "true, but...", I'd apply that 😁
