### ISSUE TITLE
list-effects: info for BREATH and LASH is NULL

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4843]
I was expecting "dam" for both like the other damaging effects.  Are the NULLs for those intentional?

**Comment by NickMcConnell** [comment]
You could have "dam" for those, but it makes no practical difference because they're purely monster attacks, and the info field is for spell books.

**Comment by backwardsEric** [comment]
Got it - so leave it as is until someone uses BREATH or LASH for a spell and complains that the damage summary isn't right.
