### ISSUE TITLE
Incorrect message text when hit by offscreen giant's boulder

### ISSUE THREAD

**Issue by RogueFanUK** [angband/angband#4847]
When you're hit by an offscreen thrown boulder from a giant you get the message:

"You hear a grunt of exertion. You are hit by something sharp!"

Last time I checked, boulders were not sharp.

**Comment by NickMcConnell** [comment]
That's because you're thinking of a nice weathered boulder sitting out on a moor somewhere, instead of a large piece of dungeon wall that's just been ripped out.
