### ISSUE TITLE
cannot find input file: `mk/sinclude.mk.in'

### ISSUE THREAD

**Issue by rikis-salazar** [angband/angband#4858]
Hey averyone,

Not sure this is the right place, feel free to send me hunting for answers at other possible places.

Long story short: every time I want to play a new character (b/c old one dies or wins the game), I usually just `fetch`, `pull`, and recompile. This time, I cannot do so as I am hit with the message:

```
config.status: error: cannot find input file: `mk/sinclude.mk.in'
```

The message is the same when I attempt to configure via

```
./configure --with-no-install
```

or 

```
./configure --with-no-install --enable-sdl2
```  

I ran `make clean` to see if anything changed but the issue persists. I am running Arch Linux and other than this, any previous issues while recompiling have been mostly nonexistent.

I am attaching the output of my configure call. Any help is appreciated.

[configure-output.txt](https://github.com/angband/angband/files/6642648/configure-output.txt)

**Comment by rikis-salazar** [comment]
Just wanted to add that a `git clone` into `/tmp` followed by `./autogen.sh`, `./configure --with-no-install --enable-sdl2`, and `make` was successful.

Still though, if possible I'd like to know how to _fix_ my "problem".

**Comment by rikis-salazar** [comment]
I'm sorry, I should have done this before posting:

After realizing that `sinclude.mk` was just _"an ugly hack"_, I deleted the file from the directory. Then I issued a `make distclean` followed by the `autogen...make` sequence. The compilation was successful this time.

Once again, apologies for not researching this further before I opened the issue.

**Comment by backwardsEric** [comment]
Thanks for reporting it though; now we'll know what to say when someone hits the same problem.  This was triggered by a recent update to the build system.  That left the configure script in your directory inconsistent with what's in the mk directory.  Rerunning autogen.sh would have fixed that, but a git fetch/pull alone would not.  Cloning into a new directory avoided the inconsistent configure script and worked.
