### ISSUE TITLE
@command inscriptions don't believe in the 'p'ray command

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4859]
As mentioned in [http://angband.oook.cz/forum/showthread.php?p=153789#post153789](url), in order to use a priest book with inscriptions, you have to inscribe it with @m1, even though the 'p' command still exists. This is true in both standard and roguelike.

I assume what's going on under the hood is that the 'real' command is 'm' for all spellcasters, and 'p' is just a keymap

**Comment by NickMcConnell** [comment]
Yes; proposed solution is remove the 'p' command altogether.

**Comment by NickMcConnell** [comment]
Done in 6e7f4e891
