### ISSUE TITLE
Object stack behaviour

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#4882]
"What about the problem with double stacks of items and using from second stack actually depleting the first? (you have 40 phase doors + 10 phase doors, you use a scroll from the pile of 10 and end up with 39+10 instead of 40+9)" - PowerWyrm

**Comment by backwardsEric** [comment]
I could not reproduce the 40 + 10, use one from the 10 stack, and get 39 + 10 in the current version.  What I did see is use one from the 40 stack, get a message about having 39 in that slot, but then a combining step happens that gives 40 + 9 (there is a recombining pack message).  Similarly on pickup, pickup 10, get message about 10 in slot x, then pickup 40 and get message about 40 in slot x + 1, but a rearrangement leaves 40 in slot x without a recombined pack message.

**Comment by backwardsEric** [comment]
Pull request #4884 has the effect of generating a "combine some items" message in the two cases I mentioned in the previous comment.  Is that good enough as feedback to the player for why there was a change in the numbers after the "You have x items" message displayed immediately after an item was used?

**Comment by NickMcConnell** [comment]
I think so.
