### ISSUE TITLE
Help file for Birth Options not working

### ISSUE THREAD

**Issue by RogueFanUK** [angband/angband#4892]
Hi, this should be simple to solve. On the birth options screen, hitting "?" to option the help gives the message "Cannot open 'option.txt'", probably as the file has been renamed to option.rst

**Comment by backwardsEric** [comment]
Thanks for reporting that.  From an earlier report, #4719 , the decision was made to remove '?' as an accepted key on the options screen.  That change is in the current development releases and will also be in the next full release.
