### ISSUE TITLE
Unable to get experience for casting Identify Rune spell if all Runes and Flavours set to known at birth

### ISSUE THREAD

**Issue by RogueFanUK** [angband/angband#4893]
This might be working as intended, but you can't cast this spell, ever, when those options are active as there's no possible valid targets ever. This might need a fix similar to the "Tap Magical Energy" so if you cancel out, the spell is still marked as tried and you get the XP for that.

(Also on a related note, should the same functionality be added to the "Remove Curse" spell to avoid having to wait till the RNG sees fit to spawn a cursed item you can cast it on to get the XP for the spell)

**Comment by NickMcConnell** [comment]
After a bit of thought, I'm going to say the current situation is the correct one.  There needs to be some punishment for taking those options...
