### ISSUE TITLE
Drop and rest should take a count

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4901]
They take a numerical input, so there's no reason not to let the user prefix it with the number they want.

In particular, I have the hard-wired reflex of "0dj" to try to drop all of a thing, because that used to work, but there's also a very common situation where I look at my inventory, see I have 10 too many of a thing, and try to use "010dj"

**Comment by NickMcConnell** [comment]
The '0' command now only asks for a number of repeats, and this is built into the structure of the command system.  Enabling this would require fairly significant surgery to that system, which is already quite intricate.  So I'm afraid the utility isn't worth the effort from my point of view, considering there is already a perfectly functional interface.
