### ISSUE TITLE
Typo in description for Great Wyrm of Chaos

### ISSUE THREAD

**Issue by fruviad** [angband/angband#4922]
https://github.com/angband/angband/blob/9d5133eaed1057ce2730db6e19573b2c9c481d6c/lib/gamedata/monster.txt#L13417

desc:A massive dragon of changing form.  As you watch, it appears first fair a$
desc: then foul.  Its body is twisted by chaotic forces as it strives to stay
desc: real.  Its very existence distorts the universe around it.

**Comment by NickMcConnell** [comment]
Thanks.
