### ISSUE TITLE
The "see abilities" command has no reason to exist

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4924]
There's a character info screen.

There's a separate, extensive, menu of character knowledge.

Either of these would be a better place to keep the info on race/class abilities than a standalone command.

**Comment by NickMcConnell** [comment]
So FAangband has (inherited from Oangband) a system of specialty abilities which the character can gain.  There is a command for learning these, and for displaying the ones you have.  The display command also shows race and class abilities, and so gives a handy snapshot of all the character's abilities, in a bit of detail.  Given the [current incarnation of FAangband](https://github.com/NickMcConnell/FirstAgeAngband) shares most of its codebase with V, it was really easy to port the ability display, and seemed like it was a nice thing to have.

The argument for having its own command is stronger in FA, where the same command is also used for learning.  So I guess the V display could be moved, probably to the knowledge menus.  Counter to that, I'd rather not introduce differences between the FA and V code unless it's needed (it's convenient to be able to exchange features), and the command isn't really doing any harm where it is.  Also, maybe some day V will have specialties.
