### ISSUE TITLE
Make release builds use NDEBUG

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#4948]
In line with ce004e45f, define NDEBUG for most builds.  The non-use of asserts and the streamlining of bitflags is likely to improve performance.  I think this should probably be done through a switch to configure, but am interested in other opinions.

**Comment by backwardsEric** [comment]
An alternative is to simply set CFLAGS when invoking configure.  There's several disadvantages to that:  it overrides the default CFLAGS that configure would set (currently "-g -O2", at least on Debian buster and building in additional behavior (more compiler options, stripping ...) is more cumbersome and error-prone.

Adding an option to configure doesn't help the other paths used for building (Makefile.osx, CMake), but that's expected.

I put up a pulll request, #4952 , which goes the route of adding an option to configure (only adds -DNDEBUG to CFLAGS currently).  For macOS builds, it overrides OPT when running Makefile.osx from release.yaml to set -DNDEBUG.
