### ISSUE TITLE
Sense surroundings fails to reveal wall tiles next to a rubble-filled hole.

### ISSUE THREAD

**Issue by jsv** [angband/angband#4958]
4.2.2 release, linux X11

When there is a shape like this:
```
###
#:#
#@#
```
the sense surroundings spell seems to stop at the rubble and doesn't reveal the wall above.

For example, this is a picture of the town in my current game, note the rubble-filled holes in the north and south:
![before_the_spell](https://user-images.githubusercontent.com/27961968/127448752-6316e359-e490-47a4-8583-4b807e0e1b3d.png)

Sense surroundings reveals the southern portion of the map, as it is sufficiently complex, but not the northern:
![after_the_spell](https://user-images.githubusercontent.com/27961968/127451041-572398ef-feac-4962-9d35-3faddeae54a8.png)

It seems that is because in the north there is nothing but wall right next to the rubble:
![actual_shape](https://user-images.githubusercontent.com/27961968/127448896-f9f4caf4-cb03-48e1-bf6f-3ab334193ba1.png)

**Comment by NickMcConnell** [comment]
This is actually working as designed.  Walls are only mapped by magic mapping if they are next to a non-wall, and for these purposes rubble counts as a wall.

**Comment by jsv** [comment]
Fair enough. It does look strange, though :)
