### ISSUE TITLE
The swap weapons macro no longer work if one of the weapons is also inscribed with @vN

### ISSUE THREAD

**Issue by jsv** [angband/angband#4959]
I see there is some general discussion about inscriptions so maybe this should belong there. But anyway.

4.2.2-263-ga032b1dc6

In my current game I have a randart spear inscribed with `@w0@v5=g`. In 4.2.2 the X macro works as usuall, but when I try using the current dev build, the spear is automatically put to the quiver and 'w0' can't get it from there.

**Comment by NickMcConnell** [comment]
Throwing weapons are put in the quiver if you give them an @v inscription.  This is not really a bug, more a limitation of the inscription feature.

**Comment by jsv** [comment]
Well, I suppose not inscribing it with @v does not have many drawbacks. It becomes slightly less convenient to select it for throwing, but that's all.
