### ISSUE TITLE
Suggestion: rename potions of Intellect.

### ISSUE THREAD

**Issue by jsv** [angband/angband#4960]
Well, it could be that people are already too accustomed to the name and it is not worth bothering. Still, I would use a name that doesn't share the first 6 letters with "Intelligence". Smarts, Acumen, Cunning, I don't know, English is not my mother tongue. But no other "gain 1, lose 1" potion is so easily confusable with pure "gain 1".

**Comment by NickMcConnell** [comment]
This is actually on old one that I was ignoring due to lack of interest; since you've shown interest I've reopened the original issue.  It will have to wait for 4.3 because changing object names breaks savefiles.
