### ISSUE TITLE
Browsing spell book should show descriptions by default

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4975]
As it is now, you browse a spell book, and have to hit ? to see the spell info. 

I don't see any good ui reason not to have the info displayed by default. 

Or, indeed, to justify turning off the info display, but I concede there may be one. If it's a screen size thing, I think defaulting to on would be a minor improvement for the vast majority of players.

**Comment by NickMcConnell** [comment]
Resolved by https://github.com/angband/angband/commit/9db67c1c93910ac8dd79dbd332db7f43137927b7
