### ISSUE TITLE
Shapechange mechanics poorly documented

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4976]
The description of bat form, at least, says "you cannot use objects". You also cannot cast spells. You also are never told how to end a shapechange; there is no dedicated command, and you're never told to use the spellcasting command. (And the "cast a spell, or just end shapechange" prompt is just clunky, requiring clearing a more prompt and answering a question.)

Edit: I see it's not quite how I described above, and all commands give the prompt. The prompt is still clunky. Among other things, it silently breaks macros.

Edit2: Not all commands prompt. 'm', 'w', 'r', 't', 'T', and 'q' do. 'E' does not, and I'm getting tired of checking every single one.

**Comment by MarbleDice** [comment]
A complete list of commands that cannot be used while shape changing: throw, fire, inscribe, uninscribe, take off, wield, drop, read, quaff, use, aim, zap, activate, refill, cast, study.

Interestingly, I just noticed you can only eat with the eat command directly, if you try to "use" food then you get blocked (since use also works for wands, rods, etc).

Removing the first message about "You cannot do this while in X form." should eliminate the more prompting issue. Is just the second message "Change back and act or return to normal?" descriptive enough?

**Comment by jl8e** [comment]
You can't eat, either. It says "you have no food to eat". Maybe this is different for other forms, but that's the case for bat.

The prompt is still awkward; it's a yes/no with a third option. The third option confuses the issue.

A much cleaner interface would be to have a single "end shapechange" command, whether dedicated or repurposing the cast command, and just have the other commands say "you cannot do this while shapechanged".

**Comment by MarbleDice** [comment]
Equip/inven/quiver are disabled when shape-shifted, so you can only eat from the ground. I assume this is to balance the druid spell rapid regeneration? But I'm not sure.

I wouldn't mind a separate, dedicated command to return to normal, but inconsistent treatment of cast vs all other commands is what made me propose this 3-way menu in the first place. (Previously cast would only let you return to normal y/n, all other commands would only let you return and act y/n). On druid, the most common reason I want to return to normal is cast spells to rebuff. But there are other forms that probably just want to return to normal and not act.

**Comment by jl8e** [comment]
> Equip/inven/quiver are disabled when shape-shifted, so you can only eat from the ground. I assume this is to balance the druid spell rapid regeneration? But I'm not sure.

It's a weird exception. You can't interact with items; except you can eat food off the ground. Can you drink potions off the ground? (No, but once you open the possibility, it's an obvious question.)

Also, telling the player they have nothing to eat, when they can look at their inventory and see food there, is confusing. Eat should either be available or fully disabled, just for consistency. The use case of eating food off the ground is really minor.

> I wouldn't mind a separate, dedicated command to return to normal, but inconsistent treatment of cast vs all other commands is what made me propose this 3-way menu in the first place. (Previously cast would only let you return to normal y/n, all other commands would only let you return and act y/n). On druid, the most common reason I want to return to normal is cast spells to rebuff. But there are other forms that probably just want to return to normal and not act.

IMO, the right interface is zero prompts. If you try to do an unavailable command, it tells you it's unavailable (and aborts any queued keystrokes). If you use the end shapechange command, your shapechange ends. (One could argue for a confirmation prompt for that. I'd do it if repurposing the cast command, but not if it's a new command.)

Also, when you shapechange, it should remind you how to end shapechange.

**Comment by NickMcConnell** [comment]
Shapechanged players being able to eat off the floor was a specifically asked for feature, IIRC - there were quite a lot of tweaks to it early on based on forum discussion.

Other variants have a dedicated shapechange command, but that usually goes with races that can shapechange at any time, and no ban on use of items.  The current solution seemed simpler here.

One way of making the whole thing cleaner would be to have a whole other command context for shapechanged players; one could also imagine doing this for players commanding a monster.  It might be overkill for this situation, though.

**Comment by NickMcConnell** [comment]
Setting this to 4.2 to at least look at it and document a bit better.

**Comment by jl8e** [comment]
> A complete list of commands that cannot be used while shape changing: throw, fire, inscribe, uninscribe, take off, wield, drop, read, quaff, use, aim, zap, activate, refill, cast, study.

Why inscribe and uninscribe? They have no actual game effects; they're just convenience commands. It's like forbidding perusing a book, or looking at your inventory.

**Comment by NickMcConnell** [comment]
True.

**Comment by MarbleDice** [comment]
I also find it weird you can pick up items (get and auto-pickup are both fine) but you can't drop them. If you grab a heavy item that triggers overburden, you'll have to change back to drop it. Is this to plug up some kind of residual loop hole? The only gotcha I'm aware of is eating from the ground - so if you could drop, you could just drop a food item, then eat it from the ground.

**Comment by NickMcConnell** [comment]
Pickup wasn't originally allowed either, but was included by popular demand (it's especially important for things like eagle form).  The idea is that your backpack is now part of your body, so how are you going to take things out of it?

**Comment by jl8e** [comment]
> Pickup wasn't originally allowed either, but was included by popular demand (it's especially important for things like eagle form). The idea is that your backpack is now part of your body, so how are you going to take things out of it?

And how could you put things into it?

Realism isn't a great justification in either direction here. Game balance is a better guide. The intent of shapechange seems to be that you get the benefits of the shape, but can't use stuff to make up for the drawbacks. Also, in most non-combat circumstances, the player can just exit the form, do a thing, and recast the spell.

So, does dropping objects give the player some meaningful advantage?

If you can eat food off the ground, does dropping food then eating it give the player some meaningful advantage?

Would eating food out of the inventory provide meaningful advantage, or is it just a convenience?

**Comment by NickMcConnell** [comment]
> > The idea is that your backpack is now part of your body, so how are you going to take things out of it?
> 
> And how could you put things into it?
Well, maybe you're just balancing those things on your head or something - I agree it's a bit thin, but it's a compromise.
> Realism isn't a great justification in either direction here. Game balance is a better guide.
I like to have both as far as possible.  While game balance is always going to win in the end, it needs to be within the context of trying to be immersive and maintain suspension of disbelief.
In Oangband (where the shapechange mechanic is loosely from) there is no such restriction, and I always felt that went against both game balance and realism.  I think shapechanging should feel like a temporary thing, so be used tactically for specific situations rather than just "Well, I'm a bear now", and reducing the player's access to their gear encourages this.
