### ISSUE TITLE
Generation statistics: X vault vs X vault (new)

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4979]
For the cave generation statistics, there's a separate bin for each room profile, so "X vault" and "X vault (new)" where X is either Lesser, Medium or Greater are distinguished.  For modified and moria levels, however, only the bin without the "(new)" will get counts: dun_profile.txt only lists the "X vault" forms and the decision whether to use "X vault (new)" rather than "X vault" is made after room_build() signals the start of building a room.

A fairly clean solution would be to include both the "X vault" and "X vault (new)" forms in dun_profile.txt for the "modified" and "moria" levels and have one take about half the current allocation while the other takes the rest.  The room profiles for those forms would have separate builder functions (one calling build_vault_type("X vault") the other calling build_vault_type("X vault (new)").  That would also mean that restricting classic levels to only have the "X vault" types happens in dun_profile.txt rather than being hardwired in the code.

**Comment by NickMcConnell** [comment]
This sounds like a good plan.  I'll assign it to Future for now, but don't let that stop you doing it if you feel like it 😄
