### ISSUE TITLE
Tap Unlife targets the space, not the monster

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4985]
This means that when it dies, your target remains where the critter was, and if you have "use old target" set, your attacks can go the wrong way.

**Comment by jl8e** [comment]
Correction: it seems to be inconsistent. I've had it leave a targeted space when killing a G, but not a s.

**Comment by jl8e** [comment]
OK, I think what's happening is that, if you kill the monster outright, the space becomes targeted. Otherwise, it's the monster.

**Comment by backwardsEric** [comment]
Would you prefer that Tap Unlife and Vampire Strike preserve what had been the target after doing their dirty work?

**Comment by jl8e** [comment]
No, I think the victim being the new target makes sense, since you're likely going to want to keep hammering the victim; it's the floating target on instadeath that's the problem.
