### ISSUE TITLE
Vampire Strike can't teleport you onto a door

### ISSUE THREAD

**Issue by jl8e** [angband/angband#4987]
Well, at least a broken door. I was fighting a critter, and the situation was

\#\#\#
'A@
\#\#\#

and was getting "Not enough room next to the Maia"

**Comment by NickMcConnell** [comment]
That's unsurprising - it looks for a floor with no monster, and open doors don't count as floors.

**Comment by NickMcConnell** [comment]
So I'm going to call this working as designed.
