### ISSUE TITLE
Smite Evil or Demon Bane and fists

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#4992]
While the spell descriptions and onset messages for Smite Evil and Demon Bane imply they affect all melee attacks, casting one with no weapon equipped and attacking a vulnerable creature doesn't seem to improve damage:

```
Your hands are imbued with holy force!
You miss the cave orc.
You punch the cave orc. <5x>
```

or

```
Your hands become a bane of demons!
You punch the lemure.
You miss the lemure.
You punch the lemure. <6x>
```

That matches with the code, which, in py_attack_real() only calls improve_attack_modifier() if obj is not NULL.

On a related note, if the code is modified to apply temporary slays or brands to fists, should fists also benefit from off-weapon slays or brands?

**Comment by jl8e** [comment]
> On a related note, if the code is modified to apply temporary slays or brands to fists, should fists also benefit from off-weapon slays or brands?

It makes sense.

**Comment by NickMcConnell** [comment]
This seems like a good idea, and agreed on off-weapon brands and slays applying to fists.

**Comment by backwardsEric** [comment]
Its probably easiest to drop the "if (obj)" in py_attack_real() but keeping what it brackets with appropriate values substituted when the weapon is NULL (1d1 in damage, zero weight, no bonus to hit or damage but what the player has).

Doing that would give fists the chance to do criticals.  Is that desirable?  If not, could skip the portion that includes the criticals when the weapon is NULL.

**Comment by NickMcConnell** [comment]
Agreed.  I'm not sure about criticals, but (especially comparing with FAangband unarmed combat) I'm inclined to say no.
