### ISSUE TITLE
object_learn_on_use(), death_knowledge(), and player_outfit() take a player argument and call object_flavor_aware() which uses the player global.

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5010]

**Comment by Tacolovers** [comment]
Death knowledge not working. One of my characters died, I then made a new one based on the one that died, and several of the uniques and other normal monsters had not been remembered. Even when I made new characters, and then said characters died, subsequent generational characters had no memory of monsters battled by ancestors. I have seen this error on the nightly builds of 4.2.3+

**Comment by backwardsEric** [comment]
That should be posted in its own issue; this one is highly unlikely to be have any impact on that.  Posting your lore.txt with that issue or in the post made on the 4.2.3 thread in the forum should help determine what's wrong with the monster recall.
