### ISSUE TITLE
lair level - long (perhaps infinite) loop to place second room in modified half

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5025]
At level 40 got a lair level which after hours hasn't finished generating.  The half with a 74 x 49 modified chunk has one greater vault but, so far, all attempts to add the second room have failed.

A handful of solutions come to mind (these aren't mutually exclusive; so it might be worth it to implement more than one):

1. For modified chunks used in lair levels, drop the requirement that there has to be two rooms.  That restriction is there so there'll be some place to place the player.  For lair levels, the cavern half can hold that spot so the restriction could be relaxed.
2. In the checks for greater vaults (likely huge rooms as well) include a check that the at least one of the left, top, right, or bottom edges of the vault is such that there'll be space for a small second room on that side.  The smallest dimension for a simple room is 5 (3 for floors; 2 for walls) and leaving a 2 grid buffer for tunneling would mean that vault left edge > 6 or vault top edge > 6 or vault right edge < chunk width - 7 or vault bottom edge < chunk height - 7.
3. Add a backstop check in modified_chunk() which will bail out after a certain number of attempts at generating rooms.

Moria levels also have the two room requirement (for the same reason as modified levels do) so (2) or (3) perhaps should be applied there as well.

**Comment by NickMcConnell** [comment]
I think I like the simplicity of 3 best.  2 would be OK too, although it might be hard to find the right smaller room.  1 would work, but would require modified_chunk() to know where it was being generated, so it would need another argument.
On balance I think 3, with maybe 2 as well, would be my vote.
