### ISSUE TITLE
update_stuff() takes a player argument and indirectly calls update_mon() (via update_monsters()) which uses the player global.

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5048]

**Comment by draconisPW** [comment]
This case is one of the few special cases that should not have been changed, and it can be explained by looking at what is done in a multiplayer version of the game:
- call update_stuff() for player p
- call update_monsters() for cave c corresponding to p->cave
- call update_mon() for every monster in that cave
- for **every player currently at that depth**, update monster view for that player (in my variant, this is a update_mon_aux() method, which takes a struct player *q parameter)
So in the end, the parameter in update_stuff() and update_mon()... is NOT the same player! Passing the player parameter to update_monsters() and then update_mon() breaks that logic.

**Comment by backwardsEric** [comment]
This pull request, #5195 , removes the player argument from update_monsters() and update_mon().  Since become_aware() seems to have a similar issue (I'm guessing in the multiplayer case you want that function to act on all players in sight of the mimic), I also removed the player argument that had been added to it in #4945 .

**Comment by NickMcConnell** [comment]
That's been pulled in now, and I'm just going to leave this as done in #4934 rather than mess with it any further.
