### ISSUE TITLE
Confusion blocks releasing command

### ISSUE THREAD

**Issue by jdholbrook81** [angband/angband#5056]
I have a necro on live right now v4.2.3. I controlled Saruman, but then Osse came and confused me. I cannot release my control of Saruman, it says too confused to read.

Can anything be done for my character? This is the furthest I've gotten and I have no way to escape Osse who is just pummeling me with spells while I'm stuck controlling Saruman.

**Comment by NickMcConnell** [comment]
This looks like a bug.  If you have any way of getting out of line-of-sight of Saruman, that should release the command.

**Comment by jdholbrook81** [comment]
Unfortunately Osse will probably kill me in the next turn, I'm at 112 HP. Are there any other options besides cheating? If not I understand. Just bummed to die to a bug on my furthest character.

**Comment by NickMcConnell** [comment]
You could download the savefile and send it to me, I should be able to fix it.  It will mean you can't play that character on live any more, I believe.

**Comment by jdholbrook81** [comment]
I appreciate the offer. I ended up taking a chance and survived!

**Comment by NickMcConnell** [comment]
Phew 😄 Thanks for spotting the bug.
