### ISSUE TITLE
Edited Color 0 ("Dark") does not refresh correctly on dungeon backgrounds, window borders

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5132]
Found in Angband 4.2.3, Windows version

Go to Option, Edit Colours, Modify colors, and edit Color 0 ("Dark")

Notice that the screen background changes to the edited Dark color--except only in spots: areas that correspond to background in the current dungeon remain black.

For instance, when I made color 0 ("Dark") bright red:

![ang2](https://user-images.githubusercontent.com/91744319/140845721-165f9398-d2ba-485f-82f8-e1bcdca69e97.jpg)

If you back out to the active game, you'll find that the dungeon background and the window borders remain black rather than your edited color:

![ang3](https://user-images.githubusercontent.com/91744319/140845878-6615c14e-38bc-4ec9-9d0d-9115e0b60f68.jpg)

CTRL+R to refresh the display in town, or going up or down stairs, will get back to the correct, edited dungeon background color, but the window borders will remain black:

![ang4](https://user-images.githubusercontent.com/91744319/140846041-07637571-5ab6-4f7d-9dcb-2522e341ca51.jpg)

CTRL+R again will revert the dungeon background back to black

![ang5](https://user-images.githubusercontent.com/91744319/140846402-5b0267ac-2c76-4fdb-952c-acda7401975f.jpg)

as will going in and out of the Options menu with =; also, the incorrect black map background will continue to show through in the Options menu:

![ang6](https://user-images.githubusercontent.com/91744319/140846837-31a5e090-2ec7-44da-9e64-c9210ecb64d6.jpg)

**Comment by backwardsEric** [comment]
I believe this happens because the windows front end uses RGB(0, 0, 0) as the clearing color in some instances (Term_xtra_win_clear() and Term_xtra_wipe_win()) but uses the first entry in the color table when drawing text with the default background.  The front end on the Mac made a different choice, and always uses RGB(0, 0, 0).

Doing the same thing for Windows as the Mac is one way to resolve that, but then one can't configure the background color.  Another way would be to use the first entry in the color table for all the clearing (perhaps making an exception for the case when the clearing is done to make way for drawing a graphic tile).

**Comment by NickMcConnell** [comment]
Re the comment on the pull request, probably should do the same for the other front ends, but it can stay as Future.

**Comment by backwardsEric** [comment]
WIth the above pull requests merged in, I think this is resolved for everything except for the NDS front end.  I haven't looked at that to know if it makes similar assumptions about COLOUR_DARK being black or that COLOUR_DARK wouldn't be changed by the player.

**Comment by NickMcConnell** [comment]
I thought that was pretty much it.  I haven't looked at the NDS port either; it's a fairly niche thing, but on the other hand people using it might have strong feelings about this sort of modification.  I'll leave this open at least for a bit, and maybe ping the author.

**Comment by timschumi** [comment]
#5147 resolves the issue for NDS, after which fore- and background color changes are applied immediately and everywhere.

**Comment by NickMcConnell** [comment]
OK, I believe this is done now.
