### ISSUE TITLE
Color Dump with black Color 0 ("Dark") doesn't override edited Color 0 when loaded

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5138]
Found in Angband 4.2.3, Windows version

1) Start a new character
2) Press =cb to select Options, Edit Colours, Dump colors
3) Save under some filename; the default PLAYER.prf is fine
4) Dump the colors again under a different filename just to be sure
5) Press c to select Modify colors
6) Press R to change the background to red
7) Press ESC and then a to select Load a user pref file
8) Load one or both of your color dumps
-- The background color remains red, even though it was black when you dumped your colors.

(When Color 0 is 0:0:0, it isn't being dumped to the .prf.)

![ang](https://user-images.githubusercontent.com/91744319/141196703-992b9e60-9940-49cc-bfae-c8c75918ce7d.jpg)

**Comment by backwardsEric** [comment]
Thank you for reporting these issues.  With regards to this one and, as a partial solution to #5132 , is anything lost by preventing the end user from editing color 0 ("Dark")?  Would doing so hurt accessibility in some way or prevent Angband from better fitting into a "light theme" desktop?  Would it hurt a variant that uses "Dark" as a color for monsters or objects?

**Comment by smbhax** [comment]
I can't answer for users with accessibility needs, or variant authors; I was just messing around with it because I wanted to run the game in a Umoria Windows 10 console color scheme, ie black and white, with 12:12:12 for the dark value and 204:204:204 for the light value. Since uncovering the quirks with it, I've settled for just using 0:0:0 and 192:192:192, which work well enough for my purpose.

After getting that bright red background color while running quick tests, I *had* been thinking that being able to run with a mauve background once in a while, for instance, would be fun, but I can't say I have an actual need for it. ^_^ Likewise, possibilities of exploring inverted schemes with light backgrounds and dark foregrounds were intriguing, but not particularly necessary as far as I know; in other words, I think people could have some additional fun with the game if the color support was robust in that way, but I don't know of anyone who actually requires that support just now. (I know fairly little about roguelikes in general, mind you!)
