### ISSUE TITLE
angband.live - vi keys "dig a tunnel southeast" command keys blocked by web browser

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5162]
When playing Angband through a web browser via https://angband.live and using the vi keys option, the key commands necessary to dig southeast are intercepted for other functions by major web browsers (Firefox, Chrome), preventing the user from digging southeast in the game.

Tested using Angband 4.2.3-141-g335036713 on angband.live, Angband nightly game, in Firefox 94.0.2 (64-bit) on Windows 10.

1) Using the Firefox browser, start a character in an Angband nightly game on https://angband.live
2) Press = and then a to access the game's User interface options
3) Set the top option, "use the roguelike command keyset," to "yes"
4) Stand with a tunnel wall to your southeast 
5) Press ^N to dig southeast
==> Nothing happens in the game window; Firefox pops a new browser window open
6) In the angband.live browser window, press ^T to use the "dig a tunnel" command (this would prompt you to press a directional input to choose which direction to dig)
==> Nothing happens in the game window; Firefox pops a new tab open

A workaround in the game is to set a movement delay (=m and then a delay factor in ms, like 10); with that set, you can dig in diagonal directions using the two surrounding cardinal direction keys, so ^J^L simultaneously or in quick succession would dig southeast. This does make movement inputs a little delayed/sloppy, and may not be obvious to some users.

**Comment by jl8e** [comment]
You ought to be able to work around this by using the ^ command to send your control keys in two parts, or the + (alter grid) command.

I don't think there's much else Angband can do about it.

**Comment by smbhax** [comment]
Ooh! Those do indeed both do the trick. I had looked through the command list but failed to grasp what those two were about. Thanks!

So yeah, aside from somehow making it more obvious for a noob like me, this can be closed. Hm maybe I can close it with this button here, I'll give that a shot.
