### ISSUE TITLE
Custom background color doesn't cover all areas in angband.live subwindows

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5174]
Version: Angband "nightly" on angband.live; currently at 4.2.3-129-gcfe38c796

If you edit the game's background color, your custom background color affects angband.live's optional subwindow displays, but only in areas around or enclosed by letters--the open background areas of the subwindows remain black.

- On angband.live, start a game session in Angband (nightly version), with "subwindow right cols," "subwindow right split," and "subwindow bottom rows" numbers to create those subwindow areas (I use 40, 30, 8 for them, respectively, with Droid Sans Mono size 20 font on my 1080p display)
- Once in a dungeon, press = for Options
- Press w for "Subwindow setup"
- Set something in your three subwindows (I have Term-1 monster recall, object recall, Term-2 monster list, Term-3 messages)
- ESC back to the dungeon display and move around/fight until the subwindows are populated with letters
- Press = for Options
- Press c for "Edit colours (advanced)"
- Press c for "Modify colors"
- Press Shift+r ("R") to change the background color to red
--> The background of the main game display is red, but in the subwindows, only the blocks around or enclosed by letters are red--the wider background areas remain black
![angl_colors](https://user-images.githubusercontent.com/91744319/145267533-75b2d458-be45-4cb2-afc5-7fe9c355825b.jpg)

I noticed this after messing with it in angband.live due to it coming up as a player request on the forum: http://angband.oook.cz/forum/showpost.php?p=154693&postcount=12

**Comment by backwardsEric** [comment]
I'm not able to reproduce this with the standalone game running the GCU front end:  there the background color fills each subwindow, with a one character wide black bar separating the subwindows.  Perhaps the change to Angband's GCU front end, https://github.com/angband/angband/commit/f9a714934e988873909f9b892ad3fb5445b9405d#diff-c4c05d8f78104b190eb5a934834b8f836e1ab4e51885217c0ff76cc30dcb9bc5 , wasn't included in the nightly version of Angband on angband.live, or it's something else particular to how angband.live converts the output from the GCU front end to what's displayed through a web browser.

**Comment by backwardsEric** [comment]
That sounds fine - especially since leaving this one here will let Nick respond since he likely put the nightly on angband.live and knows what changes were made when that was done.

**Comment by smbhax** [comment]
Sounds good; I've re-opened it on the angband.live git at the link in my previous comment, adding a new comment there with the information you gave.

**Comment by NickMcConnell** [comment]
angband.live should have been just using the latest (ie 4.2.3-149-gcfe38c796), so I don't know what the problem is - unless Gwarl's done some special thing.  In any case, I've pulled in the latest PRs and updated angband.live, so it should now be running 4.2.3-157-g9f25c10fb.

**Comment by smbhax** [comment]
Still happening on angband.live (now at 4.2.3-157-g9f25c10fb).

**Comment by smbhax** [comment]
> I tried to look at the term.js dependency for angband.live. The one directly listed by GitHub has a readme saying it's unmaintained, and I couldn't tell from the code how it was implementing the xterm compatibility (though that is likely just me since I don't know anything about Javascript). The project listed as a successor to term.js, https://github.com/xtermjs/xterm.js , has an implementation that's clearer to dig into. There, the color changing in browser/renderer/BaseRenderLayer.ts (https://github.com/xtermjs/xterm.js/blob/master/src/browser/renderer/BaseRenderLayer.ts ), looks suspect: the setColors() method updates the character atlas member but doesn't appear to do anything with the _colors member which is used for the clearing color in _clearAll().

And a commenter on the angband.live git issue for this just pointed out https://github.com/OwenGHB/angband-webclient/issues/52#issuecomment-992928842 that it is related to an existing open issue they have involving looking into switching their terminal from term to xterm: https://github.com/OwenGHB/angband-webclient/issues/51 . I've passed your comment on term and xterm along.

**Comment by peterdresslar** [comment]
Just for the record I am assuming xterm will break more things than it fixes! But, can try it anyway

**Comment by NickMcConnell** [comment]
If I'm reading this correctly, this is not an Angband issue, so can be closed - let me know if I'm wrong.
