### ISSUE TITLE
Liberate proprietary data

### ISSUE THREAD

**Issue by throwaway1037** [angband/angband#5176]
Please may the proprietary data in Angband be released under a [libre](https://freedomdefined.org) license so that they can be packaged in a 100% libre system like [Parabola](https://parabola.nu)?

At the moment, Parabola has to [remove this data](https://git.parabola.nu/abslibre.git/tree/libre/angband/libre.patch) which is an unnecessary hassle.

**Comment by Zireael07** [comment]
That's some VERY specific definition of libre, as it seems from the patch not even CC qualifies...?

**Comment by throwaway1037** [comment]
@Zireael07 Creative Commons is not a license, but an organisation that publishes licenses. Some of their licenses are libre, and some are not.

As such, the data released under a libre CC license is fine and is not removed by Parabola.

**Comment by dherrerace** [comment]
I've seen this being discussed on other closed issues #3020. Personally, I would love that all the assets provided from this repository could be distributed using libre licenses, it would make things a lot easier for packagers, but its probable that those assets wouldn't even exist as an option for the community if there was not a non-libre option to distribute this game.

I'm currently planning to package this game for Fedora,

**Comment by throwaway1037** [comment]
> assets 

The term ["assets"](https://gnu.org/philosophy/words-to-avoid.html#Assets) when used to refer to published works is a horrible propaganda term; it degrades the work and presumes its only measure of worth is that of how much money it can make.
I'd suggest the term "published works" as an unbiased replacement term. 

> Personally, I would love that all the assets provided from this repository could be distributed using libre licenses, it would make things a lot easier for packagers 

Increased practicality is just a bonus; the real issue here is [freedom](https://freedomdefined.org); freedom is an inalienable right and all published works should be libre. 

> but its probable that those assets wouldn't even exist as an option for the community if there was not a non-libre option to distribute this game. 

Better that unethical, proprietary published works were never written, than exist and restrict people.
Doing zero is better than doing a negative, which is the harm that proprietary published works do, as they restrict people and limit freedom. 

> I'm currently planning to package this game for Fedora 

Thank you for making free software and data available to people! 

> they have strict licensing guidelines 

Hardly.
Fedora is not a libre distro, as it contains proprietary software and published works.
I'd recommend [Parabola](https://parabola.nu) instead, which is 100% libre.
There is also a Freed-ora project which seeks to maintain an entirely libre fork of Fedora.
Unfortunately, it's not as active as it could be at the moment, but it would be great if you could help maintain it. 

I initially would have suggested copying the Angband package from Parabola and converting it to work with Fedora, because it's already 100% libre, otherwise you're just duplicating work and wasting time and effort, but it turns out you looked closer than the Parabola packager did because you spotted even more proprietary files that were missed!
Thank you, well done! 

I'll report the Adam Bolt 16×16 tiles to Parabola. 

Which Windows library header files are you referring to? 

> Project owners 

The term ["owner"](https://gnu.org/philosophy/words-to-avoid.html#CopyrightOwner) is confusing because people hold the rights to published works; they don't "own" them.
I'd suggest the terms "project authors" or "project maintainers" instead as unbiased replacement terms. 

> content 

The term ["content"](https://gnu.org/philosophy/words-to-avoid.html#Content) is propaganda because it degrades the work and treats it just as a placeholder for people to buy and forget about before buying the next published work, instead of something to be admired on its artistic and other merits.
I'd suggest the term "published work" instead as an unbiased replacement term. 

> creator 

The term ["creator"](https://gnu.org/philosophy/words-to-avoid.html#Creator) is propaganda because it gives authors an artificially high moral status with which it appears natural for them to restrict others.
I'd suggest the terms "athor" or "composer" or "artist" instead as unbiased replacement terms because some terms fit certain types of published works better, eg. "author of a novel" is a correct usage, but "composer of a novel" wouldn't work, because you'd only really use the word "compose" to refer to musical works, eg. "composer of a symphony" 

> content creators have the right to license their creations as they see fit 

All published works should respect the freedom of their users.
People should not have the right to release published works under proprietary licenses, as that is unethical, just as nobody should have the right to keep slaves. 

> open source 

The "open source" initiative is a watered-down, weaker version of the [free software movement](https://fsf.org); see [this article](https://gnu.org/philosophy/open-source-misses-the-point.html) for why "open source" misses the point of free software.
I'd suggest saying "free software" instead because freedom matters. 

> would help a lot to open source distribution package maintainers if the restricted assets could be stored on a separate repository 

I agree; all proprietary published works should be clearly marked and separated into a separate repo.
This is already the standard for many packages, and it would improved Angband if this were the case. 

Better still, the proprietary published works should be deleted. 

Even better still, the proprietary published works should be liberated, which is the reason I initially opened this issue.

**Comment by dherrerace** [comment]
First, I want to say that English is not my first language, so I appreciate you for taking the time to check my use of words from a FOSS perspective.

On the technical parts of the conversation:

> Which Windows library header files are you referring to?

Sorry, the problem was not in the headers, but some binary libraries in the /src/win/dll and /src/win/lib folder that don't apply to get distributed. They won't end up getting bundled in the binary installable package, but if you care about the sources that you are distributing (on SRPMs in my case), then it may concern you.

**Comment by throwaway1037** [comment]
@dherrerace, you're welcome!
:)

The term ["FOSS"](https://gnu.org/words-to-avoid.html) is biased because it's meant to be neutral between free software and "open source" software, yet "free software" is split up, but "open source software" is clearly visible.
If you want to be neutral, then "FLOSS" is the better term because it unambiguously refers to freedom with "free/libre" as contiguous initials.
However, I'd recommend saying "free software" and supporting freedom instead.

> Sorry, the problem was not in the headers...

Not to worry, it's better news that there are no proprietary source files than there are prebuilt binaries.

Thank you for being so diligent with checking the licenses.

**Comment by NickMcConnell** [comment]
A quick survey of Angband users indicates no appetite for changes to the way it is packaged.  Individual behaviour is of course up to the individual; we're not in the business of telling people what to do.

**Comment by throwaway1037** [comment]
@NickMcConnell, nevertheless, please may the proprietary data be liberated?

**Comment by NickMcConnell** [comment]
The data I believe you are referring to (sounds and tiles) was provided to the Angband project by the individuals who made it, under their conditions.  It is packaged with Angband for convenience of its players.  I would regard any "liberation" of this data to be up to its originators.

**Comment by throwaway1037** [comment]
> to be up to its originators

That's the unfortunate situation of society at the moment: published works can be proprietary and are not all libre, instead we have to beg and plead and grovel for freedom from the authors.

Please may the authors be reached out to and asked if they would liberate their works?
I am not part of the Angband community, and I fear such a request may not be taken kindly from a newcomer.

**Comment by NickMcConnell** [comment]
You have very definite views of the definitions of things like freedom, and a certainty about those views, which I do not share.  So I am not going to represent those views to people who have generously provided the fruits of their labours to the project.  This is my last word on this (closed) issue.

**Comment by throwaway1037** [comment]
@NickMcConnell thank you for your time.
