### ISSUE TITLE
Android. Bug with persistent levels, prepare_next_level

### ISSUE THREAD

**Issue by Cuboideb** [angband/angband#5183]
Hi, I'm getting a recurrent error, reported by google. Line 1408 in generate.c

for (i = 0; i < p->cave->obj_max; i++) {

I don't have more information than this.

**Comment by backwardsEric** [comment]
Has the Android version incorporated this post 4.2.3 change, https://github.com/angband/angband/commit/bf573fb6dce7a94d4c577263b852798b268d94d4#diff-6d9a7271930e59d160aea9f36ae41b3f29afeaaba7c156b201f3d46353593bc7 ?  That's my best guess for the cause:  leaving the single combat arena could leave a version of the known level in the chunk list causing trouble later, usually when exiting another single combat arena at the same depth.

**Comment by Cuboideb** [comment]
Yes, those lines are included. I'll let you know if it repeats again.

**Comment by Cuboideb** [comment]
I'm closing this issue. Perphaps it was a device running a previous version.
