### ISSUE TITLE
When saving in Single Combat, record player's location in the original level

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5184]
As it is in 4.2.3, that information isn't saved.  If the player exits the game and starts again from the savefile, the player's location upon successfully leaving Single Combat is either near the killed monster or anywhere, if something appropriate could not be found.

Marking this with the 4.3 milestone since fixing it would likely break savefile compatibility (the cleanest solution probably would be to have the extra information stored with the other chunk list details).  Perhaps implementing it by saving a fake monster in the monster list at the player's location could avoid that (older versions would see a monster with an unknown race and ignore it; newer versions would use that monster's record to get the position), but that's likely overly convoluted and doesn't fit well with the current logic for saving and restoring the monsters.

**Comment by backwardsEric** [comment]
Your solution seems like it would backward compatible for savefiles (old versions wouldn't do anything with the "old grid" coordinates; new versions could have a fallback if (0, 0) from an old savefile shows up for those coordinates) so it could be implemented in 4.2 rather than wait for 4.3.

**Comment by NickMcConnell** [comment]
Should be done in cf0d5908f

**Comment by backwardsEric** [comment]
Look's good to me.  I'd be tempted to add an assert, something like assert(square_ispassable(cave, p->old_grid) && square_monster(cave, p->old_grid) <= 0), when old_grid is used upon return from the arena.
