### ISSUE TITLE
Unused 3rd argument to TV() in list-tvals.h

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5196]
The third argument to the TV() macro in list-tvals.h is not used in the two places list-tvals.h is included, obj-properties.h and obj-tval.c.  Should it be removed entirely?  Looks like it was introduced 5 years ago for a change to obj-randart.c but then that use was removed fairly soon thereafter.

**Comment by NickMcConnell** [comment]
I don't see why not.  Anything with any original relationship to the randart code is likely to contain some sort of temporary hack or other...
