### ISSUE TITLE
Technically incorrect message when wielding incompatible launcher and ammo

### ISSUE THREAD

**Issue by RogueFanUK** [angband/angband#5215]
For example, if you're wielding a Short Bow but only have Iron Shots in your quiver, on hitting "f" the game says "You have no ammunition to fire". I would suggest changing to "You have no suitable ammunition to fire" or something similar. You have ammunition so the current statement is technically incorrect.

**Comment by NickMcConnell** [comment]
This issue is technically correct 😄

**Comment by RogueFanUK** [comment]
Thanks! I know the things I flag are relatively trivial, but hopefully my reports are not unwelcomed.

**Comment by NickMcConnell** [comment]
Depends how I'm feeling on the day 😉
