### ISSUE TITLE
Cygwin xterm-256color terminal: frame around game window not affected by game's background color

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5225]
Version 4.2.3-193-g75174c4c3-dirty, in xterm-256color Cygwin terminal

Follow-up to issue 5210: the black frame between subwindows is gone! = D But running in a black terminal window, there's still a black frame around the outside of the window when a custom background color is set in-game:

- Run the game full-screen in curses with 3 subwindows (-mgcu -- -n4)
- In-game, with the background color at its default black, press =wccR to change color 0, the background color, to bright red.

== A black frame is evident around the window: an area not affected by the change to color 0. (In my display, the frame is narrower at the top and left than on the other sides.)

The color of this area appears to be set by the terminal emulator's background color. If it simply isn't possible to extend the game's control to this area, then this is not an Angband problem. (The workaround would be setting the terminal emulator's background color to match Angband's background color, via the terminal emulator's options.)

![ang_frame](https://user-images.githubusercontent.com/91744319/147397736-ca38bfaf-b33b-49ac-ac09-262e1740d9b4.jpg)

**Comment by backwardsEric** [comment]
On Linux (Debian bullseye) with either the xfce4-terminal or xterm running in 256-color mode, I see thin black borders on all 4 sides - probably a pixel or two wide for both though the xfce4-terminal's border appears narrower.

In principle, the last change to the GCU front end changes the background color on the entire area that ncurses makes available to the application (it calls wbkgd() on stdscr).  I can't say that I know curses well, so I don't know if there's something more that the GCU front end could do.

For your thicker borders on the right and bottom, is it possible that those correspond to the areas for scroll bars?  If so, you could disable the scrollbars.  The border width and color are also likely controllable.  From "xterm --help" on Linux, the command line option "-b number" sets the border width to be number, the "-bd color" sets the border color, and "+sb" disables display of a scrollbar.  There should be equivalent X resources if you want to configure the terminal with those, but I didn't bother to look up the way to set those.

**Comment by smbhax** [comment]
Aha! Yes, these are terminal program things: the single-pixel border all around can be turned off with a config file setting for Cygwin's mintty terminal ("border=0"), and the larger border on the right and bottom is just space that isn't quite large enough to fill with another column or row of characters in my chosen font size (I had already turned off scroll bars). So, not an Angband thing, and I'm closing it. : )
