### ISSUE TITLE
"Save this keymap?" prompt after creating a keymap is either misleading or confusing

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5236]
In 4.2.3-199-geec078290-dirty, Cygwin curses:

1. From gameplay, press =wd to get to the "Create a keymap" dialogue
2. Create a keymap
When you press "=" to finish the keymap, a prompt appears: "Save this keymap? [y/n]"
3. Press "y"
"Keymap added" appears. At this point the keymap can be used in-game.
4. Back out to gameplay and press CTRL+x to save and quit
5. Load the game and character
6. Press the key to which you'd assigned the keymap

=== The keymap does not work--it was not actually saved to a file--at least not to one that restored it for the user; I don't know if it saved it somewhere else--which the user may have assumed would have been the case, since they confirmed when prompted to "save" it, and when you "save" something it usually comes back when you return, or is at least readily available in some obvious way.

Possibly it should say something like "Keep this keymap?" instead of "Save this keymap?", and then, in addition to saying "Keymap added," it should say something like "Be sure to save your added keymaps to a file (b) if you want to keep them for later sessions."

(Maybe even tell them the various .prf names they can save to for multi-user auto-re-use, like "user" or the class names.)

**Comment by NickMcConnell** [comment]
Seems sensible.
