### ISSUE TITLE
archive directory and setgid installs

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5270]
With the setgid installs, it's possible (depending on how the system's files are laid out and where Angband is installed) that the archive directory ends up on a different file system than where the user files are stored.  That would break using file_move() (i.e. rename()) to shift things back and forth between the archive directory and the directory with the user's files.

Is that an argument to not store the archive directory in the central location for setgid installs and instead place it in ~/.angband/Angband? Or should file_archive() be prepared to move stuff between filesystems when necessary?  Which is better probably depends on what benefits the files in the archive directory get from being in the central location.  Those seem to be:

- extra protections against cheating of various forms because of the permissions on the centralized files
- the possibility, dependent on how the permissions are set or what can be shown in game (i.e. how the game presents the high score information), to facilitate sharing of information between the different users

Since files in the archive directory are moved back and forth from the user directory (where the user has free rein), the extra cheating protections from the centralized install may not matter.

**Comment by NickMcConnell** [comment]
I feel like having it in ~/.angband/Angband is probably better.  I'm really not too fussed about cheating protections, and currently it's only randart files that are archived, so I don't think that would have any effect on scores (unless I'm missing something).

**Comment by backwardsEric** [comment]
Sounds good to me.  I asked in case there was plans for something else which would use the archive directory and would benefit more than the randart file does from being in the shared directory.

**Comment by backwardsEric** [comment]
Given the logic in init_file_paths(), changing this will affect both the --with-no-install and --with-setgid configurations.  If the player doesn't manually move the randart files from the old location (lib/archive in a --with-no-install build) to the new one, the game'll regenerate the randart file.  That will work fine if the character was started in 4.2.3 (looks like there hasn't been a change to randart generation since the change to the screening for activations in July 2021), but, for character started earlier than that, the regenerated file wouldn't match what the character started with.

Is that enough of a concern to postpone  dealing with this till there's savefile breaking changes?

**Comment by NickMcConnell** [comment]
I don't think so - it's not technically a savefile break, it's unlikely to affect many (or any) people, and if anyone is affected there are plenty of places they can ask for help.
