### ISSUE TITLE
Suggestion: make roguelike keys able to browse menus

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5298]
Version: 4.2.3-249-gbb7ea2dca-dirty
Environment: Curses front end, Cygwin, Windows 11

Currently, when using the roguelike command keyset (=aa), the hjklyubn keys can be used to navigate the dungeon and a few, but not most, game menus; for most menus, the user has to revert to using the cursor keys, particularly for scrolling through options, somewhat defeating the point of providing the roguelike keys in the first place; such menus include:

- (i) inventory
- (e) equipment
- (~) knowledge (including submenus (~a) objects, (~b) runes, (~d) ego items, (~e) monsters, (~f) features, (~g) traps (and (l) is used for "toggle lighting" in those last two), (~h) shapechange effects, (~i-p) store/home displays--although roguelike keys DO work in actual shops, where they are skipped in the menu item assignments, (~r) character history, and (~s) equippable comparison
- Not the main (=) Options menu, but some Options submenus including (=a) User interface options, (=i) Item ignoring options, and (={) Auto-inscription setup (duplicate of the Knowledge - known objects menu)
- (^p) Message recall (scrolling)
- Character creation: select race
- (r) read
- (q) quaff
- (d) drop
- (I) inspect
- (T) unwield
- (w) wield
- (g) get
- (^D) ignore
- ({) inscribe
- (}) uninscribe

And possibly also (wasn't able to test these as I didn't have enough items or entries):
- (e) eat 
- (a/A/z/Z) activate/zap
- (v) throw
- (~c) artifacts
- (~q) hall of fame (scrolling)

Note that shops specifically accommodate the roguelike keyset by skipping the roguelike movement keys when assigning alphabetical shortcut letters to items in the shop, allowing the roguelike keyset's j and k buttons to scroll through the menu items; most other menus in the game that assign alphabetical shortcut letters to their item list do NOT skip the roguelike keys, however--even the knowledge menu re-creation of the shop menus neglects to do this--so if the list is long enough to get to j, trying to scroll the list with the roguelike keys may instead activate one of the menu items.

Shops, omitting the roguelike key letters, expand available alphabetical shortcut letters by supplementing them, if necessary, with numbers. The lengthy User interface menu (=a) does not skip the roguelike letters, but still runs out of letters for assigning to menu items, and supplements this by assigning capital letters rather than numbers.

The shop menu skips roguelike letters in its menu assignments, and assigned numbers:
![shop](https://user-images.githubusercontent.com/91744319/153913606-501ca49a-915f-4b9c-9bf0-a5c8092b7d5e.jpg)

The user interface menu does not skip roguelike letters, and assigns uppercase letters:
![interface](https://user-images.githubusercontent.com/91744319/153913665-bc08c701-a3f8-4dbf-a02d-528f06b0f65a.jpg)

**Comment by NickMcConnell** [comment]
Fixed in 8f823a77f
