### ISSUE TITLE
Available commands list shows Ctrl shortcuts as uppercase letters (Ctrl+Shift)

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5299]
Version: 4.2.3-249-gbb7ea2dca-dirty
Environment: Curses front end, Cygwin, Windows 11

In the Available commands lists (?a) for both original and roguelike keysets, commands activated while holding a Ctrl key are shown with uppercase letters--but uppercase letters are also used in the list to denote non-Ctrl commands executed while holding a Shift key, and these Ctrl key commands require NOT holding Shift.

For instance, in the original keyset, "locate player on map" is listed as "L," to indicate that it is executed by pressing Shift+l--pressing just "l" would do "Look around"--while "Center Map" is listed as "^L," suggesting that it is activated with Ctrl+Shift+l--but in fact, only Ctrl+l is meant, as pressing Ctrl+Shift+l does nothing.

(Ctrl+Shift+l does nothing in the Curses front end in Cygwin; in the Windows graphical front end, it behaves like Ctrl+l.)

This probably applies to all the ^ keys listed, as they are all listed with uppercase letters only.

Possibly there is some long-standing convention--beyond Angband and its variants--of only listing Ctrl key commands as uppercase letters, with which I am unfamiliar; uppercase letters in this instance may be regarded as more legible, for instance. But the command list will primarily be referred to by newer players, who may be unfamiliar with any such convention. (For that matter, some may not understand that "^" denotes the Ctrl key, and that is not explained in the help file.)

**Comment by NickMcConnell** [comment]
This looks like it's done.  Is it done?

**Comment by NickMcConnell** [comment]
OK, that's a yes, some weird refresh thing happening to me.
