### ISSUE TITLE
Suggestion: change "life" to "experience" in XP drain "You feel your life draining away!" status message

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5300]
Version: 4.2.3-249-gbb7ea2dca-dirty
Environment: Curses front end, Cygwin, Windows 11

When a grape jelly hits you with its "lower experience" attack, it lowers your current Experience Points, but the status message says "You feel your life draining away!"

I can see "life" also equating with your XP count, but it more directly and usually equates to the character's Hit Points--so this status message is confusing.

Video, complete with my momentary noob confusion: https://www.youtube.com/watch?v=HZ7iTr41Rsg&t=1141s

Something like "You feel your experience draining away!" would be clearer, and less easily confused for meaning something else in the context of the game.

![drain](https://user-images.githubusercontent.com/91744319/153979491-6e78a4fd-419b-402f-acbe-b53352bf5a54.jpg)

**Comment by bart9h** [comment]
There are other parts of the game that refer to experience as "life".

I remember at least one: the "Potion of Restore Life Levels".

**Comment by smbhax** [comment]
> I agree with you, it's a bit confusing for beginners.
> 
> And there are other parts of the game that refer to experience as "life". I remember at least one: the "Potion of Restore Life Levels".

Good point! Although with consumables, they at least have a description the player can read that could potentially clarify things. Although, in many cases consumable descriptions are merely self-defining and seemingly intentionally obscure; the Potion of Heroism or something like that says just something like "Grants and extends heroism for [formula] turns," without telling you what the heck "heroism" is--a bunch of the potions you find early on follow that pattern, anyway.

Obviously the designers wanted a bit of poetic license and mystery, the question is when does it go too far and just become downright misleading. In this case, it's not perhaps a critical problem as an observant player will probably figure it out eventually--but is it called for in the first place? Were this a new game on which I was a QA tester, for instance, I would have submitted this issue as an outright bug rather than a suggestion, because it could quite easily be an actual error in which the wrong text string--one meant for a life drain attack--had mistakenly been assigned to the XP drain status effect.

**Comment by NickMcConnell** [comment]
I think this should stay as is:

1. It's something that the player learns as soon as they encounter it, really;
2. I think it's fairly clear that this is a special type of attack, in which case the player would be expecting something beyond just lost HP, which any damaging attack does.

**Comment by smbhax** [comment]
> I think this should stay as is:
> 
>     1. It's something that the player learns as soon as they encounter it, really;
> 
>     2. I think it's fairly clear that this is a special type of attack, in which case the player would be expecting something beyond just lost HP, which any damaging attack does.

Fair enough, although I think one of my first thoughts was that it was going to lower my max HP.
