### ISSUE TITLE
unIDed wands on monster which is outside of my vision

### ISSUE THREAD

**Issue by igroglaz** [angband/angband#5319]
I've met it in Tangaria (PWMA), but it's the same in V:

https://youtu.be/ERsK0PawKnA?t=1827 (timecode)
used unIDed wands on monster which is outside of my vision
but wand become IDed
though I didn't see what it did (confused stationary mob and slowed it)
it shouldn't ID I suppose in such case

My char has torch equipped and and his vision is 1 radius. So I stood away from monster (but in borders of my screen) and used wand not by target, but by direction. Mob is outside of my vision, 2 tiles away.

So.. as it is outside of the light radius: player DO NOT see whats happening in the darkness. How come zapping wand make it IDed if you didn't see the result?

p.s.
PowerWyrm: "in V it's even worse since hitting a mob with a wand while blind not only IDs the wand, but also gives no message at all..."

**Comment by backwardsEric** [comment]
Do you have an opinion whether all wands should only be identified if able to see the monster or thing affected or if there is some subset (I'm thinking the wands that produce a bolt of some element and perhaps the wands that produce a ball of some element) that seeing what shoots from the wand's tip is sufficient to see identify the wand?

**Comment by igroglaz** [comment]
I agree with idea about IDing bolt and balls wands even if player doesn't see the result. Not sure about Stinking Cloud, though it also works as a 'BALL'.. btw, maybe Stinking Cloud should be a STRIKE with radius 2? Seems legit. I think in Moria they worked like this, though I don't remember precisely.
