### ISSUE TITLE
discussions?

### ISSUE THREAD

**Issue by user1095108** [angband/angband#5328]
I believe we should rekindle the fires of long-forgotten flame wars of old and have a discussions forum, which is now possible on github.

**Comment by backwardsEric** [comment]
There is http://angband.oook.cz/forum/index.php which has been the hub for discussions of Angband for quite some time.  That said, some rearrangement of Angband's internet presence, see https://github.com/angband/angband/issues/4869 and http://angband.oook.cz/forum/showthread.php?t=10165 , may happen.

**Comment by user1095108** [comment]
of course I know of that forum, but of late I've been seeing angband-related material go offline, not to mention that the forum here would be development-oriented, I suppose.

**Comment by NickMcConnell** [comment]
Currently discussions happen on oook, angband.live, discord, [angband.live forum](https://forum.angband.live/), and there's even still the odd post on rec.games.roguelike.angband.  I feel like further fragmentation is unnecessary 😄

**Comment by user1095108** [comment]
The law of entropy assures us all of the these shall at some time disappear. It is not the fragmentation of forums you need to worry about, but fragmentation of your development time. There are issues in the issues section, that are not issues at all, but complaints about a feature being under or overpowered. Such would fit nicely into a discussions section. I'd personally enjoy a flame war of old, but be as it may.

**Comment by NickMcConnell** [comment]
I'm not opposing flame wars, just their location...
