### ISSUE TITLE
Bolt effect animation with unlighted target - information leak?

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5336]
At least with the Mac front end (current nightly source, custom compiled), using a wand or rod with a bolt effect on an unlighted target shows the propagation of the bolt and the point of impact - revealing the location of the unlighted target.  Should it only show the propagation of the bolt in grids that are lighted and not show the rest?

**Comment by NickMcConnell** [comment]
AFAIK that's how it has always been.  I guess the questions is whether that's how the game world behaves or not.

**Comment by backwardsEric** [comment]
I don't have strong opinion about how it should behave.  It does give a player an additional tactical option for probing something out of sight.

**Comment by jl8e** [comment]
If we're talking realism, one can presumably see the bolt even if it doesn't give enough light for long enough to make anything else out.

If we're talking game balance, eh, whatever.

**Comment by backwardsEric** [comment]
That argument, "see the bolt even if it doesn't give enough light for long enough to make anything else out", is reasonable and isn't inconsistent with how the identification for the wands and rods are working (for the elemental balls and bolts, the wand or rod is identified when it is used and the player isn't blind; the ones that apply a status effect only identify if the effect on a target is seen, but those still could be emitting something which is visible out beyond the grids that are lit).
