### ISSUE TITLE
Spell messages interrupt keymaps

### ISSUE THREAD

**Issue by jl8e** [angband/angband#5360]
If you try to put two spells on a keymap, if the first one displays a message, the second one doesn't happen.

I was testing this because of something on the Android thread, and tested it with my current necromancer, chaining see invisible and darkness.

If you get the "your eyes feel very sensitive!" message, darkness doesn't get cast. If you already have the spell going, there's no message, and darkness does get cast.

I assume what happens is that the message is flushing the input buffer. (Or disturbing the player, maybe?) There's no good reason to IMO; people sometimes want to chain spells (or other actions) in keymaps, and they're aware of the potential risk of using multiple turns.

But if it is done, it should be done consistently.

**Comment by backwardsEric** [comment]
In that case, see invisible starts a timed effect on the player causing disturb() to be called which flushes the input buffer.  Could disable disturb() if a keymap is being executed and the keymap isn't executing a command that can autorepeat (like resting, disabling, opening ...).

**Comment by backwardsEric** [comment]
Another approach would be to not disturb the player for the increase of a timed effect if it's the direct result of a spell or item use.

**Comment by jl8e** [comment]
That would make a fair amount of sense. Normally it's part of a single player action, so there's nothing to be disturbed from. (And I don't think fast-typing running ahead of the game is a concern in this day and age.) If it's part of a keymap, the player expects things to continue past the spell.

A trickier question would be detect spells. I've certainly chained several on a keymap in the past, but some things are more potentially disturbing than others. (doors/stairs: no, treasure: no, traps: probably not, but there's a case for it, monsters: yes)

**Comment by backwardsEric** [comment]
For changes in player timed effects, I'd favor using the approach that it would not disturb if the player is the source of the change (so when coming from an effect handler, the origin is SRC_PLAYER) and, if the effect is generated by the player using an item, the player is aware of the item's effects.  There's the question of what to do about the blinding/stunning side effects of destruction and earthquakes.  I would favor leaving those as they are now:  disturbing the player if they impose a new status.

For the detections, the detection of map features and objects currently do not disturb from what I saw in the code.  The detection of traps also does not disturb, unless the trap is on a chest.  That exception seems odd to me, but I haven't dug into the history of it to see if there's a specific reason for that.  The detection of monsters disturbs if the monster goes from seen to unseen or unseen to seen and the disturb_near option is set.
