### ISSUE TITLE
Ignored items are no longer being ignored 

### ISSUE THREAD

**Issue by LeslieCarr** [angband/angband#5401]
Hi! All of a sudden, my ignored items are no longer being ignored - 
Here's my save file (I added a .txt so github would upload it) in case that helps! I'm running 4.2.4 on OSX 12.4 on an M1
[Idron.txt](https://github.com/angband/angband/files/8987973/Idron.txt)

**Comment by backwardsEric** [comment]
Had you pressed 'K'?  That toggles on and off the unignoring mode when using the original keyset.  When that mode is on, you'll see "Unignoring" in the status line.  Pressing 'K' again will turn it off.

**Comment by NickMcConnell** [comment]
Nice catch - opening the savefile shows "Unignoring" is indeed on.

**Comment by LeslieCarr** [comment]
Thank you! I must have accidentally hit 'K' and not realized that was a thing!
