### ISSUE TITLE
Have more timed effect special cases specified by timed_effect.txt

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5434]
Currently (post 4.2.4), there's special case handling for these timed effects in player-timed.c:

1. TMD_FOOD has a different lower bound.  In the parsing, it has additional logic to scale the grade maximums by z_info->food_value and set the PY_FOOD_* values.
2. TMD_PARALYZED isn't allowed to accumulate.
3. TMD_POISONED is protected against by TMD_OPP_POIS.
4. TMD_SCRAMBLE scrambles player's stats on onset and unscrambles them upon lapsing.
5. TMD_SPRINT triggers TMD_SLOW when it lapses.

Propose adding or changing directives to player_timed.txt (and the necessary parsing and backend logic to support them in player-timed.c) so more of those special cases are specified from player_timed.txt without explicit references in player-timed.c.  The proposed new directives would be:

lower-bound:value
Optional.  Sets value as the lower bound for the timed effect rather than zero.  Value has to be greater than zero (don't see any need to allow negative minimums).

on-begin-effect:name:subtype (if needed):radius (if needed):parameter (if needed)
Optional.  The named effect will be triggered when the timed effect begins.  May be specified multiple times to allow multiple effects to be triggered.

on-end-effect:name:subtype (if needed):radius (if needed):parameter (if needed)
Optional.  The named effect will be triggered when the timed effect lapses.  May be specified multiple times to allow multiple effects to be triggered.

effect-yx:yrange:xrange
Optional.  Sets the y and x range for the last effect given by on-begin-effect or on-end-effect.  Would trigger an error if this timed effect has not had an on-begin-effect or on-end-effect directive yet.

effect-dice:dice string
Optional.  Sets the dice string for the last effect given by on-begin-effect or on-end-effect.  Would trigger an error if this timed effect has not had an on-begin-effect or on-end-effect directive yet.

effect-expr:dice expression
Optional.  Sets an expression to be used in the dice string for the last effect given by on-begin-effect or on-end-effect.  Would trigger an error if this timed effect has not had an on-begin-effect or on-end-effect directive yet.

effect-msg:string
Optional.  Sets a message to be used with the last effect given by on-begin-effect or on-end-effect.  Would trigger an error if this timed effect has not had an on-begin-effect or on-end-effect directive yet.

The proposed changed directive would be "fail:".  Allow it to be specified multiple times so there could be multiple causes of failure.  Allow '5' for the first parameter which would indicate that the second parameter is a timed effect name that would cause the effect to fail.  That timed effect name could be a forward or self reference.  Could add post-parsing processing step so any timed effect with a resist directive would be automatically added as a fail condition to any timed effects that fail because of that non-timed resist.

While the current code wouldn't use it, it might be useful to allow trigger an effect on transitions between grades.  If implemented, an additional directive (grade-up-effect?  would there be a need for a grade-down-effect as well?) that would add the effect to the most recently specified grade seems convenient.  Would require additional specification for how effect-yx, effect-dice, effect-expr, and effect-msg could be applied to the grade transition effects.

Those proposals don't resolve the scaling of the food values, and the setting of PY_FOOD_*.

**Comment by NickMcConnell** [comment]
This sounds like a good idea, and it seems like you've come up with pretty much a minimal set of changes.  TMD_FOOD is different in spirit to the others anyway, so it's not surprising that it's harder to make behave (not to say we should stop trying, though).
