### ISSUE TITLE
Messaging for resisted side effects of some high damage projections

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5435]
In 4.2.*, the messages for the side effects from high damage projections of strong light ("You are dazzled."), dark ("You feel unsure of yourself in the darkness." and "Darkness penetrates your mind."), and sound ("The noise disorients you.") will be displayed even if player_inc_timed() to apply the side effect fails.  That may have contributed to sffp wondering about the "disorients you" message here, http://angband.oook.cz/ladder-show.php?id=25008 (according the dump the character has pConf).

Could check the return value for player_inc_timed() before displaying the side effect message but then the message ordering may be confusing:  want "disorients you" to appear before the messages generated in player_inc_timed().  Alternatively, could add an explicit call to player_inc_check() before displaying the message or say it's fine as is.

**Comment by NickMcConnell** [comment]
I think a call to player_inc_check() first is best.

**Comment by backwardsEric** [comment]
The side effects from darkness aren't resisted (somehow missed that the check argument to player_inc_timed() is false for those when reviewing the code) so those messages are fine.
