### ISSUE TITLE
Drop and Ignore share "d" shortcut in item details window: can't use Ignore from shortcut

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5436]
Running Angband 4.2.4-97-42b7b1f9b1f0099070013a6b1b542de9ccb5e1bb, compiled in Cygwin from the latest code.

1) Press i to go to Inventory
2) Select an inventory item
3) Look at the list of available actions and their shortcuts at the upper right of the item details window

==> Both Drop and Ignore have the shortcut "d"; pressing "d" drops the item; there doesn't seem to be a way to Ignore it from this menu now.

(Workaround: eXamine the item while it is on the ground, so there is no Drop action and "d" works for Ignore.)

![ignore](https://user-images.githubusercontent.com/91744319/180739679-98683821-d40f-4436-b205-4e82fb7899d4.jpg)

**Comment by backwardsEric** [comment]
This happens with the rogue-like keyset and is a regression introduced by https://github.com/angband/angband/pull/5409 .  Also affects testing for the inscription to prompt before ignoring an item with the rogue-like keyset (before the pull request "!D" would work for that; now it is "!d" which overlaps with the inscription to prompt before dropping).
