### ISSUE TITLE
Move Arkenstone to top of item list if unidentified

### ISSUE THREAD

**Issue by AvdN** [angband/angband#5444]
In Angband 4.2.4 (on macOS) I drank a potion of Enlightenment at lvl 98. There was the first power ring at the top of the item list window. After picking up Vilya I just happen to explore to another unidentified item Arkenstone. Which on closer examination (after backing off from actually seeing it) is not at the top of the item list.
Maybe this is because you don't really seem to have to identify it, or maybe because there is only one Arkenstone. _It would nicer if such an important item is at the top of the list like the powerring was._ 
I assume that this would be the same for the Phial and Star.

**Comment by backwardsEric** [comment]
The current ordering does put artifacts at the top, but the character has to "touch" them first, usually by having been in the same grid as the object.  Objects with unknown kinds come next, and as it's implemented currently, that'll favor artifact rings and amulets (like Vilya) and unknown kinds of ordinary amulets, mushrooms, potions, rings, rods, scrolls, staves, and wands; all other kinds are assumed to be known by the character from the start of the game.  The ordering after that depends on the object kind, and lights like the Arkenstone have a disadvantage:  all weapons and armor will come before any light.

A way to reproduce this with the debugging commands is:

1. Create a new character.
2. Use the 'c' debugging command to get a scroll of teleportation and a potion of enlightenment.  Pick them up and descend to the dungeon.
3. Use the 'C' debugging command to create all artifacts.
4. Read the scroll of teleportation and then quaff the potion of enlightenment.

In the resulting object list when I tried it, the items from the end of the list are "a flask of oil", "an Arkenstone", "a Star", "a Phial", and "Power Dragon Scale Mail" (i.e. Bladeturner).
