### ISSUE TITLE
More control of ego effects or use activation instead?

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5451]
The parsing of ego types currently (4.2.*) does not allow some of the control over added effects that's present for object kinds, curses, and activations.  Namely, there's no provision for specifying the y and x parameters of an effect (effect-yx directive) or binding an expression (expr directive).  Also, there's no control over the message when an ego item is activated.

Could add the parsing so ego types have the same level control over the added effects, but would it be better to have them link to an activation instead?  That would reduce the amount of code needed, and when changes are made to how activations are handled, it wouldn't have to be done in more than one place.  The drawbacks are that there likely would have to be additional data with each activation to signal whether it was appropriate for inclusion on a random artifact (and likely would want that mechanism to be general if we are using activations in multiple contexts) and that, for someone reading/editing the data files, there's the extra level of indirection (have to look up the activation in activation.txt) to see what's happening if an ego item is activated.

Also could use activations to replace the effect chains for object kinds and curses, again with the aim to have one place where effect chains for objects are configured.  If that was done, would want to do some renaming (for curses and most object kinds the effect chain isn't invoked by activation) to avoid confusion.  Is "effect_chain"/"effect-chain" good enough?

**Comment by NickMcConnell** [comment]
FAangband uses activations on ego items, but then it actually has some ego items which can be activated, whereas Angband currently has none.  I'd be inclined to use activations, and I don't think it's likely that activations suitable for ego items would be unsuitable for randarts.

I'm inclined to leave effect chains in object.txt and curse.txt, because of the extra level of indirection you mention.
