### ISSUE TITLE
Character Permanently Afraid. There is no cure.

### ISSUE THREAD

**Issue by davidwilcox** [angband/angband#5455]
See the screenshot. It's been about 1000 game turns. And I've drunk a potion of boldness. There's no indication on the status bar on the bottom that my character is afraid. But I can't cure the fear. 

Save is here:
https://drive.google.com/file/d/1ecg3X9WFf4LoyfMIs7Lwhbm7t7npdw7g/view?usp=sharing

![Capture](https://user-images.githubusercontent.com/253677/184062766-9bb33680-c65b-4e9f-b6b3-fb8763a5f4b7.PNG)

**Comment by davidwilcox** [comment]
It was a dumb ring of escaping.

**Comment by SimonGPort** [comment]
lol I had the same problem. Thank you
