### ISSUE TITLE
monster_base's spell_flags field never modified

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5458]
From the history for monster_base.txt, the capability for specifying spell flags for a base was added 12 years ago and taken out 8 years ago.  struct monster_base still retains a spell_flags field which is initialized to be empty and merged into the spell flags for each race that uses the base, but those spell flags can't be modified from the data files.  Remove the field and the references to it?

**Comment by NickMcConnell** [comment]
Seems reasonable.
