### ISSUE TITLE
Restriction by monster glyph in gen-monster.c will break if the glyph is outside the range of a char

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5465]
In mon_restrict(), there's the use of a "%c" format to convert the d_char field (of type wchar_t) of struct monster-base.  In mon_select(), there's the use of strchr() (which works with bytes, not wide or multibyte characters) to look for what's in the d_char field of struct monster_base within the string generated by mon_restrict().

Could change the base_d_char private variable in gen-monster.c to be a wchar_t, using a value of zero to signal there's no restriction based on the glyph.  That would avoid the issue.

**Comment by NickMcConnell** [comment]
That seems like a sensible idea.
