### ISSUE TITLE
Do y'all REALLY think Tolkien would like to see "gender neutrality" in a game that is based on his creations???

### ISSUE THREAD

**Issue by JoePeter17** [angband/angband#5474]
If someone is going to make a game based on middle-earth, they should _at least_ honor it's creator.

**Comment by jl8e** [comment]
1: He'd probably hate the game in its entirety, seeing as it makes a hash of his carefully-constructed world
2: Who cares what he'd think?
3: Of all the liberties the game takes with Tolkien, why are you particularly focussed on this one?
4: I have no idea what you're referring to, anyway
