### ISSUE TITLE
Shift + keypad direction doesn't trigger running on some systems

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5488]
According to this post, http://angband.oook.cz/forum/showpost.php?p=159315&postcount=138 , shift + numeric keypad 6 on a AZERTY keyboard is converted to {SK}[Right] by the X11 front end.  That does not trigger the default keymap to run right.  Consider augmenting the default keymaps so {SK}[Right] (and the equivalents for End, Down, PageDown, Left, Home, Up, and PageUp) trigger running.

**Comment by NickMcConnell** [comment]
I seem to recall this may be an issue with whether NumLock is pressed or not

**Comment by backwardsEric** [comment]
In this post, http://angband.oook.cz/forum/showpost.php?p=159312&postcount=136 , the reporter said it didn't work regardless of whether NumLock was on.  The later post with the output of the key log didn't indicate whether that was done with or without NumLock

**Comment by animal-waves** [comment]
I confirm that this behavior is present regardless of the Numlock state.
I also tested if the 'initial' Numlock state (ie. enabled before launching the game or not) made a difference but it does not.

Feel free to ask if you need more info or testing!
