### ISSUE TITLE
Feature Request: Flavor for Runes

### ISSUE THREAD

**Issue by dagit** [angband/angband#5502]
I don't know if this is the right place to make this request or if it's already been discussed.

As someone that plays with flavor text always on, I noticed that runes could really benefit from some flavor text at least while still unidentified. I also saw that newer versions of angband have utf8 support. Maybe the flavor text for runes could pull glyphs from a runic alphabet? If the alphabet is large enough maybe it's one glyph per rune. If the alphabet isn't large enough, then maybe the flavors could work like scroll flavors. You could have 1-3 glyphs per rune separated by spaces?

**Comment by backwardsEric** [comment]
The hurdle I see for using a runic alphabet is knowing whether the font the front-end uses has the necessary glyphs (there could be hook functions for the front ends so the core could query whether a font has something useful for a particular Unicode code point to work around that and substitute a widely available fallback character if a rune is unavailable).  That's especially true for the Windows, SDL, and SDL2 front ends which use the .fon files in lib/fonts, and those likely only have support for what's in ISO-Latin 1/code page 437.  An extra complication is that some front ends allow use of a different font for each of the terminals.

**Comment by dagit** [comment]
Yeah, that does sound complicated. I looked through Latin-1 and there's maybe a few symbols that would work well but not really enough to be an alphabet. So maybe using a runic alphabet is too hard at the moment.

That said, I still like the idea of having something. How would you feel about using elder futhark as the alphabet? (See here https://en.wikipedia.org/wiki/Runes#Elder_Futhark_(2nd_to_8th_centuries) ). Except for now sticking to the things in the "transliteration" column? Based on my understanding those appear to all be latin-1 except for the third to last (ingwaz). And for that one, I think we could just make a different substitution such as this character ¤ (hex A4)?

At first it would just seem like they are normal english characters, but it could make it easier to later switch over to their futhark counterparts as they have glyph support for them? Like maybe having it as a UI option where toggling it on uses the futhark codepoints and toggling it off (the default) uses the latin-1 transliterations?

**Comment by backwardsEric** [comment]
Leaving aside the concerns about the font details, you might describe how your proposal would look like (with a fully unidentified, partially unidentified, fully identified item what would be seen when inspecting the item; would it affect the one-line item summary in an inventory or object list?).  When I saw your original post, I jumped to thinking about the descriptions shown for flavored items (potions, scrolls, wands, staves, amulets, rings, and rods) when inspecting them, but from your last post, I think I misread what you intended.

**Comment by NickMcConnell** [comment]
I'm going to take the line here that "rune" is just a convenient way of describing an object property, rather than actually meaning that there are runes on the objects that cause it to have the property.  So I'm saying no.
