### ISSUE TITLE
Shop shortcut keys are confusing

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5541]
(Roguelike keyset)

If you hit ? for help in a shop, you are told of the following commands:

x - examines selected item
p - purchases selected item
d - gives an item

The reality is much more complicated. What actually happens:

- With an item highlighted but not (?) "selected":
 x - prompts you for which item to "Examine"
 p - prompts you for which item to "Purchase"
 g - prompts you for which item to "Purchase"
 d - prompts you for which item to "Give"
 s - prompts you for which item to "Give"
 left arrow - exits shop
 right arrow - selects highlighted item
 enter - selects highlighted item
 key matching item ID - selects highlighted item

- With an item selected:
 x - "Examines" selected item
 p - nothing
 d - "Buy"
 o - "Buy one"

This is confusing. The help is very incomplete. There are undocumented redundant keys. There are inconsistent keys: why is "d" being used for "Give" (or even the old "Sell"--I can at least understand why "s" is still supported; wait, is "d" "Donate" (not shown)?) in one case, and "Buy" in another? Shouldn't "g" be "Give"? Why is "g" being used for Purchase? ("Get"? But "Give" is the "g" word the interface uses.) Shouldn't "b" be "Buy"? Why is "Buy" being used as well as "Purchase"? Why does "p" do nothing with an item selected?

I know that at least some of these ("s" for "Sell") are legacy controls--but even so, for this new-ish player, the current shop controls are very confusing.

**Comment by backwardsEric** [comment]
I'd assumed that 'g' and 'd' were there so muscle memory for the commands outside the store was useful:  get item ('g' in both keysets) becomes purchase in the store and drop item ('d' in both keysets) becomes sell in the store.  It's also the case that interacting with the character's home and interacting with another store is handled by the same code and 'g' and 'd' are more intuitive for working with the character's home.

From the commit history for ui-store.c, it looks like the commands when an item was selected used to (~8 years ago) more closely match the normal commands but a change converted 'p' to 'd', and that somehow stuck.  Changing that back to 'p' to make the commands more consistent seems wise.  It may also be possible to get 'g' to work for buying in that context for more consistency.

As for the documentation, it could very briefly mention the other controls though the standard menu interaction (item selection via label, cursor keys, and enter) is the same as elsewhere in the game.
