### ISSUE TITLE
Reading last Enchant scroll changes target item's key assignment

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5543]
Latest source (a bit dirty), SDL2 front end, compiled in MSYS2 under Windows 11

1) Have in Inventory a SINGLE Enchant Weapon To-Hit scroll, and an easily enchantable weapon (do not have multiples of the scroll in inventory, I think the bug does not occur then)
2) Note the weapon's assigned inventory key (in my case it was "v")
3) Press r to read, and select the Enchant Weapon To-Hit scroll
== In the selection list of enchantable items that appears, the weapon now has an inventory key assignment one higher than it was just prior (in my case, "u")

This makes it tricky to target an item with the scroll, as the target key suddenly changes from the one you'd seen. If you use ESC to back out of using the enchantment, retaining the scroll, the item's assigned key goes back to the prior one ("v" for me).

Especially given that the scroll isn't actually consumed until after the target is selected, the assigned target key should probably NOT change at all during the process of choosing the target.

I haven't had a chance to test, but possibly this also occurs with other item-targeting scrolls such as `*Enchant Weapon*`, Enchant Weapon To-Dam, and Identify Rune.

Video: https://www.youtube.com/watch?v=abDcOJWnlLo&t=9125s

"Brangolf" target item with "v" key assignment prior to reading scroll:

![001](https://user-images.githubusercontent.com/91744319/199106322-f9855876-bcd2-4428-8fd5-9fa870603156.jpg)

"Brangolf" target item with "u" key assignment during scroll's target selection:

![002](https://user-images.githubusercontent.com/91744319/199106418-e83b8997-d9fa-4d18-9c81-defcf56c9727.jpg)

**Comment by backwardsEric** [comment]
#5548 handles this when both the scroll and weapon are in the pack.  If they are both on the floor, there'll still be  changes to the item index:  deduction of the scroll used is still done before use in that case because some items (scrolls of teleport level and runes of protection) won't be accessible after use when used from the floor.
