### ISSUE TITLE
Sidebar equipment display distorts/disappears when tile size > 1

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5551]
MSYS2-compiled SDL2 front end, latest code, somewhat dirty. Also reproduced in Windows front end, 4.2.4. Windows 11.

1) In the Gervais or Shockbolt Dark tilesets (did not test the others), set tile size to 1x1 (in Windows front end, use "Options > Graphics > Tile Multiplier" rather than "Window > Increase/Decrease Tile Height/Width")
2) Have either the main window sidebar display showing, or the "Display player > compact" subwindow (Term 7 by default in Windows front end, I think)--or both
== You can see your @'s equipment summarized in item tiles in the sidebar/subwindow between the rows for AU and STR
3) Set tile size to 2x2
== The equipment display tiles in the sidebar/subwindow start to distort, and disappear or shift out of view
4) Set tile size to 4x4
== Sidebar/subwindow equipment tile display distortion continues and may disappear entirely
5) Set tile size to 8x8
== At this point, the item display may be entirely or nearly entirely invisible in the sidebar/subwindow. In SDL2, it may still be visible, bleeding down the side of the subwindow. (See screenshots below.)

If you start the game at a tile size larger than 1x1, the tile equipment display is not shown--until you lower the tile size to 1x1. Ideally, the equipment tiles would remain fully visible in the sidebar/subwindow no matter their scale in the main window.

Screenshots of the MSYS2-compiled SDL2 front end, Windows 11, Gervais tileset; "Display player > compact" subwindow on the far left, main window sidebar to its right:

Tile size 1x1:
![001](https://user-images.githubusercontent.com/91744319/200654710-81bd895b-3f53-4960-bebb-f6a823f4e71e.jpg)

Tile size 2x2:
![002](https://user-images.githubusercontent.com/91744319/200654723-ad834879-2475-4d60-bba0-297914d1fbc9.jpg)

Tile size 4x4:
![003](https://user-images.githubusercontent.com/91744319/200654726-4e88920d-1aa3-41a8-bbcc-abe554dc2a55.jpg)

Tile size 8x8:
![004](https://user-images.githubusercontent.com/91744319/200654731-7d142fc9-5138-43c4-a884-fab75cb57f1f.jpg)

**Comment by backwardsEric** [comment]
Currently, there's no real provision for having tiles appear at different sizes at the same time.  That's part of the reason the equipment tiles aren't normally shown unless the tile multipliers are 1 x 1 (would have to display them at the chosen multiplier which may or may not fit). It would be relatively easy to display the ASCII representations for the objects (though those wouldn't account for user display preferences) if the tile set multipliers are different than 1 x 1.

As for the distortions you see when changing the multipliers, it looks like you're getting the upper left corner for the tile (whatever fits in space for a single character).  If the tile multiplier change triggered a full update of the sidebar or compact player subwindow, that would avoid that (though, with the current implementation, the equipment slot indicators would disappear unless the tile set multipliers changed to 1 x 1).

In a related issue, the equipment indicators in the knowledge menu's equippable comparison don't look right when tiles are used and the tile multipliers are different than 1 x 1.

**Comment by smbhax** [comment]
Gosh, there are also character tiles next to the listings in the monster window at 1x1. ; ) They disappear and their column is removed at larger tile multipliers.

**Comment by backwardsEric** [comment]
#5556 gets rid of the distortion:  the equipment display will always be cleared if going from a 1 x 1 tile multiplier to something else.
