### ISSUE TITLE
SDL2 front end crashes bringing up fonts menu with over 32 fonts in font dir

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5583]
MSYS2-compiled SDL2 front end, latest code, all standard.

1) Have over 32 fonts in my \lib\fonts directory
2) Run Angband
3) Select "Menu > Angband > Font > Name" from the top menu.
==> Angband crashes with the message shown in the screenshot below:

![Untitled-1 copy](https://user-images.githubusercontent.com/91744319/207998601-c215fa59-f3ba-4170-92b8-fe9edcc0811a.jpg)

~~~~
Microsoft Visual C++ Runtime Library

Assertion failed!

Program: C:\msys64\home\smbhax\angband\angband.exe
File: main-sdl2.c
Line: 1744

Expression: bank-> number < bank-> size
~~~~~

**Comment by backwardsEric** [comment]
#5588 should take care of the crash if there are more than 32 usable fonts in lib/fonts.  There's still a cap (32 currently; set by MAX_BUTTONS in main-sdl2.c) on the number of fonts the SDL2 front end will make available in the Font menu.
