### ISSUE TITLE
SDL2: toggling tiles on/off resets visuals (aka DOS symbols)

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5584]
MSYS2-compiled SDL2 front end, latest code, in Windows 11.

1) In Angband, use Menu > Angband > Font > Name to switch to a ttf font with the DOS symbols in it (https://www.dafont.com/perfect-dos-vga-437.font)
2) Press =p to get to "Load a user pref file" and enter "font-ibm.prf"
3) ESC back out to the dungeon view and you'll see DOS checkerboard blocks in place of # for dungeon walls
4) use Menu > Angband > Tiles > Set > David Gervais' tiles
5) use Menu > Angband > Tiles > Set > None
==> The normal "#" and other symbols have replaced the DOS symbols you'd loaded from font-ibm.prf

**Comment by smbhax** [comment]
Ah I see, but if tiles have to change the symbols because that's how they work, ook.

**Comment by backwardsEric** [comment]
Yes, changing the tileset causes a reload of the assignments for how things are displayed.  To have your changes stick when reverting back to no tiles, you'd want to have the preferences so they'd automatically would be loaded when font.prf is loaded.  An easy way to do that if you're using the SDL2 front end on Windows is to copy font-ibm.prf from lib/customize to font-sdl2.prf in lib/user within where you built Angband for Windows.

**Comment by smbhax** [comment]
Oh hey yeah that sure works. : ) I don't think that trick is exactly mentioned in the manual.
