### ISSUE TITLE
SDL2: Accented letters display incorrectly when using DOS-style font (with font-ibm.prf)

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5586]
Perhaps similar to issue #5498.

In MSYS2-compiled SDL2 front end, Windows 11, latest Angband code.

1) Have a character with an item or memorized lore of an item with accented letters in the name--I had "a Long Bow of Lothlórien"

2) Switch to a DOS-style font, such as Bm437_Wyse700b-27.FON from "The Ultimate Oldschool PC Font Pack v2.2" at https://int10h.org/oldschool-pc-fonts/download/

3) Press "=p" to bring up the "load a user prf" dialogue

4) Enter "font-ibm.prf" to switch to the DOS-style game character set

==> The accented letter is now displaying in a garbled fashion--see screenshots below (ó became ≤)

![image](https://user-images.githubusercontent.com/91744319/208108132-1cde79b2-c543-4b36-b013-99ddb1b40b52.png)

![dos](https://user-images.githubusercontent.com/91744319/208109789-48a72944-3b18-4d25-9b54-84e1d2be5c24.jpg)

**Comment by backwardsEric** [comment]
That's the expected result when using a Code Page 437 font with text encoded in Unicode:  any character where Unicode's value differs from that for Code Page 437 (so pretty much anything that isn't a printable character in the ASCII standard) won't be displayed properly.  ó is 243 (0xf3 in hexadecimal) in Unicode which happens to be ≤ in Code Page 437's assignments.   ó is at 163 (0xa3 in hexadecimal) in Code Page 437.

As Angband is sticking with Unicode encoding, you'd have to workaround this yourself.  One way would be to  use a Unicode font (to get a DOS-like look with that, you'd need to use a preference file that emulates font-ibm.prf but changes the assignments to use a symbol from Unicode that most closely matches the Code Page 437 one; you'll also need  access to a fixed-width Unicode font which supports those symbols and can be used with SDL2_ttf).  Another way would be to alter the encoding of the files in lib/gamedata (i.e. something like what Makefile.ibm does with iconv).

**Comment by smbhax** [comment]
Ooh. Trick may be I can't change some things while my current character (and maybe lore.txt? although I could probably replace the accents in that to match...) is going: save gets corrupt (ego_item.txt) / game crashes immediately (monster.txt).
