### ISSUE TITLE
Outdated "lib/help/command.txt" and "src/files.c" references in numerous .prf files

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5587]
The files "lib/help/command.txt" and "src/files.c" do not exist in the project, but are referenced in at least 16 and 15 .prf files, respectively.

The reader is advised to see one or both "for more information." This does not appear to apply to the nearest help file by name, command.txt, as the only information in it is a command key list.

Search "lib/help/command.txt" (16 hits in 16 files of 1593 searched)
  C:\msys64\home\smbhax\angband\lib\customize\font.prf (1 hit)
	Line  8: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\customize\message.prf (1 hit)
	Line   8: # See "lib/help/command.txt" for more information.
  C:\msys64\home\smbhax\angband\lib\customize\pref.prf (1 hit)
	Line   8: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\customize\user.prf (1 hit)
	Line  8: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\adam-bolt\graf-new.prf (1 hit)
	Line    9: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\adam-bolt\xtra-new.prf (1 hit)
	Line   9: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\gervais\graf-dvg.prf (1 hit)
	Line   14: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\gervais\xtra-dvg.prf (1 hit)
	Line   8: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\nomad\flvr-nmd.prf (1 hit)
	Line    8: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\nomad\graf-nmd.prf (1 hit)
	Line    9: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\nomad\xtra-nmd.prf (1 hit)
	Line   8: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\old\graf-xxx.prf (1 hit)
	Line    4: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\old\xtra-xxx.prf (1 hit)
	Line   6: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\shockbolt\graf-shb-dark.prf (1 hit)
	Line   13: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\shockbolt\graf-shb-light.prf (1 hit)
	Line   13: # See "lib/help/command.txt" and "src/files.c" for more information.
  C:\msys64\home\smbhax\angband\lib\tiles\shockbolt\xtra-shb.prf (1 hit)
	Line  12: # See "lib/help/command.txt" and "src/files.c" for more information.

**Comment by backwardsEric** [comment]
src/ui-prefs.c is the place to look rather than src/files.c.  docs/customize.rst probably covers what lib/help/command.txt did.
