### ISSUE TITLE
SDL2: highlighted SDL2 menu items unreadable when using two-color palette

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5596]
MSYS2-compiled SDL2 front-end, recent code, Windows 11.

1) Use the color edit menu (=cc) to change the colors to black for the first color, and any single color for the other colors
2) Open the SDL2 mouse menu in the upper left-hand corner
==> Menu items in the SDL2 menu are a single filled block of color when highlighted, so they can't be read. This is slightly inconvenient for instance when changing a font size (Menu > Angband > Font > Size), because you're clicking on arrows you can't see, and you can't see the current size number (see screenshot below).

It can be worked around by moving the highlight briefly to check the menu item.

This is a minor aesthetic/accessibility issue, and probably not many users will be playing in two colors (or maybe more specifically it's when Slate and...whatever other grayish color that is are the same color). But I thought I might as well mention it. The way to avoid it would be to have the background color be the foreground color for highlighted menu items.

![mono](https://user-images.githubusercontent.com/91744319/208507309-d474e7ac-55a3-4f2f-be62-596fcb0a3972.png)

**Comment by backwardsEric** [comment]
Besides flipping foreground and background, some other ways that main-sdl2.c could handle the highlighting with a two-color palette:

- Always use the default palette for the menus.  Has the drawback that the appearance of the contents of the windows can clash with the appearance of the menus.
- Rather than changing the background color across the entire menu entry when highlighting, change the border for the entry.  Has the drawback that highlighting will be less noticeable.  Also, most user interface toolkits don't handle menu highlighting that way.

Is there any preference for one of those three?  Or for something else?

If we're reworking the highlighting, there's overlap between the highlighting and how the current active selection (i.e. for the font, tile set, or enabled terminals) are shown.  So it might be desirable that the highlighted entry and current active entry appear differently.  It's tempting to add a displayed check mark for the current active entry, but while okay for the entries in the submenus, the main menu bar entries for the active terminals are another matter.

**Comment by smbhax** [comment]
Sticking with the default palette for the pop-up SDL2 menu would be all right as long as the always-visible SDL2 main menu bar at the top of the screen followed the user's palette, otherwise the effect of the user's custom palette would be ruined by constantly intruding foreign colors.

A one-pixel border for the currently moused-over item(s) might work all right.

Personally I would be okay with having inverted colors for both the current highlight and the current active selection; I don't think that would be too confusing, really.

Except, I wouldn't want inverted color on the current selections in the top menu bar, which would show up brightly and would be a bit of a constant distraction while playing.

I was thinking about whether a checkerboard dither pattern on a background or on the text would work, when I noticed that's already used for unselectable items:

![dither](https://user-images.githubusercontent.com/91744319/209737700-d1667aa3-bc22-405a-aeec-0de659b394d3.png)

Currently, dithered text is used to indicate a non-highlighted unselectable option. I was thinking for the top menu bar it might have been nice to dither the text of the currently selected items. Or hm, maybe of the non-currently-selected items. One of those.

In any case, I wouldn't want highlighted or dithered backgrounds on any part of the top menu toggle bar.

Obviously, the fully dithered highlighted + currently unselectable option is unreadable, which isn't great--but doesn't really matter a whole lot, really. Dithered background + non-dithered text would probably work a little better.

I really don't mind most of that stuff all that much, though. As a weirdo who chose monochrome, I expect not to get visual feedback for some things, just like I can no longer see by color which stats have been drained. I would like to be able to read all currently valid options, though : ) -- so just getting inversion going on background and text for the current highlight would be okay, I think. Anything more than that is gravy. (But also don't put solid or dithered background fills on the always-visible top menu bar thing, that would suck.)

Actually, highlighting the currently moused-over item(s) isn't even all that necessary, is it? It's a mouse-only menu, and you know what you're pointing at.

I think I'm stuck with wanting separate visual feedback schemes for the top always-visible toggle bar and the pop-up menus (they currently DO have separate systems, anyway):

SDL2 top toggle bar:
- no mouse-over highlighting
- dithered text for inactive items (far-left "Menu" always non-dithered)

SDL2 pop-up menu:
- dithered text for unselectable items
- dithered backgrounds with solid text for moused-over unselectable items
- inverted text & backgrounds for all other moused-over items
- 1-pixel box border or bold text, if bolding is guaranteed to work for all fonts, for currently toggled-on items

or simpler, not worrying about mouse-over indication:

SDL2 pop-up menu:
- dithered text for unselectable items
- inverted text & backgrounds for currently toggled-on items

**Comment by backwardsEric** [comment]
At some point keyboard traversal of the menus for both the SDL2 and SDL front ends should be implemented, so I'd prefer to retain some indication of the highlighted menu item for that.
