### ISSUE TITLE
SDL2: color edit - crash cycling backwards from color 255 (main-sdl2.c line 4023 "graphics.texture != NULL")

### ISSUE THREAD

**Issue by smbhax** [angband/angband#5597]
MSYS2-compiled SDL2 front-end, latest Angband code, Windows 11.

Default fonts, no tile set, with or without subwindows.

The crash information is identical to the occasional crash when setting tiles to None (#5592).

1) Press =cc to get to the "Modify colors" screen; if you haven't been editing other colors previously in this session, it will be at color 0
2) From color 0, press NN
==> This goes to color 255 ("undefined") on the first press; on the second press, the game crashes with an "Assertion failed" window--see screenshot below.

~~~~~~~~~~~
Microsoft Visual C++ Runtime Library

Assertion failed!

Program: C:\msys64\home\smbhax\angband\angband.exe
File: main-sdl2.c
Line: 4023

Expression: subwindow->window ->graphics.texture != NULL
~~~~~~~~~~~~

![4023_colors](https://user-images.githubusercontent.com/91744319/208971745-3578144d-d0db-4cf4-b037-056cda27a355.jpg)

**Comment by backwardsEric** [comment]
#5598 avoids the crash but doesn't address the underlying issue for what triggers the SDL2's pict_hook in this case.  Posted http://angband.oook.cz/forum/showthread.php?t=11422 to see if anyone has insights about entries 128 to 255 of the color table. I'm tempted to remove them and change the implementation of the BG_* constants to address the underlying issue.
