### ISSUE TITLE
Corrupted save file

### ISSUE THREAD

**Issue by chowell2718** [angband/angband#5599]
Hi,

I was killed by a shapeshifted Maia of Aule and my save file appears to be corrupted now. Could you take a look?

Thanks!

[Beldoria.zip](https://github.com/angband/angband/files/10288152/Beldoria.zip)

**Comment by backwardsEric** [comment]
Thanks for the report.  I'll try to take a look at the save.  Which version were you using?

**Comment by chowell2718** [comment]
4.2.4

Thanks!

**Comment by backwardsEric** [comment]
Could you describe the problem(s) you had with that savefile?   Was there anything amiss at the tombstone screen?  Did the game crash when you tried to restart the game with that savefile?

If the game did crash when you loaded the savefile, the slightly modified copy of that savefile attached below should load successfully (assuming the crash you saw was the same one as I saw when loading it:  a blackguard's bloodlust can cause it to attack even after death).

[Beldoria.zip](https://github.com/angband/angband/files/10290189/Beldoria.zip)

**Comment by chowell2718** [comment]
Yes, that was the case. Thanks for helping fix the save file.

**Comment by backwardsEric** [comment]
Resolved by https://github.com/angband/angband/pull/5600 :  bloodlusted blackguards won't perform random attacks when dead.
