### ISSUE TITLE
Inconsistent energy use for wielding and taking off an item?

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5601]
If I've understood the code correctly, wielding an item never takes energy and taking off an item always takes energy.  It looks like it has been that way a long time (14 years or more).

When wielding an item replaces another item, that's inconsistent since the wield is taking something off in that case.

**Comment by NickMcConnell** [comment]
That does seem inconsistent.

**Comment by backwardsEric** [comment]
Wielding does take energy (player->upkeep->energy_use is set in inven_wield()).  The amount is different than for taking off (in do_cmd_takeoff()).  If that's a problem, probably best to put it under a different issue.

**Comment by NickMcConnell** [comment]
👍
