### ISSUE TITLE
Add the game to steam

### ISSUE THREAD

**Issue by wiki-me** [angband/angband#5616]
Why I think it will be beneficial:

* it is very popular and it's website has a lot of visitors (Alexa ranks it as the 314 most popular website on the internet).

* Seeing a lot of good reviews can really tip the scales and make me (and probably others) take a chance on trying a game (it's basically [social proof](https://en.wikipedia.org/wiki/Social_proof)), it could lead to more exposure which will mean more developers and more feedback (former developer of naev [said](https://www.reddit.com/r/opensourcegames/comments/tcwkr6/naikari_020_open_source_space_trading_and/i0kb8dd/) it brought new developers).

* Steam is one of the only game review systems that i know of which is able to rank games only based on \"recent reviews\" (besides gog.com), so if a game starts badly and keeps getting developed and becomes good the old review don\'t prevent it from getting a good rating, this is especially good for open source games that can have a very long history of development (being developed for more then a 15 years is common).

* Another nice feature of steam is that you can find reviews for players that played more then a certain number of hours , some games can be half done and a review after three hours of play time might not reflect problems, a review after say 30h indicates you can pour some time into it without the game failing (and you will have to wait for a newer version and maybe play it until the point you reached before because save files are not always compatible with future versions).

* Some FOSS projects on steam have a price (for example the game [Mindustry](https://store.steampowered.com/app/1127400/Mindustry/) ). Maybe you could use that for funding and paying freelancers to create graphics and sound (iirc this is what shattered pixel dungeon does). 

* early feedback can be useful, there is a saying that if you are not embarrassed when releasing the software then you released it too late, steam can mark a game as early access (like *[*supertux*](https://store.steampowered.com/app/1572920/SuperTux/)* does) so there is no danger of disappointing players because the game isn't fully polished.

**Comment by Zireael07** [comment]
Are you just going around repositories and suggesting they add their games on Steam? 
I saw you make an almost exact same proposal with the similar points on Terasology.

That said, Angband is not a good fit for Steam IMHO - just the graphics will mean a flood of negative reviews because many modern gamers expect modern graphics and not ASCII/pixel art tiles.

**Comment by NickMcConnell** [comment]
Not while I'm maintainer.

**Comment by Zireael07** [comment]
@NickMcConnell can you give a reason why? Lack of time? Too difficult? What I wrote above?

**Comment by NickMcConnell** [comment]
All of them 😄 .  It would involve a lot of uninteresting work for no tangible benefit.  Angband isn't a new game trying to make a mark, it doesn't require funding, it doesn't want to employ people.  And *early feedback* ?  Given it's more than 30 years old, it's a bit late for that.

**Comment by Zireael07** [comment]
Hehe, he did indeed miss the mark on that - as I said above, he seems to be copy and pasting this to various repos with only minor adjustments :P

**Comment by wiki-me** [comment]
> Are you just going around repositories and suggesting they add their games on Steam?
I saw you make an almost exact same proposal with the similar points on Terasology.

I made requests to other projects besides terasology, and will probably do that to a few other projects in the future, but i don't see how that contributes to the discussion, the points are identical to all open source projects (at least without knowledge about their development) and i stay around and respond to questions and comments .

If anybody is interested, the main motivation is that i played a foss game once and found out after a few hours it is kinda half baked (so i basically feel like i kinda wasted a few hours, but ofcourse nobody owes me anything, i submitted a few bug reports so at least something came out of it), so i would prefer to have a good sample size of reviews, preferably with people who played the game for atleast 30-40 hours.

>That said, Angband is not a good fit for Steam IMHO - just the graphics will mean a flood of negative reviews because many modern gamers expect modern graphics and not ASCII/pixel art tiles.

[Dwarf fortress](https://store.steampowered.com/app/975370/Dwarf_Fortress/) has graphics that seem similar to angband, a quick search shows at least [one game](https://store.steampowered.com/app/328760/SanctuaryRPG_Black_Edition/) that is ascii based and very well reviewed.

>All of them smile . It would involve a lot of uninteresting work for no tangible benefit. 

So if someone else will want to do it it's ok?

> Angband isn't a new game trying to make a mark

Still it's hard to find real reviews of it, and it could bring more players and even contributors, iirc that's what happened to openttd (despite being a fairly mature game).

> it doesn't require funding, it doesn't want to employ people. 

You could even make it donationware, the world has enough hungry and poor people to put that money to good use.

>And early feedback ? Given it's more than 30 years old, it's a bit late for that.

In my defence, even old open source projects can experience long periods of instability where an "early access" release coulld be useful , If you are an older linux user you might remember stuff like KDE 4 or GNOME 3 or even today with GIMP being a few years in development.

Thank you for your time!

**Comment by jcnventura** [comment]
> So if someone else will want to do it it's ok?

Well, it is GPL, with some exceptions (see https://angband.readthedocs.io/en/latest/copying.html). So nothing prevents you from doing whatever you want with the code as long as you abide by the license. I'd just suggest to call it "Steam Angband" since you'll have to remove the non-FOSS sections, and make it free.

Whatever you do don't start charging for it, like these guys did: https://store.steampowered.com/app/1443430/Rogue/

**Comment by jl8e** [comment]
> > So if someone else will want to do it it's ok?
> 
> Well, it is GPL, with some exceptions (see https://angband.readthedocs.io/en/latest/copying.html). So nothing prevents you from doing whatever you want with the code as long as you abide by the license. I'd just suggest to call it "Steam Angband" since you'll have to remove the non-FOSS sections, and make it free.
> 
> Whatever you do don't start charging for it, like these guys did: https://store.steampowered.com/app/1443430/Rogue/

That Rogue is a legit commercial version.

As long as you remove the sounds and shockbolt tiles, I believe there's nothing else that stops you selling it, as long as you fulfill the requirements of the GPL.

(Aside from the fact that, if you don't have a value-add of your own, nobody's going to buy what they can get for free.)

**Comment by NickMcConnell** [comment]
> (Aside from the fact that, if you don't have a value-add of your own, nobody's going to buy what they can get for free.)

I'm not actually convinced of that - there are people who want to support games, and people who just have money burning a hole in their pockets.  Another reason I have for not wanting to put the game on Steam is I don't want to think about where the money should go.  A maintainer with a different mindset might set up a foundation or something, or I guess just pocket it 😄
