### ISSUE TITLE
Bad counting of room profiles

### ISSUE THREAD

**Issue by NickMcConnell** [angband/angband#5621]
In finish_parse_profile():
```
	/* Count the list */
	while (c) {
		struct room_profile *r = c->room_profiles;
		c->n_room_profiles = 0;

		z_info->profile_max++;
		c = c->next;
		while (r) {
			c->n_room_profiles++;
			r = r->next;
		}
	}

```
I believe everything to do with r and n_room_profiles should be removed from here.  Room profiles are counted later in the function, and this segfaults if c->next is NULL.
Asking for confirmation; it's code I wrote 8.5 years ago...

**Comment by backwardsEric** [comment]
As you said, deleting the first counting loop is right since it is, at best, redundant with the later calculation.
