### ISSUE TITLE
Innate frequency not specified for hezrou

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5646]
PowerWyrm pointed out some time ago, http://angband.oook.cz/forum/showpost.php?p=142351&postcount=147 , that hezrou have BR_FIRE and BR_ACID but do not have an innate frequency set.

I don't know what's appropriate for the frequency.  It could be set to 25 to mimic what it gets now from the fallback setting in mon-init.c, but is there something better than that?  The old version of hezrou didn't have breath attacks and had a spell frequency of 9 for the two non-innate spells that it had, BO_FIRE and S_DEMON.

**Comment by NickMcConnell** [comment]
I think 3, same as the spell frequency.  It's slow, so it needs to hit hard and often when it does move.
