### ISSUE TITLE
BLESS_WEAPON description and implementation

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5664]
The description for the BLESS_WEAPON player ability says that there's melee bonuses for blessed and hafted weapons, but the calculations in player-calcs.c (lines 2296 to 2300 in the current version) only grant a bonus for blessed weapons.  I'm guessing that is a mistake in the code rather than the description.

Also, the description of the Blessed ego in docs/attack.rst mentions that wielding a non-blessed sword or polearm has an effect on a priest's spell casting.  That documentation hasn't kept up with the changes in 4.2.

**Comment by NickMcConnell** [comment]
Yes, I think that's a mistake in the code.

**Comment by backwardsEric** [comment]
Should the default starting kit for a paladin use a whip rather than a main gauche?  With the default point buy, the whip has the same number of blows and does more damage because of the bonuses for being hafted.  It also has the advantage of being cheaper, leaving more gold for other things.
