### ISSUE TITLE
Logic for multiple traps in a grid

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5683]
Some parts of the code, the next field in struct trap and portions of the logic in hit_trap() are examples, try to allow for multiple traps in a grid.  However, the code used to destroy a trap, square_destroy_trap() and square_remove_all_traps(), destroys all the traps in a grid so the provision for multiple traps is half-hearted.  Need to decide if support for multiple traps is desired (if not for Angband itself, possibly to give variants the flexibility to do what they want).  Then based on that, make all the logic handling traps consistent with that.

**Comment by NickMcConnell** [comment]
I'm reluctant to take it out, for the reasons you give - I don't think there's a big hurry to change the other logic though.

**Comment by backwardsEric** [comment]
I agree that there's no hurry to change things.

**Comment by agoodman00** [comment]
Possible bug with this change.  The added assert()	
assert(square_iscloseddoor(c, grid));
should probably have 
	assert(square_iscloseddoor(c, grid) || square_issecretdoor(c, grid) );
At least I think that is what is causing a crash I am seeing.

**Comment by backwardsEric** [comment]
Yes, it is definitely a bug and will be triggered by a monster opening or bashing a secret door.  Thank you for finding that.  Should be fixed by https://github.com/angband/angband/pull/5883 .
