### ISSUE TITLE
Object that gives a vulnerability and a resistance to the same element

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5694]
For an object that gives both a vulnerability and a resistance to the same element (but no immunity to that element) what's shown in the resistance panel of the character sheet or in the equippable comparison can be misleading.  Currently a '.' is shown which could mislead a player to think that he or she'll have a resistance for that element if some other equipment provides a resistance and there's no other equipment that provides a vulnerability.

Allowing for another symbol ('0' or '~' might be good choices) to be displayed when an object gives a vulnerability and a resistance would resolve that.

**Comment by NickMcConnell** [comment]
Yeah, good idea.  I think I like '~'.
