### ISSUE TITLE
Overflow of p in borg_crush_hole()

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5718]
@agoodman00 , at a point after the attached save file was recorded, the borg hit a "Signed integer overflow" exception generated by the undefined behavior sanitizer.  The call stack at the point of the exception was:

1. borg_crush_hole at borg7.c:1990:6
2. borg_think_dungeon at borg8.c:5006:9
3. borg_think at borg9.c:643:13
4. borg_inkey_hack(flush_first=0) at borg9.c:3180:13
5. inkey_ex at ui-input.c:228:12
6. textui_get_command(count=0x00007ff7bfefd820) at ui-input.c:1759:8
7. textui_process_command at ui-game.c:518:15
8. textui_get_cmd(context=CTX_GAME) at ui-game.c:594:3
9. play_game(mode=GAME_LOAD) at ui-game.c:921:4

p was 236717700 at the point of the exception, borg_power() had returned 2367177, and the item it was thinking of expunging was a stack of 10 rations of food.

A direct solution would be to check for potential overflow when inflating p by 100 or 500 and cap the result at INT32_MAX, but I don't know if that would impair the decision made about what to expunge.

[Telch.zip](https://github.com/angband/angband/files/12265941/Telch.zip)

**Comment by agoodman00** [comment]
IMO what it is doing makes no sense.  Bumping up the power to make cost have less impact is not the right way to handle this.  I think I will redo this to have it track cost separately and then, if it makes sense, divide the cost down before adding it.  I will try to get to this monday.

**Comment by backwardsEric** [comment]
Resolved by https://github.com/angband/angband/pull/5720/commits/d5ae3f647d619ac1d87b3d93456784fa898b1f28 .
