### ISSUE TITLE
Borg and alternate food types

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5719]
@agoodman00 , as noted by Jay in http://angband.oook.cz/forum/showpost.php?p=161259&postcount=6 , the borg doesn't take advantage of some alternate sources of nutrition when hungry.  borg7.c:240-251 only considers slime molds, waybread, and rations.  Other possible sources are potions of slime mold juice, hard biscuits, apples, handfuls of dried fruits, slices of meat, honey-cakes, and pints of fine wine.  If willing to waste some positive side effects, sips of miruvor, draughts of the ents, the mushrooms without negative effects, and healing potions (except *Healing* and Life) could also be used.  If willing to risk the negative effects, scraps of flesh, flasks of whisky, swigs of orcish liquor, the mushrooms (except Purging) with bad effects, and potions of sleep, confusion, and slowness could be used.  Scrolls of satisfy hunger can be used at borg6.c:14078-14080, but not at borg7.c:240-251.

**Comment by agoodman00** [comment]
hmmm, this should be being handled in borg6.c borg_eat_food_any() where it eats anything that is food including drinking potions.  I wonder where this is used... Going to have to do a bit of debug.   I will also check into the discrepancies of when it uses satisfy hunger.

**Comment by backwardsEric** [comment]
Ah, I had missed borg_eat_food_any().  A revised version of that is up at https://github.com/agoodman00/angband/pull/4 .  It'll use potions of slime mold juice and, just in case, potions of sleep, slowness, blindness, and confusion if there's protection against the negative effect.  Dropped potions of life, \*healing\*, and restore mana from those considered since they do not provide any nutrition.

**Comment by NickMcConnell** [comment]
I've made a label specifically for borg issues, and I'm thinking they can always go in the Future milestone.

**Comment by NickMcConnell** [comment]
Actually no, let's have a separate milestone too.

**Comment by agoodman00** [comment]
Where would I put a label/milestone for a pull request?  I have https://github.com/angband/angband/compare/master...agoodman00:angband:borg_4x?expand=1 which has the code change to fix a glyph issue (https://github.com/angband/angband/commit/e0bbc345d21f6a2f20827ca86e37a79ec13f0330) and Eric's change to eating (https://github.com/angband/angband/commit/ec89221e899190781a96d18a57663a6426fc2532).  How would I label it or associate it with an issue or milestone?

**Comment by NickMcConnell** [comment]
> Where would I put a label/milestone for a pull request? I have https://github.com/angband/angband/compare/master...agoodman00:angband:borg_4x?expand=1 which has the code change to fix a glyph issue ([e0bbc34](https://github.com/angband/angband/commit/e0bbc345d21f6a2f20827ca86e37a79ec13f0330)) and Eric's change to eating ([ec89221](https://github.com/angband/angband/commit/ec89221e899190781a96d18a57663a6426fc2532)). How would I label it or associate it with an issue or milestone?

Don't bother labelling pull requests, just issues 😄

**Comment by backwardsEric** [comment]
Resolved by https://github.com/angband/angband/pull/5720/commits/ec89221e899190781a96d18a57663a6426fc2532 , https://github.com/angband/angband/pull/5720/commits/a31e64c6a7821c53f1ee46ae3aec56124030cc09 , and https://github.com/angband/angband/pull/5720/commits/d5e69e5ad67c1d66a857df33b11e41fb2becbcee .
