### ISSUE TITLE
Borg: pointer alignment in borg_inkey_hack()

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5741]
@agoodman00 , clang on OpenBsd (32-bit; in case it matters) issues this warning,

```
warning: cast from 'char *' to 'uint32_t *' (aka 'unsigned int *') increases alignment from 1 to 4 [-Wcast-align]
```

for the line

```
(*((uint32_t*)(buf)) != 0x20202020))
```

in borg_inkey_hack().  Since buf is a character array on the stack, it's not clear that the alignment of buf[0] through buf[3] will match what is expected for a uint32_t.  It would be more portable, but more verbose, to explicitly test the first four entries of buf, i.e.

```
if ((0 == borg_what_text(0, 0, 4, &t_a, buf)) &&
        (t_a != COLOUR_DARK) &&
        (buf[0] != ' ' || buf[1] != ' ' || buf[2] != ' ' || buf[3] != ' '))
```

**Comment by agoodman00** [comment]
As with other issue, hopefully this can wait till the 9th when I am back
Or if you want to take care of it, I am fine with that
