### ISSUE TITLE
Artifacts with elemental vulnerabilities not derived from curses

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5758]
The logic in obj-make.c's copy_artifact_data() does not properly handle if the base kind or the artifact itself provides an elemental vulnerability.  It uses the maximum of the resistance level from the base kind and the artifact which, if one provides a vulnerability and the other provides a resistance level that is not a vulnerability or an immunity, the result will completely suppress the vulnerability.

This currently has no effect in Vanilla:  no standard artifact has a vulnerability and random artifacts can only acquire vulnerabilities by having a curse.  It does have an effect in NarSil (which inherited the same logic in copy_artifact_data()).  See Infinitum's report here, http://angband.oook.cz/forum/showpost.php?p=161484&postcount=30 : "Calris doesn't seem to give frost weakness."

**Comment by NickMcConnell** [comment]
OK, that ought to be fixed in V and pulled into NarSil then.

**Comment by NickMcConnell** [comment]
Also makes me think maybe Angband should have standard artifacts with vulnerabilities...
