### ISSUE TITLE
Game allows cloning of Beorn when he has shapechanged

### ISSUE THREAD

**Issue by ThirdLemon** [angband/angband#5765]
You can use a wand of Clone Monster on Beorn while he is shapechanged into Beorn, the Mountain Bear, and he will be cloned despite being a unique. The game then crashes if you use 'l'ook to inspect the cloned Beorn.

**Comment by NickMcConnell** [comment]
Nice catch

**Comment by NickMcConnell** [comment]
Yes, I think that's right
