### ISSUE TITLE
angband: Couldn't load the requested font. (10x20)

### ISSUE THREAD

**Issue by nobodyatandnothing** [angband/angband#5782]
xwayland

running fc-cache does not help

**Comment by backwardsEric** [comment]
Which OS (and if Linux, which distribution) is this?  The X11 front end expects certain core X11 fonts to be installed though many Linux distributions no longer install those fonts by default.  If running `xlsfont -fn "10*"` from a terminal does not report anything, the needed font has not been installed or it has been installed but something is preventing it from being recognized by X11 (see https://github.com/angband/angband/issues/4575 and https://github.com/angband/angband/issues/5088 for other cases where there was trouble).  On Debian and Ubuntu, the xfonts-base package has the needed font.  On Fedora, the package is xorg-x11-fonts-misc .
