### ISSUE TITLE
suicide quitting negative/oudated 

### ISSUE THREAD

**Issue by dchmelik** [angband/angband#5789]
The first time I played Moria (which forked to Angband) and quit, I felt the worst I ever did playing/losing any game other than being physically hurt (sports).  Many people have friends/family who suicided or have suicidal thoughts themselves, which a game should allow them to escape from rather than reminding them of.  Even when I played games like Doom, which insults you for quitting, I didn't feel as bad as quitting Moria/Angband/ToME/etc.  Suicide is a sin in most/all cultures (other than some for terminal/painful illness) and you shouldn't have to sin to quit.  In the game which inspired Moria/Angband--Dungeons & Dragons--no one considered if they didn't play a while, or played another character, that they suicided.  They'd think the character goes on living a normal life, or the Dungeon Master (DM) would take them over as a non-player character.
        I suggest/request this element be removed/deprecated--at least off unless you set to compile back in.
        It should simply say you retire from adventuring, not show a gravestone.

**Comment by NickMcConnell** [comment]
I've thought about this occasionally too.  I'll list it as to be implemented.
