### ISSUE TITLE
Solid walls and Hybrid walls for 3DS/DS

### ISSUE THREAD

**Issue by pav1388** [angband/angband#5810]
On the DS platform, the attribute to change the background of a symbol is not checked.

_Link ->_ [https://github.com/angband/angband/commit/d448578469598f5dc4ffd267b98b33f4c16b8e0a](https://github.com/angband/angband/commit/d448578469598f5dc4ffd267b98b33f4c16b8e0a)

P.s. I don't know how to make a pull request from a single commit, so I'll write it here.

![_22 12 23_13 39 20 208](https://github.com/angband/angband/assets/59249860/22d3c502-1db5-4b24-8830-e6cc166b7a98)

**Comment by backwardsEric** [comment]
Thank you for the bug report.  The proposed fix is here, https://github.com/angband/angband/pull/5811 .  It avoids using bitwise operations to extract the base color and background option in case MAX_COLORS is not a power of two.
