### ISSUE TITLE
SDL2: fullscreen to not fullscreen can leave subwindows in violation of minimum size requirements

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5842]
With a large enough font configured for the main subwindow, I've seen that subwindow no longer satisfy the 80 column x 24 row minimum size after changing from fullscreen mode to not fullscreen mode.  Resolving #5840 and #5841 may help avoid that but may need either an additional constraint on the fonts selected in fullscreen mode (players who do not use the not fullscreen mode may not like that limitation) or adjustment of the font and subwindow size when transitioning to not fullscreen mode so that the minimum sizes are still satisfied.

**Comment by smbhax** [comment]
(The title of this surprised me, as toggling off Fullscreen in the Windows-compiled version of the SDL2 interface has never done anything, and I didn't really know what to make of that. I guess it's probably a bug? I don't know what not fullscreen mode looks like when it's working as expected.)

**Comment by NickMcConnell** [comment]
Maybe the player just needs to learn not to do that?

**Comment by NickMcConnell** [comment]
Yep, I'm going to be harsh on this one.
