### ISSUE TITLE
can't access = options in sdl2

### ISSUE THREAD

**Issue by Turmfalke2** [angband/angband#5853]
hi,
I'm trying to play using sdl2 interface and everything appears to work fine, except I can't open the options screen. = just doesn't do anything. It works if I start the game using the x11 mode.
I'm using a German keyboard layout, but the game seems to handle that just fine. If I write a note using : all my keys (except =) do what I would expect them to do.

**Comment by backwardsEric** [comment]
Which version of Angband are you using?  There was a change after 4.2.4 was released that was incorporated into 4.2.5 which affected the '=' key with the SDL2 front end.

If you are using the latest release, 4.2.5, you might try disabling the "Send Keypad Modifier" option from the front end's menu.  On non-English keyboard layouts, that can help the front end correctly handle keys that appear both on the main keyboard and on the numeric keypad in English keyboard layouts ('=' is on of those).  The drawback of disabling that option is that it prevents keymaps from treating a key on the numeric keypad differently from the key on the main keyboard that generates the same symbol.

**Comment by Turmfalke2** [comment]
I have downloaded and built the 4.2.5 source code.

Also thank you, disabling the **Send Keypad Modifier** did help, wonder why I didn't spot that. Being unable to differentiate between numeric keypad and main keys isn't an issue for me since I don't have a keypad. Enabling hjkl was the reason I wanted to open the options menu.
