### ISSUE TITLE
The show_damage option does not show spell damage

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5862]
This is from the Debian bug tracker, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780770 .

If we want to implement that, there's two effects which both have one target, TAP_UNLIFE and CURSE, where it would be straightforward to implement showing the damage (it is already done in JUMP_AND_BITE).  All other spells damaging monsters are either earthquakes (multiple monsters can be affected, does not use mon_take_hit(), and has its own messaging via msg()) or projections (multiple monsters can be affected, uses mon_take_hit(), messaging goes through add_monster_message()).  For those, would the damage be shown for all the monsters that take damage or only the monster, if any, that matches the current target or health_who?

For damage to the player, those handled by make_attack_normal() in mon-attack.c show the damage if there is an action string for the blow.  That damage display does not include any modifications from the effect handler for the blow.  Other causes of player damage (effect handlers, poison/cut/starvation damage in process_world(), player_over_exert(), player_take_terrain_damage(), and projections) do not show the damage.

**Comment by NickMcConnell** [comment]
I think we've thought about this before and decided it's too hard, especially in the case of what to show for multiple monster targets.  If you or someone else really wants to have a go at it that would be fine, but I think not doing it is a valid option too.

**Comment by NickMcConnell** [comment]
Limiting to one monster might work, with perhaps priority order of targeted monster, then monster hit (if different from targeted monster), then first monster hit (in the case of no target).
