### ISSUE TITLE
High-elf mage activates the Phial of Galadriel and takes 0-3 damage

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5866]
That does not happen prior to https://github.com/angband/angband/commit/3b7cb18aadb30d16ed26bb3fb4c41fce8f855e42 (between 4.2.1 and 4.2.2).  It could be intentional but seems wrong for two reasons:

1) For monsters, LIGHT_WEAK only does damage if the monster is specifically marked as vulnerable by having the HURT_LIGHT flag.  Players do not have something like that and all are vulnerable.
2) A high-elf intrinsically resists projections of ELEM_LIGHT, but that confers no protection against LIGHT_WEAK.  Yes, it is a different projection type but the name suggests that light resistance would have an effect.

The situation with DARK_WEAK is similar:  monsters are never damaged by it but players can be.  In the current master, reading a scroll of darkness causes the reader to take one point of damage.

**Comment by NickMcConnell** [comment]
It seems very wrong

**Comment by backwardsEric** [comment]
Is implicitly giving all players immunity (or resistance and then set the resistance scaling factor to something good enough in projection.txt) to LIGHT_WEAK (DARK_WEAK as well?) the appropriate solution?  Could add a directive to projection.txt ("player-resistance" perhaps) so that the intrinsic resistance for all players to a given projection could be configured.

Another option would be to allow specifying the resistance level to the projections that are not in list-elements.h via values directives in the text files and then changing p_race.txt (or class.txt but there's no currently no provision there for a values directive) so that most (all?) of the races or classes get a resistance or immunity to LIGHT_WEAK or DARK_WEAK.

**Comment by backwardsEric** [comment]
Another, more specific solution, would be to change some activations, spells, and objects to use the SPHERE rather than SPOT effect so the damage would not be applied to the player.  The LIGHT and ILLUMINATION activations, priest's Call Light spell, paladin's Call Light spell, Light scroll, Light staff, and Rod of Illumination are the ones that could cause damage with LIGHT_WEAK.  Mage's Light Room spell also uses SPOT with LIGHT_WEAK, but the damage is low enough that the 1/10th reduction in project_p() always reduces the damage to zero.  There's also three spells in old_class.txt using SPOT that could cause damage with LIGHT_WEAK.

**Comment by NickMcConnell** [comment]
This last one is a good point.  I think the problem may have arisen with me being inconsistent about which effects were used for what, and going through phases of either overloading effects, or introducing too many new ones.  I think with SPOT, SPHERE and BALL potentially one is being used where one of the others should be.
