### ISSUE TITLE
square_isknown(player->cave, ...) returns false

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5879]
Instead, I'd suggest that square_isknown(player->cave, grid) act the same as square_isknown(cave, grid).  In many situations, one will call square_isknown() to see if the player has some memory of a location and then will do specific tests of what that memory is (square_ispassable(), ...).  As it is now, the square_isknown() call has to use cave as the chunk while the other calls have to use player->cave.  That can make it easier to mistakenly use cave in the other calls leading to bugs like https://github.com/angband/angband/issues/5295 .

In a similar vein, I'd suggest renaming square_isnotknown() (square_ismisremembered() is closer to what the function does, but that's long and hard to type).  Since square_isnotknown() is not a synonym for !square_isknown(), the current name makes it easy to mistakenly use one for the other, leading to bugs.  Like the suggestion above, square_isnotknown(player->cave, grid) should give the same result as square_isnotknown(cave, grid).  EDIT:  perhaps square_ismemorybad() is what square_isnotknown() should be called

**Comment by NickMcConnell** [comment]
Yes, agreed.  The square_ predicates have grown somewhat organically (to be polite), so any clarification of them is generally a good idea.  The main thing is to check all the instances to make sure the fix isn't breaking anything.
