### ISSUE TITLE
4.2.5: Crash on exiting Single Combat

### ISSUE THREAD

**Issue by tryphiodorus** [angband/angband#5886]
I engaged Meássë, the Bloody in Single Combat in Angband 4.2.5. When I defeat her, the game repeatably crashes.

One possible trigger is that I had previously (prior to casting Single Combat) cast Word of Recall and it may have reached the actual recall time while I was in the arena.

The (gzipped) save file is [tryphiodorus_v1.gz](https://github.com/angband/angband/files/14145199/tryphiodorus_v1.gz). It should also be available at https://angband.live/tryphiodorus_v1/angband/4.2.5/tryphiodorus_v1 (since I don't seem to need to be logged in to download it).

Running locally, the message generated on the crash is:

> angband: generate.c:1397: prepare_next_level: Assertion `old_known' failed.
> angband: software bug

_Edit:_ Yes, I believe the recall was the problem--running under gdb, at the time of the assertion failure [`name`](https://github.com/angband/angband/blob/master/src/generate.c#L1388) is 'Town' and `known_name` is 'Town known'; `p->depth` is 0. I can also see the recall kick message in the message log.

I don't have much of an opinion on what the proper solution should be here. Options include:
1) If recall kicks in while you're in the arena, it actually brings you back to the town immediately. This does mean that there is a way to "schedule" an exit from Single Combat, however.
2) When you leave the arena, if recall has kicked in in the meantime, you are brought directly back to the town. The loot from the monster you killed should probably not be generated at all.
3) The countdown for recall doesn't advance at all while in the arena.

I believe that the same issue could happen with Deep Descent, too.

**Comment by NickMcConnell** [comment]
Just clarifying from your comments on .live - this was in 4.2.5, not nightly?  And the issue you talked about was just getting a playable savefile, not a difference in the bug between versions, right?

**Comment by backwardsEric** [comment]
Thank you for the bug report.

I've attached a save that will allow you to continue the game without crashing.  With a different character, I got a different result when recall triggered in the arena:  the monster in the arena died and the player was transferred to a different arena with nothing else there.  In any case, something has to be done with a pending recall in effect when Single Combat is cast.  Your proposed solution of (3) is easy to implement and makes some sense.  Another possibility is to cancel the recall when Single Combat is cast (perhaps with an option for the player to retain the recall and cancel casting Single Combat).

[tryphiodorus_v1_fixed.gz](https://github.com/angband/angband/files/14149417/tryphiodorus_v1_fixed.gz)

**Comment by NickMcConnell** [comment]
I like solution 3 too.

**Comment by tryphiodorus** [comment]
Yeah, the error from this bug was on 4.2.5, not nightly. The issue I was facing on live was indeed just getting a playable savefile to be able to debug; the same seed resulted in a slightly different set of randarts on nightly vs. 4.2.5, which meant that loading failed because data on some of the randarts in my inventory could not be found. (Rebuilding at tags/4.2.5 fixed that incompatibility, which was what enabled me to run it under gdb to the point where I could verify that the recall was likely the trigger.)
