### ISSUE TITLE
+hit or +dam from curse on equipped weapon or launcher not included when attacking

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#5912]
In the attached save file, a level 1 warrior has a +0,+0 dagger with the air swing curse equipped.  Using a debugger to examine what the contributions to the to-hit roll are in chance_of_melee_hit_base() shows:

p->state.to_h is 4 (3 from 18/40 dexterity, 1 from 18/30 strength)
weapon->to_h is 0

The -20 from the curse is not accounted for.  Something similar happens with +dam from an equipped weapon:  melee_damage() and o_melee_damage() do not include to_d from curses, and it has not been included in struct player_state's to_d.  There are similar issues with launchers and thrown weapons with regards +hit and +dam (see chance_of_missile_hit_base(), ranged_damage() and o_ranged_damage()).  +hit and +dam from curses on launched ammunition are also not included.

In unmodded Vanilla, this is mostly unnoticeable to the player:  no curse affects +dam on weapons, launchers, or ammunition, no curse affects +hit on launchers or ammunition, and the air swing curse is the only curse that can affect +hit on weapons.

[Hyar.zip](https://github.com/angband/angband/files/14454066/Hyar.zip)

**Comment by NickMcConnell** [comment]
Looks like a bug
