### ISSUE TITLE
restore solid wall blocks

### ISSUE THREAD

**Issue by dchmelik** [angband/angband#5942]
For command-line mode (gcu) please restore solid block walls (and any other solid map characters) like always was (and still is) in the DOS version (and others)... this is more important than myriad changes that made Angband unlike AD&D and unlike Angband ever used to be since it was Moria: having '#' for walls makes it harder to look at the map so harder to play.  I don't use so-called 'tiles' version (after X11 art tiles were removed when licensing changed) which I guess is just X11/SDL 'tiles' made to look like ASCII, but solid walls should be default in all modes (gcu, sdl, x11).
```
unicode
point       character
u+2591   ░
u+2592   ▒
u+2593   ▓
u+2588   █
```

**Comment by backwardsEric** [comment]
Does the "Show walls as solid blocks" option (admittedly off by default) satisfy what you want?  It is available in all front ends from the in-game options menu ('=' key) under the "User interface options" category.

**Comment by dchmelik** [comment]
Yes; I guess it's set on some OS' Angband but not others for some odd reason.
