### ISSUE TITLE
Ongoing Borg Issues

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6011]
I'm still seeing problems with the borg after the latest update.  Here's an example where it's trapped and can't figure out how to escape.

[PLAYER.zip](https://github.com/user-attachments/files/16517708/PLAYER.zip)

I'm seeing other questionable behavior with this latest release, and I'll keep you posted!

**Comment by Netbrian** [comment]
This borg crashes for some reason.

[20240806-03 PLAYER.zip](https://github.com/user-attachments/files/16517808/20240806-03.PLAYER.zip)

**Comment by agoodman00** [comment]
> I'm still seeing problems with the borg after the latest update. Here's an example where it's trapped and can't figure out how to escape.
> 
> [PLAYER.zip](https://github.com/user-attachments/files/16517708/PLAYER.zip)
> 
> I'm seeing other questionable behavior with this latest release, and I'll keep you posted!

Yep, that borg is good and stuck.  it should try to dig out the quartz but doesn't think it is strong enough to.  I will check into that calculation and perhaps boost the limit if the borg is twitchy (unable to find anything to do)

**Comment by agoodman00** [comment]
> Here's the borg bouncing between two locations. [20240806-02 PLAYER.zip](https://github.com/user-attachments/files/16517747/20240806-02.PLAYER.zip)

This is what I would call "normal low level borg behavior".  When I restart he works fine but looking at the message log... he was bored, wanted to explore and go down but is on a leash so can only go so far (level dependent) from the stairs... gets too far, bounces back to the stairs.  Still bored, wants to go down, looks around, does it again... I have this behavior in my "to do" (https://github.com/agoodman00/angband/discussions/21) as "bouncing between two spots. he keeps track of some places he has been. Could generalize over the map and minimize repeated steps" which would at least make him explore new areas.

**Comment by agoodman00** [comment]
> This borg crashes for some reason.
> 
> [20240806-03 PLAYER.zip](https://github.com/user-attachments/files/16517808/20240806-03.PLAYER.zip)

Crash is bad... very bad.  I am having trouble duplicating it.  Can you send this with your borg.txt and angband.ini?

**Comment by Netbrian** [comment]
Here you go!


It feels like I'm seeing a lot more questionable behavior than the last version, and it digs more than I think it should be.  It's hard to isolate on a savegame though -- do you want a bunch of character dumps for dead borg?
[borg.zip](https://github.com/user-attachments/files/16606931/borg.zip)

**Comment by agoodman00** [comment]
Found the crash.  It is fixed in https://github.com/angband/angband/pull/6014

**Comment by agoodman00** [comment]
ok, I moved where the borg checks how it should behave when twitchy.  I am not sure what you were seeing was a borg sticking around after it was digging stuff but if it was, this should help that.  https://github.com/angband/angband/pull/6015

**Comment by agoodman00** [comment]
looks like both of those are now in the build

**Comment by Netbrian** [comment]
Thank you!  I'll run the latest version and keep you posted!

I suspect that my borgs get stuck so often simply because I leave it running throughout the workday.  That gives it more chances to be stuck when I end up checking on it.
