### ISSUE TITLE
Borg On Strike

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6028]
I'm still having trouble posting to angband.live.

This borg runs inside his house, and refuses to leave.  While this may be rational behavior on his part, it's still a bug.
[Cirialf.zip](https://github.com/user-attachments/files/16698619/Cirialf.zip)

**Comment by agoodman00** [comment]
checked in under https://github.com/angband/angband/pull/6029

**Comment by agoodman00** [comment]
BTW @Netbrian if you could either @ me or assign borg issues to me so I get an email, that would be great.  I don't know github well enough to create some sort of automation that looks for "borg" in new issues and emails me.

**Comment by Netbrian** [comment]
Looks like this is taken care of!  I'll assign you next time!
