### ISSUE TITLE
Borg Struggling to Collect Potions

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6032]
@agoodman00 

My borg has all the potions he needs, but refuses to dive to see Morgoth.

It might be waiting to kill some uniques, but no matter how long I leave the game open, he never gets around to actually doing that.

[PLAYER.zip](https://github.com/user-attachments/files/16791205/PLAYER.zip)
[borg.txt](https://github.com/user-attachments/files/16791207/borg.txt)

**Comment by agoodman00** [comment]
Have you checked ^z2 ?   That should tell you why he is at the level he is and if he feels he is ready for morgoth

**Comment by Netbrian** [comment]
The borg says he doesn't have enough *Healing* potions, but that's wrong, and he has over 190.  He doesn't seem able to actually grab his potions and head for the fight.

**Comment by agoodman00** [comment]
Okay I will check into it when I’m back at my house.  I’m traveling till the 9th

**Comment by agoodman00** [comment]
Okay, the code is triggered off of the triait "BI_PREP_BIG_FIGHT".  You can see this used in borg.txt as 
value(trait, prep big fight)
but I am seeing, both in the code and in borg.txt 
	value(trait, amt ezheal): range(1, 2): condition(value(trait, max depth) >= 46 and value(trait, prep big fight)): reward(10000);
	value(trait, amt ezheal): range(1, 1): condition(value(trait, max depth) >= 46 and !value(trait, prep big fight)): reward(10000);

so... I keep 2 if prpping for the big fight?  Ummmm... no, that don't seem right.  Should be 99 (get all the potions to go after morgoth).  Checking back in the code to see if I mucked this up or if it has been this way a while.  If it has been this way a while, there might be a reason for it and I will check further.   I think I probably typo'd at some point though.

**Comment by agoodman00** [comment]
There are more problems out there that this is revealing.  The check I mention above, that is actually right.  It is "what do I carry when trying to prepare" so there are checks below for "gather up everything to go after morgoth" make depth 99 or lower.  
Right now I noticed BI_EMPTY (number of empty slots) is wrong, doesn't take quiver into account.  Also need a "really, we need at least one empty slot at all times" reward or the borg will never pick up stuff from home, ever.  The "get stuff from home" check also had a flag that wasn't being set correctly so if any items had been sold it never picked up stuff.... 
in total, still working on this but it seems there are multiple issues here.

**Comment by Netbrian** [comment]
I'm having problems with angband.live , but wanted to mention that I think having the borg give up on swaps at level 90 makes perfect sense.  My observation is that the borg tends to be very powerful by then anyway, and most of the time it's just dead weight.

**Comment by agoodman00** [comment]
checked in 
https://github.com/angband/angband/pull/6041

**Comment by Netbrian** [comment]
Closing and validating!
