### ISSUE TITLE
Borg Struggling to Sell

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6035]
@agoodman00 

This borg keeps trying and failing to sell a ring.  I'm using the latest version, and am not sure what's happening.

[Cirialf 20240829.zip](https://github.com/user-attachments/files/16801473/Cirialf.20240829.zip)

**Comment by agoodman00** [comment]
I will check into it.  I am traveling till the 9th but will debug after that.

**Comment by Netbrian** [comment]
> I will check into it. I am traveling till the 9th but will debug after that.

Oh yeah, I understand perfectly.  I just happen to be running the borg now, so I figured I'd submit the issues as they came up, and let people deal with them whenever.

**Comment by agoodman00** [comment]
checked in https://github.com/angband/angband/pull/6036

**Comment by Netbrian** [comment]
Fix validated!
