### ISSUE TITLE
SDL2: "Perfect DOS" ttf font can now only be set up to Size 31 (blurry), not 32

### ISSUE THREAD

**Issue by smbhax** [angband/angband#6043]
MSYS2-compiled SDL2 front-end, latest Angband code, Windows 11.

I'm using a custom font, Perfect DOS VGA 437.ttf (download from https://www.dafont.com/perfect-dos-vga-437.font for instance), and while a year or so ago I was able to set its size to 32 in the SDL2 interface--a perfect multiple of its base size or whatever, so it comes out nice and sharp--in the current SDL2 interface, the size "+" button only allows it to go up to size 31, leaving it blurry.

![Untitled-1 copy](https://github.com/user-attachments/assets/16098733-2f40-4d14-852d-59e3bba5809a)

1) Download Perfect DOS VGA 437.tff and put it in angband's \lib\fonts folder
2) Run Angband with the SDL2 front end
3) In the SDL2 front end, select Menu - Angband - Font - Name - Perfect DOS VGA 437
4) In the SDL2 front end, select Menu - Angband - Size and click the "+" repeatedly
== The size can only be increased to 31, leaving the font blurry. Ideally, it would go to at least 32.

Size 16 is also nice and crisp but that's too small for easy viewing on my 1080p screen.

Workaround:

In \lib\user\sdl2init.txt, change

`subwindow-font:0:31:Perfect DOS VGA 437.ttf`

to

`subwindow-font:0:32:Perfect DOS VGA 437.ttf`

(but don't go too crazy with it; it's possibly screen-resolution-dependent, but on my 1080p screen for instance, if I've set the size number to over 41, the game starts with a pop-up error message, then quits out and blanks out the sdl2init.txt)

**Comment by backwardsEric** [comment]
Note that there is a hardwired internal limit of 32 (set by MAX_VECTOR_FONT_SIZE near the beginning of src/main-sdl2.c) for the size that can be used with a TTF font.  The menu will use a smaller limit when the subwindow's current size would not satisfy the minimum number of columns or rows with a larger font than that.

The patch fixed an off-by-one error for the maximum size allowed by the menu.

**Comment by smbhax** [comment]
(I wonder if that hardwired font size 32 limit could present readability issues for people with super high density displays. I don't have one of those so I can only speculate, but if it was limited to size 32 on a like 4K display--my current is only 1080p--that could be rather small and hard to read, if the scaling is linear.)
