### ISSUE TITLE
Borg Crashing When Respawning

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6074]
I finally got a proper reproducable example!  

For the g394de923a release of Angband, the borg explores this level, dies, and then crashes the game.  I've attached a savefile and my borg.txt!

[PLAYER.zip](https://github.com/user-attachments/files/17230291/PLAYER.zip)
[borg.txt](https://github.com/user-attachments/files/17230297/borg.txt)

@agoodman00

**Comment by agoodman00** [comment]
woohoo!  it crashes for me in the latest code :)
high ho the derry-o a debugging I do go.

**Comment by backwardsEric** [comment]
It looks like the reincarnate_borg() fires when the character falls into a pit trap.  That resets contents of the character's struct player setting the player's location to (0, 0) and player->cave to NULL.  When control returns to the trap handling logic, the player is not marked as dead and there's an attempt to move the player from (0, 0) to the location of the pit.  That either triggers an assertion in non-release builds or a NULL pointer dereference in release builds as the game tries to update the state of traps in the player's view of the cave.

To avoid that for the conditions in this case, I'd recommend that at exit from reincarnate_borg() the player's position and pointer to the player's view of the cave are the same as they were when reincarnate_borg() was called.

When player->is_dead or player->upkeep->generate_level are true, the trap-handling logic in the core game may want to bypass the bookkeeping it does after firing off the trap's effect and extra effect.

**Comment by agoodman00** [comment]
ok, my change fixes the pointer to the player's view of the cave.  I can also save and restore the players position.

**Comment by Netbrian** [comment]
This looks good!
