### ISSUE TITLE
Borg Perplexed By Potions

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6078]
I noticed that when running the borg on high levels, he'll spend a bit of time on dlvl 98, and then recall back to towns ("To Drop off Potions".)

However, once in town, the borg doesn't actually drop off potions (or need to.)

[Cirialf Potion.zip](https://github.com/user-attachments/files/17237106/Cirialf.Potion.zip)

Run this save for a few minutes and you'll see the behavior I'm referring to.

@agoodman00

**Comment by agoodman00** [comment]
Hmm.  Looks like the check to "drop off" potions doesn't take into account if he is trying to kill uniques.  I will add a "if max depth isn't 99+"

**Comment by agoodman00** [comment]
No, that won't work.  I think I need the check to be more complicated than that...  since he needs to regather potions if he used up all his potions killing the last batch of uniques... let me think about this.

**Comment by agoodman00** [comment]
ok, this one was a lot easier than I thought (see https://github.com/angband/angband/pull/6081).  I only need to check BI_PREP_BIG_FIGHT.  I think it takes care of this specific issue though the big picture of not behaving well around the endgame still needs work.

**Comment by Netbrian** [comment]
I noticed the borg isn't carrying around his EZ_Heal potions when looking to kill uniques.  Is that intentional?
[Cirialf.zip](https://github.com/user-attachments/files/17312030/Cirialf.zip)

**Comment by agoodman00** [comment]
I will check into it.  He should be carrying all the potions "he can"... so often he will fill up, run out of slots, dive down, explore a bit, use up some stuff, go back to town (eventually) gather up more potions, run out of slots... repeat till he uses up all his potions.  If he isn't gathering ANY ez_heal (*heal*) it is likely a bug.

**Comment by agoodman00** [comment]
Short answer, this is on purpose.  
Long answer, this is a case where he isn't "hunting uniques", he is just heading down and it happens to be that uniques are what is keeping him from going deeper.  He only carries around the trove of EZ_HEAL and such (the big stockpile of potions) when max depth is 99+.  They are FOR going after Morgoth but will be used to clean up remaining uniques before Morgoth if that is the only thing keeping him from going deeper to enter the final battle. 
I am still not sure he should be carrying around the extra potions unless all the uniques are dead... but for now, using them for "clean up" seems like a good compromise between only using them on Morgoth and using them to take out very tough baddies.

**Comment by Netbrian** [comment]
It looks like there's a difference in behavior between "borg hits level 98, goes into unique killing mode" (where he'll carry around a bunch of potions to help kill uniques) versus "borg_kills_uniques = TRUE", where all the potions are stored at home and he tries to kill uniques without them.

Is this intentional?

**Comment by agoodman00** [comment]
Yes, the "borg_kills_uniques = TRUE" setting just means "don't allow the borg to ever go deeper than where 3 uniques are native and alive".  This is a setting to be used to keep the borg from gettnig surrounded by uniques at lower levels.  It was added because a lot of borgs unable to kill the uniques because they kept ganging up on him and he had to run away.  
The behavior of killing off uniques at 98+ is for similar reasons... Morgoth has S_UNIQUE and it is hard enough for a borg to take on Morgoth when he is alone.  
So the reason he has potions for the second but not the first is that the potion gathering is for going after Morgoth.  The borg is using them to clean up uniques... but really that is accidental.  It is an accident that I am letting ride because once you get to 98, it is kinda nice to have the extra potions to clean up the remaining uniques.  It means burning them up before facing morgoth and having to regather them but it seems like it might be worth it.
I am not sure this is the right choice.  Do you have an opinion, @Netbrian?

**Comment by Netbrian** [comment]
I think this is something we'd need to test in debug mode.

My current borg is stuck on level 85, trying to kill Osse, and has been for a long time.  I'd want to test "if I give him a bunch of potions of life, can he beat Osse?"  If the potions help, it's worth changing.  Otherwise, we'd need to look into other parts of the AI.

**Comment by agoodman00** [comment]
I think if you put on dynamic calcs then change... hmmmm  ok I would try adding 
	value(trait, amt life): range(1, 99):: reward(10000);
and see if he starts grabbing life potions when he goes home.

**Comment by Netbrian** [comment]
I added the dynamic calculations, and the Borg started carrying around potions again.  He also ignored the command to kill uniques, and dived to 98.  

He still doesn't seem to be able to beat high-level uniques, even with 80 potions of life.

**Comment by agoodman00** [comment]
Hmmm the unique requirement should be separate from the dynamic calc check.  Let me double check... 
Ya, as far as I can tell turning on dynamic calcs doesn't change the unique check.  You sure you didn't accidentally put back borg_kills_uniques = fakse when you updated borg.txt?

**Comment by Netbrian** [comment]
I don't think so!

Is there a way I could demonstrate what's happening?  Would attaching a
save file help?

**Comment by agoodman00** [comment]
I can try with the save you already have attached and my suggested change to the borg.txt.  You are saying he should dive to depth 98, correct?  And does ^z2 also show that he is ready to be that deep?

**Comment by Netbrian** [comment]
Right.  My experience has been that if a borg is ready for level 98, he'll dive that far if dynamic calculations are enabled, even if borg_kills_uniques is set to true.

**Comment by agoodman00** [comment]
I am not catching him diving but I found an issue with how the living uniques are calculated that -might- have caused it.  https://github.com/angband/angband/pull/6091
It messed up knowing how many uniques were around if the max depth changed to below (above?  shallower) where there were three.

**Comment by agoodman00** [comment]
btw, going down a little bit is okay.  The borg often dives lower than he is "safe" if he is scared and the stairs down are closer than the stairs up.  This could happen a few times but being deeper than 3 or 4 levels out of depth seems like it shouldn't happen.

**Comment by agoodman00** [comment]
I just found another thing, maybe.  I added the use of deep descent recently as a means of escape.  I think it should be prioritized below escaping via WoR.  It goes deeper than your deepest depth and that will get you very deep very fast.

**Comment by Netbrian** [comment]
I retested the dynamic calculations, and I was wrong -- the borg does fine.  I'll keep tracking this!

**Comment by agoodman00** [comment]
There is an issue with the borg using deep descent but I can fix that separately

**Comment by Netbrian** [comment]
OK, please keep me posted when you do!

**Comment by agoodman00** [comment]
https://github.com/angband/angband/pull/6101 should help the deep descent issues

**Comment by Netbrian** [comment]
I'm still seeing issues with potions.  The borg is scumming for them, but doing so at very shallow dlevels.

He says this is due to needing teleport, but he has staves that he's simply not withdrawing from his house.

I don't know if I should leave this here or open a new issue.

**Comment by agoodman00** [comment]
which save should I be using to test this?   https://github.com/user-attachments/files/17312030/Cirialf.zip?  https://github.com/user-attachments/files/17237106/Cirialf.Potion.zip?

**Comment by Netbrian** [comment]
None of them.  Looks like Github didn't include my attachment as it should have.  Will include one later this evening.

**Comment by Netbrian** [comment]
This has been validated!
