### ISSUE TITLE
Borg Ranger Max Depth Issue

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6100]
I've noticed that there seems to be a problem with the borg and max depth.  Every now and then, the max depth gets set to a very high number for no apparent reason.  I set an auto-stop on dlvel 50, and it never trigger, but if you run it long enough, he keeps ending up with max depth of 99 somehow.

[Cirialf Ranger.zip](https://github.com/user-attachments/files/17398664/Cirialf.Ranger.zip)

@agoodman00

**Comment by agoodman00** [comment]
the deep descent fix https://github.com/angband/angband/pull/6101 should help this
