### ISSUE TITLE
Borg Questionable Store Scumming

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6103]
I've noticed a lot of weirdness with how the borg handles store scumming.

In the below example, the status shows he's store-scumming for a potion of *HEALING* at the black market.  However, he could just buy it outright.

[Store Scumming.zip](https://github.com/user-attachments/files/17420600/Store.Scumming.zip)

In other cases, he gives up on store scumming midway through, putters around the dungeon a bit, and then goes back to town and restarts the process.  I'll provide a better example of this a bit later.

@agoodman00

**Comment by agoodman00** [comment]
This guy looks like he is looking for teleport/teleport level scrolls.  The log (^p) shows 
# Leaving (restock)  restock teleport + teleport level 
probably should say "scrolls" on the end of that.

**Comment by Netbrian** [comment]
OK, here's a better example.

Tell this borg to money scum for a reasonable amount -- maybe $5000.

He'll get started, do it for a little while, and then give up and go back to the dungeon.

The status screen will still report him as scumming.

[Ninwe Teleport.zip](https://github.com/user-attachments/files/17446739/Ninwe.Teleport.zip)

**Comment by agoodman00** [comment]
Unfortunately the money scum code was added after I wound down my involvement in the borg code so I am going to have to try to figure out what was intended along side you.

**Comment by agoodman00** [comment]
okay after running it from what I can tell he is sticking around farming people but then doing a terrible job hunting them down and killing them for the profits.  Eventually he gets to the point where there are enough humans that he is worried about the danger and leaves.  My guess there has to be some adjustment in the "I have been waiting for townies to spawn.  Time to go on a murder spree" code.

**Comment by agoodman00** [comment]
and he isn't attacking people because he thinks the battle-scarred veterans (and possibly others) can hit to stun.  Eeeek!  that is bad.  That pumps up the danger of all badguys that falsely are interpreted as being able to stun by quite a bit.

**Comment by agoodman00** [comment]
https://github.com/angband/angband/pull/6109 might help.

**Comment by Netbrian** [comment]
What does this mean?

"10d2 is common but take and very low"

Also, it'll be interesting to see how the modified stun logic affects other things!

**Comment by Netbrian** [comment]
I'm still running into issues.  When I tell this borg to money scum (as a test), he just ignores me and starts diving.

The borg status screen still shows him as money scumming, but he isn't actually doing it.
[Uploading Cirialf 20241028.zip…]()

**Comment by agoodman00** [comment]
the link to the zip is broken.   I tried https://github.com/user-attachments/files/17446739/Cirialf 20241028.zip and that gave an error

**Comment by Netbrian** [comment]
Yeah, I noticed and edited the post just when you posted.  Try again.

Direct link -- https://github.com/user-attachments/files/17546263/Cirialf.20241028.zip

**Comment by agoodman00** [comment]
I got a l50 Druid with lots of cash from this zip.  I can tell him to scum money... 700,000 or something.  I just want to make sure I am testing what you are seeing.

**Comment by Netbrian** [comment]
Yes.  Ask him to scum a small amount of money, and then ask him to scum a large amount of money.  When I tried it, he just kept exploring.

**Comment by agoodman00** [comment]
ok, here is what I am seeing
1) I tell him to money scum 700,000 (so about 1000 more than he has)
2) zap his rod of recall to get him back to town (money scum only happens in town)
he explores but 
1)* doesn't pick up money (borgs don't collect money if they have more than 500,000) 
2)* he keeps getting stuck in "summoning halls" (he shouldn't be doing those in town... your town has some odd shapes)
3) he hangs out in town and picks up stuff eventually getting his money

1) I tell him to money scum 999,999 (the maximum enterable amount) 
same thing but he is hanging out in town a lot longer.  He may eventually twitch his way onto the stairs and leave but I haven't seen him do that yet. 

I can fix 1)* and 2)* .  Change 1 to "don't pick up money unless money scumming" and 2) "not in town".

**Comment by agoodman00** [comment]
this fix https://github.com/angband/angband/pull/6119 has the two issues above

**Comment by NickMcConnell** [comment]
Looks done than.
