### ISSUE TITLE
Borg Struggles With Shopping

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6107]
[Ninwe.zip](https://github.com/user-attachments/files/17445854/Ninwe.zip)

This borg seems to be struggling a lot with un-ided objects.  He keeps going into his house, freezing, leaving for a bit, and then going back to the house.

@agoodman00

**Comment by agoodman00** [comment]
Yup, he was counting what he could sell when he got to town and he shouldn't have been counting the un-ID'd stuff.  
see https://github.com/angband/angband/pull/6108

**Comment by Netbrian** [comment]
This is working now!
