### ISSUE TITLE
Borg Unable to Curse

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6113]
This borg keeps trying to cast the spell of curse, and then breaking.

[Cirialf 02.zip](https://github.com/user-attachments/files/17497497/Cirialf.02.zip)

@agoodman00

**Comment by agoodman00** [comment]
I am running into multiple bugs here.  
1) the CURSE spell needs to be on the "do not play with" list
2) the borg thinks his failure rate on CURSE is 15% but it is 40%
3) he tried to sell a staff listed as qty 0 giving a divide by zero error

**Comment by agoodman00** [comment]
"	/* Necromancers are punished by being on lit squares */
	if (player_has(player, PF_UNLIGHT) && square_islit(cave, player->grid)) {
		chance += 25;
	}
"
well, I didn't know about that! Bummer...  I bet borg necromancers are having all sorts of issues.

**Comment by agoodman00** [comment]
I checked in https://github.com/angband/angband/pull/6114 but necromancers need more work.  I am thinking they should never be carrying light, no?  That is going to take a bunch of coding.
I also notice the necro borg beats the crap out of itself using CRUSH excessively.  There is safeguard code to make sure you don't actually DIE casting the spell but it seems like it is over used.

**Comment by Netbrian** [comment]
I noticed the same problem with Crush, but it's hard to judge how much was a calculated risk.

In this case, the borg seems to be having Curse problems in another way.  Not sure what's going on.

[Cirialf 03.zip](https://github.com/user-attachments/files/17498520/Cirialf.03.zip)

**Comment by agoodman00** [comment]
okay, this is a targeting problem.  I have seen it before and just hadn't gotten around to fixing it since it only happens in town... and it happens to other classes to.  You can't target through trees and the borg isn't keeping track of trees or at least isn't doing a great job of it.

**Comment by Netbrian** [comment]
I've actually seen something similar in the dungeon, but haven't been able to easily reproduce it.  The borg really struggles when trying to target a monster if there are dark squares in the targeting path.

**Comment by agoodman00** [comment]
A couple of bad shots through the dark are expected.  The borg should be doing a 
1) shoot at baddie.  
2) Listen for "ouch"
3) if no "ouch" on next round, mark a unknown square between you and them as "wall" 
Often this results in multiple shots while it guesses at why it is missing.  
The case above is worse because there is no unknown squares to mark as walls, just "passable rubble" which the borg can see and walk through but not shoot through.  Trees are the same issue and I think webs have some issues.

**Comment by agoodman00** [comment]
okay I added some code to change crush to use a routine that does better at passable rubble.

**Comment by Netbrian** [comment]
> A couple of bad shots through the dark are expected. The borg should be doing a
> 
> 1. shoot at baddie.
> 2. Listen for "ouch"
> 3. if no "ouch" on next round, mark a unknown square between you and them as "wall"
>    Often this results in multiple shots while it guesses at why it is missing.
>    The case above is worse because there is no unknown squares to mark as walls, just "passable rubble" which the borg can see and walk through but not shoot through.  Trees are the same issue and I think webs have some issues.

I'm not sure that's quite what's happening.

It's tough to reproduce, but I saw this borg constantly trying and failing to hit a bat with Stinking Cloud with this savefile.  He ended up just getting stuck until time ran out.  Unfortunately, if you reload it, he won't necessarily do the same thing.

I can open a new issue if required, and I'll look for a better example.

[Cirialf.zip](https://github.com/user-attachments/files/17526886/Cirialf.zip)

**Comment by agoodman00** [comment]
unless I did something wrong, this is a l43 Blackguard, not someone who can cast Stinking Cloud.  I am running into MAIM_FOE being another that needs to be added to the "do not play" list out of this save but not the aim issue.

**Comment by agoodman00** [comment]
( the maim foe checkin https://github.com/angband/angband/pull/6118)

**Comment by Netbrian** [comment]
I'll open another issue for the targetting.
