### ISSUE TITLE
Borg Blackguard Bugs

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6116]
The borg keeps trying to use Forceful Blow in town, and it doesn't work.  He eventually gives up and goes back into the dungeon.

[Cirialf.zip](https://github.com/user-attachments/files/17512960/Cirialf.zip)

@agoodman00

**Comment by agoodman00** [comment]
okay, that is a "needs a target".  I actually haven't coded FOR "Forceful Blow" yet.  I just need to make it so he can't "play" with that... then I need to add code so he does it when he should (but that is another bug)

**Comment by agoodman00** [comment]
https://github.com/angband/angband/pull/6117

**Comment by agoodman00** [comment]
If he is trying to cast it in town, just wait for https://github.com/angband/angband/pull/6118 which should fix it.
