### ISSUE TITLE
Borg Trouble with Targeting

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6120]
This issue is unfortunately quite hard to reproduce when reloading from a save file, but I've seen it a few times now.

In this example, the borg kept trying to use lightning strike on the warrior and failing.  I've seen similar issues before when there's darkness between the borg and a monster.  Eventually he'll give up due to being on the level too long and leave.

[Cirialf 02.zip](https://github.com/user-attachments/files/17548756/Cirialf.02.zip)

When you reload the save, the borg does something else, so it's been hard to figure out how to file the bug report.

@agoodman00

**Comment by agoodman00** [comment]
hmm, it seems lightning strike has a special caveat "square must be know".  I am going to have to add code to add this check.

**Comment by Netbrian** [comment]
I think this happens with a few other spells, like stinking cloud.  I'll keep an eye out for it.

**Comment by agoodman00** [comment]
I can only fix em when I can duplicate em.  I have seen aim failures as well so I know you aren't making it up I just haven't got a good duplication case so I haven't been able to fix it yet.

This fixes the lightning strike https://github.com/angband/angband/pull/6121
