### ISSUE TITLE
Borg Coin Conundrum

### ISSUE THREAD

**Issue by Netbrian** [angband/angband#6129]
[Cirialf Coins.zip](https://github.com/user-attachments/files/17601634/Cirialf.Coins.zip)

The Blackguard Borg seems to be struggling to deal with these coins.  It looks like a Leaping failure.

This is with the latest version!

@agoodman00

**Comment by Netbrian** [comment]
Here's a similar issue with Shatter Stone.

[Cirialf Shatter.zip](https://github.com/user-attachments/files/17601744/Cirialf.Shatter.zip)

**Comment by agoodman00** [comment]
hopefully https://github.com/angband/angband/pull/6130 will help

**Comment by Netbrian** [comment]
This is fixed!
