### ISSUE TITLE
Toggle indicator in post 4.2.5 SDL2 front end is not intuitive

### ISSUE THREAD

**Issue by backwardsEric** [angband/angband#6134]
Split off from https://github.com/angband/angband/issues/6058 .  smbhax's comment there was:

Incidentally, the white square indicator for the toggle state is not very intuitive--it doesn't say "this is a toggle, toggled on" to me; actually, it looks more like a checkbox that is currently toggled OFF (although that would more obviously be an empty box rather than a filled box; and a toggle toggled on would usually be a box with a check mark in the middle).

The white square also doesn't work well as an indicator of the current selection in an option list, such as the font list--it's very easy to overlook. Something like a different color background for the currently selected item would be much easier to see at a glance--although I suppose that gets into a question of whether more colors are available to use there.

Because of https://github.com/angband/angband/issues/5596 and the fact that the colors are drawn from whatever has been loaded into Angband's color table, the menus use three colors (foreground, background, and a shadow color).  My bias for any replacement for the toggle indicator would be to similarly use a very restricted palette.  The choice of the shape the toggle indicator (nothing drawn when off, square in the foreground color when on) was chosen because it was simple to render and because the on/off representations would be clearly different even for a small menu font where the indicator would be correspondingly small.  An empty square border for the off indicator and that same square border with an inscribed "x" could work - would need to check it with a small menu font.

**Comment by rodrigogonzalez230912** [comment]
I don`t open the game I don`t now 😭
