### ISSUE TITLE
AU holdings on tombstone display

### ISSUE THREAD

**Issue by fruviad** [angband/angband#6160]
I just finished up a game.  Killed Morgoth, exported my character, and uploaded it to The Ladder.

After I uploaded the character to the Ladder, I killed off one or two remaining Uniques that I hadn't taken down before reaching dLvl 100, and then I returned to the Town and retired.

I realized when looking at the tombstone display for my character that the numbers were incorrect.  The XP seems correct, but the AU value is extremely incorrect.  The numbers might have changed slightly between the export of the character and the actual retirement in town, but the Ladder is reporting my final Gold value as "145841".  In contrast, the tombstone was reporting AU as "10145841".

Given that the tombstone's value is simply the character sheet's value prepended with "10", I'm guessing that I probably didn't pickup any more gold, and that a "10" is being added to the display for some reason.

In an attempt to reproduce the bug I created a pair of new characters, retiring one immediately, and the other after spending all my gold that's allocated upon birth.  In both cases the AU values were reported correctly on the tombstone.

I have a script that I use to start Angband.  It sets window sizes and positions, and as part of it I make a backup of the existing savefile.  I copied one of the savefiles that dates to the point where I was ready to drop to dLvl 99, so I reverted to that savefile and retired that character.  The AU values were reported correctly on the tombstone in that instance.

Perhaps this only manifests if one reaches dLvl 100, or if one kills Morgoth and wins the game?

I can make savefiles available for repro purposes if desired.  I'm attaching a screenshot of the tombstone with the incorrectly-reported AU value.  The character file is saved on the Ladder under the name "Elydhon"; as of this moment, it's the only character with that name.

![Screenshot from 2024-12-25 18-21-20](https://github.com/user-attachments/assets/6c29a3a3-8103-4966-9d27-549f556ee359)

**Comment by slodplaadmin** [comment]
This can be closed.  I dug through the code and realized that this is working as designed.   Retiring in the town adds a tidy sum to one's AU total.

player-util.c:
```
    /* Retire in the town in a good state */
    if (p->total_winner) {
        p->depth = 0;
        my_strcpy(p->died_from, "Ripe Old Age", sizeof(p->died_from));
        p->exp = p->max_exp;
        p->lev = p->max_lev;
        p->au += 10000000L;
    }

```

**Comment by fruviad** [comment]
This can be closed, as I've realized it is working as designed; Retire in town, get a bonus in AU.

player-util.c:
```
    /* Retire in the town in a good state */
    if (p->total_winner) {
        p->depth = 0;
        my_strcpy(p->died_from, "Ripe Old Age", sizeof(p->died_from));
        p->exp = p->max_exp;
        p->lev = p->max_lev;
        p->au += 10000000L;
    }
```

**Comment by NickMcConnell** [comment]
Thanks for checking for yourself, I hadn't got around to it 😄
